### ISSUE TITLE
MACCS (166bit) Fingerprint returns fingerprint of length 192

### ISSUE THREAD

**Issue by al-pi314** [cdk/cdk#1005]
I have noticed that my MACCS fingerprints generated in python using scyjava were actually 192 long, when they should be only 166bit long according to documentation at [CDK Java Docs](http://cdk.github.io/cdk/latest/docs/api/org/openscience/cdk/fingerprint/MACCSFingerprinter.html) and also [here](https://chem.libretexts.org/Courses/Intercollegiate_Courses/Cheminformatics/06%3A_Molecular_Similarity/6.01%3A_Molecular_Descriptors).

I recreated the pipeline built in python directly in java for testing and used the latest [cdk-2.9.jar](https://github.com/cdk/cdk/releases/tag/cdk-2.9) file. This is my Test.java file:
```java
import org.openscience.cdk.fingerprint.MACCSFingerprinter;
import org.openscience.cdk.DefaultChemObjectBuilder;
import org.openscience.cdk.inchi.InChIGeneratorFactory;
import org.openscience.cdk.inchi.InChIToStructure;
import org.openscience.cdk.interfaces.IAtomContainer;
import org.openscience.cdk.fingerprint.IBitFingerprint;
import org.openscience.cdk.interfaces.IChemObjectBuilder;

public class Test {
    // main method
    public static void main(String[] args) throws Exception {

        MACCSFingerprinter fingerprinter = new MACCSFingerprinter();
        
        InChIGeneratorFactory factory = InChIGeneratorFactory.getInstance();
        IChemObjectBuilder builder = DefaultChemObjectBuilder.getInstance();

        InChIToStructure structure = factory.getInChIToStructure("InChI=1S/C25H41NO2Si2/c1-20(14-15-22-12-10-9-11-13-22)26-21(2)25(28-30(6,7)8)23-16-18-24(19-17-23)27-29(3,4)5/h9-13,16-21,25-26H,14-15H2,1-8H3", builder);

        IAtomContainer mol = structure.getAtomContainer();

        IBitFingerprint fingerprint = fingerprinter.getBitFingerprint(mol);

        System.out.println(fingerprint.asBitSet().size());
        System.out.println(fingerprint.asBitSet().toString());
    }  
}
```

When I run java -cp cdk-2.9.jar Test.java the result is:

192
{19, 29, 73, 85, 89, 92, 94, 101, 103, 107, 110, 111, 112, 114, 115, 123, 124, 125, 126, 129, 140, 142, 144, 146, 147, 148, 150, 151, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164}

Are the bits after 165th index redundant? Looking at the source code the key should be 166bit long and could not be 192?

**Comment by johnmay** [comment]
Computers work in words of size 8,16,32,64. Java bitset uses 64 bit longs so any shorter fingerprint is rounded up to the neared size: 192/3 = 64.

The Maccs 166 are a bit of a relic and of limited use today beyond “this was a thing”. Even back when they were created I have no idea why they used such a strange size since it doesn’t fit nicely in any common (computer) word size.

**Comment by al-pi314** [comment]
Learned something new about Java - Thanks for the explanation.
