### ISSUE TITLE
Can CDK toolkit do products generation for reactions like rdChemReactions in rdkit?

### ISSUE THREAD

**Issue by Le0nT1** [cdk/cdk#1016]
Hi,
Just wondering if the CDK toolkit can do products generation given the reactants and reaction SMIRKS (smarts).
I used ambit2.smarts.SMIRKSManager to do such products generations in Java with cdk toolkit however it has not been updated since 2018.
I know rdkt has a "from rdkit.Chem import rdChemReactions" library that takes reactants and reaction smirks as input and outputs the product, if CDK toolkit has a similar feature then it will be very helpful and I would like use it.

Thanks

**Comment by johnmay** [comment]
WIP #916, that branch is relatively stable there will even been an to mimick the RDKit semantics which are quite different to everyone else. See also - SmirksQuirks : https://nextmovesoftware.com/talks/Mayfield_SmirksQuirks_AcsFall_2023.pdf

**Comment by biotech7** [comment]
Hi, John
As an organic synthesis chemist working in a laboratory, I find it both interesting and amazing. hopefully merged into main branch as soon as possible.

**Comment by mrwns** [comment]
it has been merged now.
