### ISSUE TITLE
Possible bug in DepictionGenerator aromatic display

### ISSUE THREAD

**Issue by JonasSchaub** [cdk/cdk#1057]
Dear all,
when I depict the structure encoded by the SMILES code "cc(c)C" using DepictionGenerator, I get this output:
![aromatic-fragment](https://github.com/cdk/cdk/assets/44881147/ae0a79f6-33d6-4402-97ec-d66e2b6ce642)
I know, the structure "makes no sense" and cannot be kekulized but it is a fragment we get from a substructure analysis and the information that these three carbon atoms are aromatic should be preserved. If I remove the one aliphatic carbon ("ccc"), I get this structure with aromatic display:
![aromatic-fragment](https://github.com/cdk/cdk/assets/44881147/15910d60-064e-48bb-a087-eefb50b52f2c)
This structure with the aliphatic carbon as a substituent on one of the aromatic carbons is what I would expect for the first structure as well. 

What do you think about this?

Here is my full example code:
```
String smilesCode = "cc(c)C";
SmilesParser smiPar = new SmilesParser(DefaultChemObjectBuilder.getInstance());
smiPar.kekulise(false);
IAtomContainer container = smiPar.parseSmiles(smilesCode);
DepictionGenerator generator = new DepictionGenerator().withAromaticDisplay().withSize(512, 512).withFillToFit();
generator.depict(container).writeTo("aromatic-fragment.png");
```

**Comment by johnmay** [comment]
Agree - will take a look
