### ISSUE TITLE
products generation mismatch on SMIRKS pattern

### ISSUE THREAD

**Issue by biotech7** [cdk/cdk#1067]
Based on _Diels-Alder Cycloaddition_ SMIRKS pattern: 
`[#6:4]=[#6:3]-[#6:2]=[#6:1].[#6:5]=[#6:6]>>[#6:5]-1-[#6:6]-[#6:1]-[#6:2]=[#6:3]-[#6:4]-1`
Failed to generate product of `O1C=CC=C1.O=C1C=CC(=O)O1`, but succeeded in `C1C=CC=C1.O=C1C=CC(=O)O1`.
Accordingly，`O=C(C1=CC(C(C=C1)=O)(OC)OC)OC.S1C=C(C)C=C1` failed，but `O=C(C1=CC(C(C=C1)=O)(OC)OC)OC.C1C=C(C)C=C1`
succeeded. 

CDK: branch of smirks v2.10
JDK: 17.0.7

**Comment by egonw** [comment]
> CDK: branch of smirks v2.10

I don't expect it to change, but can you plz run it on the CDK 2.10-SNAPSHOT too? (Available from Sonatype)

**Comment by johnmay** [comment]
Probably aromaticity, you have correctly used `#6` but = and - only match aliphatic bonds. You probably want -,: and =,: to be portable, alternatively you can turn off aromaticity but then your SMIRKS is definitely not portable

**Comment by biotech7** [comment]
@egonw 
I built CDK 2.10-SNAPSHOT, it didn't include the updated smirks module while branch of smirks did.

@johnmay 
By addition of aromaticity pattern, it was matched.
`[#6:1]=,:[#6:2][#6:3]=,:[#6:4].[#6:6]=[#6:5]>>[#6:3]-1=,:[#6:2]-[#6:1]-[#6:6]-[#6:5]-[#6:4]-1`
But this pattern mismatched benzene ring，such as:
`O(C1C=CC2C=CC=CC=2C=1)[C@@H]1C=CC(=O)O1.C1=CCCC=C1`
Since，in _Diels-Alder Cycloaddition_ benzene ring is not implementable.
I'll have a second thought for one more sophisticated SMIRKS pattern on _Diels-Alder Cycloaddition_.

**Comment by johnmay** [comment]
It's been merged in so should be there

**Comment by johnmay** [comment]
Unfortunately writing good/correct SMARTS is a bit of an art form. Aromaticity in particular makes things very tricky and needs lots of care and attention. My other suggestion was turn of the preprocessing which aromatizes with Daylight aromaticity and switch to something like MDL which keeps furan/pyrrole kekulé but delocalises benzene.

**Comment by biotech7** [comment]
Thanks, I'll compile the main branch for the latest smirks module. I am presently engaged in the meticulous compilation of thousands of SMIRKS patterns by hand, following the unsuccessful attempt to automate the process with the assistance of AI technologies, including ChatGPT-4. The task at hand is both laborious and daunting but meaningful.
