### ISSUE TITLE
Exception thrown when AllRingsFinder .findAllRingsInIsolatedRingSystem processes small molecule

### ISSUE THREAD

**Issue by ChemMitch** [cdk/cdk#1068]
When I run the following code runs, it produces this exception:
java.lang.IllegalArgumentException: graph was acyclic

It would be more useful if the method returned an empty ring set.

		String userDirectory = new File("").getAbsolutePath();
		String fileName =userDirectory + "/src/test/resources/mols/methane.mol";
		File molFile = new File(fileName);
		InputStream inputStream = new FileInputStream(molFile);
		MDLV2000Reader reader = new MDLV2000Reader(inputStream);
		IAtomContainer container=  reader.read(new AtomContainer());
		AllRingsFinder arf = new AllRingsFinder();
		IRingSet ringSet= arf.findAllRingsInIsolatedRingSystem(container, 3);

**Comment by johnmay** [comment]
``findAllRings`` not ``findAllRingsInIsolatedRingSystem`` the later one makes some assumptions about the molecule (and checks these). 

What are you trying to do there are likely more optimal ways of doing, typically now you wouldn't interact with AllRingsFinder directly but rather through [Cycles](https://cdk.github.io/cdk/latest/docs/api/org/openscience/cdk/graph/Cycles.html) like this:

```java
// use the builder otherwise you will get stung in future
IChemObjectBuilder builder = SilentChemObjectBuilder.getInstance();
IAtomContainer container=  reader.read(builder.newAtomContainer());

Cycles cycles = cf.find(m);
IRingSet rings  = cycles.toRingSet();
```
