### ISSUE TITLE
IllegalClassFormatException: Error while instrumenting sun/util/resources/cldr/provider/CLDRLocaleDataMetaInfo for Java 21

### ISSUE THREAD

**Issue by javadev** [cdk/cdk#1073]
![Screenshot_519](https://github.com/cdk/cdk/assets/348496/2b4988cc-9bf2-40a9-9db7-acb7e504d510)

**Comment by egonw** [comment]
I can confirm this. Java 11 is fine.

**Comment by egonw** [comment]
I'll make a patch to upgrade the Maven building stack.

**Comment by johnmay** [comment]
It's the jacoco instrumentation, might just need an update but it only needs to be run for one anyways (e.g. the sonar cloud build makes most sense)

**Comment by egonw** [comment]
> might just need an update

confirmed, see the draft PR

**Comment by egonw** [comment]
> but it only needs to be run for one anyways (e.g. the sonar cloud build makes most sense)

Writing a patch...
