### ISSUE TITLE
Byproduct generated by multiple R groups SMIRKS pattern

### ISSUE THREAD

**Issue by biotech7** [cdk/cdk#1077]
Hi,
  As to _Sharpless Allylic Amination_ reaction, SMIRKS pattern with multiple R groups was compiled, as follows:
[#6:3]-[#6:2]=[#6:1].[$([#6]-c1ccc(cc1)S(=O)(=O)[#7:6]=[Se:5]=[#7:4]S(=O)(=O)c1ccc(-[#6])cc1),$([#6]C([#6])([#6])[#7:6]=[Se:5]=[#7:4]C([#6])([#6])[#6])]>>[*:7]-[#7H:4]-[#6H0,#6H1:3]-[#6:2]=[#6:1]
reaction scheme pattern as:
<img width="749" alt="1715843799047" src="https://github.com/cdk/cdk/assets/49674341/b35ca62e-baef-41d7-8324-00daaa59df9e">
 
test reaction smiles: `C=C1CCCC1.N(S(C1C=CC(C)=CC=1)(=O)=O)=[Se]=NS(C1C=CC(C)=CC=1)(=O)=O`
result:` C=C1[CH2](CCC1)N*.N(S(c1cc[c]cc1)(=O)=O)=[Se]=NS(c2ccc(C)cc2)(=O)=O`
By running Smirks.apply(mol), byproduct(or unreasonable product) was generated like: N(S(c1cc[c]cc1)(=O)=O)=[Se]=NS(c2ccc(C)cc2)(=O)=O

Is it due to unreasonable SMIRKS pattern or a bug?

CDK: cdk v2.10 SnapShot
java: jdk17.0.7
ide: IDEA 2024.1

**Comment by johnmay** [comment]
In SMIRKS if you don't remove it in the pattern it doesn't get removed. However there is an option which I think does what you want:

SmirksOption.REMOVE_UNMAPPED_FRAGMENTS

https://github.com/cdk/cdk/blob/main/tool/smarts/src/main/java/org/openscience/cdk/smirks/SmirksOption.java#L75

This is on if you switch to "RDKit" flavour but that will also still updating your valences automatically as well which can be problematic

**Comment by biotech7** [comment]
Ok, I'll verify it later. In organsynthesis practices, unreasonable products in a reaction scheme can lead to significant misunderstandings.

**Comment by johnmay** [comment]
SMIRKS is like a programming language, doing things you didn't ask for is dangerous. But yes it is a common requirement that users want to write loose patterns that will then remove parts they didn't care about.

**Comment by biotech7** [comment]
In production env., convertion of some reaction to proper SMIRKS pattern proves to be particularly challenging. e.g.: _**Shiina Macrolactonization reaction**_，reaction scheme partially like：
<img width="409" alt="1" src="https://github.com/cdk/cdk/assets/49674341/1ac1d434-7dd4-4ce6-a7bc-665b84536a36">
and its patterns:
`[$([#8:1]-[#6:2]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4]),$([#8:1]-[#6:2]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:3](-[#8:5])=[O:4])]>>[$([O:4]=[#6:3]-1-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8:1]-1),$([O:4]=[#6:3]-1-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6]-[#6:2]-[#8H0:1]-1)]`
but it generated unreasonable product in terms of reactant: `OC(CCCCCCCCCCCCCCO)=O`
Could the failure of the transformation be attributed to the unmapped atoms on the right-hand side (RHS)?

**Comment by biotech7** [comment]
Got it. Separated link nodes and mapped RHS are both necessary.
At the point of _**Shiina Macrolactonization reaction**_,the number of link nodes and atom types are both arbitrary, which increases the difficulty of compilation of universal/corresponding pattern for intramolecular reaction. So, is there any simple algorithm/strategy for compiling such kind of multi-pattern intramolecular reaction?

**Comment by johnmay** [comment]
You should use more of the expressions, v/D/X/H to constrain the pattern and you can do a generalised one like this. Any atom which isn't present in the pattern is left alone.

You also should be modifying hydrogen counts on oxygen no?

Something like this perhaps:

```
[O;H1+0,H0-:1][Cv4H2+0:2].[Cv4H2+0:3][Cv4H0+0:4]([O;H1+0,H0-:5])=[OD1H0+0:6]>>[O:6]=[C:4]([OH0+0:1][C:2])[C:3]
```

**Comment by biotech7** [comment]
Thanks,John. Maybe it's a challenging job to summarized a unique algorithm for intramolecular reaction.
