### ISSUE TITLE
ensure that calls to DefaultChemObjectReader::handleError emit log entries

### ISSUE THREAD

**Issue by uli-f** [cdk/cdk#1111]
`DefaultChemObjectReader` does two things in response to a call to any of its `handleError` methods:
- it delegates to its `IChemObjectReaderErrorHandler`
- depending on  `IChemObjectReader.Mode` it throws a `CDKException`

The `IChemObjectReaderErrorHandler` of `DefaultChemObjectReader` is initialized to `null`, so that the error is actually not handled at all by default.

It might be advantageous to at least log any error. This could be done by
1. provide an implementation of `IChemObjectReaderErrorHandler` and assigning `DefaultChemObjectReader.errorHandler` to an instance of this implementation OR
2. add logging to the `handleError` methods of `DefaultChemObjectReader`

I am happy to do a PR once there is an agreement how to approach this.

**Comment by johnmay** [comment]
or ILoggingTool sorry... the reason is a log isn't that useful on a server and so you would normally want to override the handler to return content back to the front end.

**Comment by johnmay** [comment]
Thing this is fixed with that PR now right?
