### ISSUE TITLE
Parsing stereochemistry?

### ISSUE THREAD

**Issue by ChemMitch** [cdk/cdk#1113]
Is there a way perceive the R/S stereochemistry from a structure with marked bonds?
[test_stereo.mol.txt](https://github.com/user-attachments/files/17157917/test_stereo.mol.txt)

For example, read the attached molfile and return that atom 2 and 4 are both R.

**Comment by johnmay** [comment]
There is an OK CIP implement in CDK but I would recommend using the dedicate library: https://github.com/SiMolecule/centres. This uses CDK and provides a command line tool and an API. The simplest thing though is to use CDK depict.


<img width="625" alt="Screenshot 2024-09-27 at 09 39 12" src="https://github.com/user-attachments/assets/417f1810-791e-4ee7-82d1-279be6ee9eef">


I would caution though CIP isn't perhaps as useful as you might think, what is your use case?

**Comment by ChemMitch** [comment]
Thanks!
My use case was to take a structure with one unspecified stereocenter and generate 2 stereoisomers, one with R the other with S.
I found a way to set bonds so we have both stereoisomers but I didn't know which was which.
