### ISSUE TITLE
Depicting terminal methyl groups

### ISSUE THREAD

**Issue by parit** [cdk/cdk#1121]
Hello,

Is there a setting in DepictionGenerator for showing only Terminal methyl groups (withCarbonSymbols show all the carbons). For ex, I used the following code for the attached [CHEBI_16066.mol.txt](https://github.com/user-attachments/files/17520418/CHEBI_16066.mol.txt) file. 

```
try (MDLV2000Reader reader = new MDLV2000Reader(new StringReader(mol)))
{
	IAtomContainer container = reader.read(
		DefaultChemObjectBuilder.getInstance().newInstance(IAtomContainer.class));
	DepictionGenerator myGenerator = new DepictionGenerator()
		.withAtomColors(new CDK2DAtomColors())
		.withBackgroundColor(Color.WHITE)
                .withCarbonSymbols();
	myGenerator.depict(container).writeTo("svg", new FileOutputStream("16066.svg"));
} catch (Exception e)
{
	e.printStackTrace();
}
```

And got the following image.

![16066](https://github.com/user-attachments/assets/8461d37d-b757-4262-87b8-65a8efeaf292)

**Comment by johnmay** [comment]
``withTerminalCarbons()``?

```
try (MDLV2000Reader reader = new MDLV2000Reader(new StringReader(mol)))
{
	IAtomContainer container = reader.read(
		DefaultChemObjectBuilder.getInstance().newInstance(IAtomContainer.class));
	DepictionGenerator myGenerator = new DepictionGenerator()
		.withAtomColors(new CDK2DAtomColors())
		.withBackgroundColor(Color.WHITE)
                .withTerminalCarbons();
	myGenerator.depict(container).writeTo("svg", new FileOutputStream("16066.svg"));
} catch (Exception e)
{
	e.printStackTrace();
}
```

You have full control under "symbol visibility" option, the wiki page gives good details: https://github.com/cdk/cdk/wiki/Standard-Generator#symbol-visibility. You can set with manually using ``withParam``. 

If you want the them to appear as "Me" you would do that with abbreviations.


```java
Abbreviations abbr = new Abbreviations();
abbr.add("*C Me");

IAtomContainer mol = ...;
abbr.apply(mol);
```

**Comment by parit** [comment]
Thanks @johnmay dunno how I completely missed it. Thanks again.

**Comment by johnmay** [comment]
BTW got a cool patch incoming that generates Haworth depictions that might be nice for ChEBI/RHEA... 

![Screenshot 2023-10-02 at 15 59 09](https://github.com/user-attachments/assets/a79fef63-1839-40b9-a605-bde1ad4a8eca)
![Screenshot 2023-10-02 at 15 58 35](https://github.com/user-attachments/assets/7cfe2e2a-43ef-4179-9a07-c615dcc0d3bb)

Although I think the pipeline is you have the coords/layout already, but still neat for sugers

**Comment by parit** [comment]
This looks good. I can show this to RHEA curators.
