### ISSUE TITLE
can't generate an absolute SMILES with "*" in it

### ISSUE THREAD

**Issue by adalke** [cdk/cdk#272]
I have been investigating how CDK uses InChI to generate Universal SMILES. InChI doesn't handle all of SMILES. For example, it doesn't handle atoms with an atomic number of 0 ("*"), which means the following bit of Jython code fails:

```
from org.openscience.cdk.smiles import SmilesParser
from org.openscience.cdk.silent import SilentChemObjectBuilder
sp = SmilesParser(SilentChemObjectBuilder.getInstance())
mol = sp.parseSmiles("*c1ccccc1")
from org.openscience.cdk.smiles import SmilesGenerator
sg = SmilesGenerator.absolute()
sg.create(mol)
```
It gives the exception:
```
org.openscience.cdk.exception.CDKException: org.openscience.cdk.exception.CDKException: An InChI could not be generated and used to canonise SMILES: null
```

**Comment by johnmay** [comment]
Yes as you would expect? The bigger issues with universal SMILES is the
mobile charges. I know how (and have) written correct and faster
canonicalisation algorithms but haven't had time to put this in CDK (it is
more likely to go in Beam).

John

**Comment by adalke** [comment]
I phrased it poorly. A better report might be "CDK can't generate an absolute SMILES if the structure contains a *". That is independent of the implementation.

One solution might be to use a different algorithm if there is a "*" in the SMILES, as you mentioned would be possible but take time.

Another might be to sacrifice element 'Og' or whatever the upper end of InChI is, and map all atoms with atomic number 0 to that atomic number. This is a hack, but easier than option 1 and unlikely to cause real-world problems.

A third might be to document SmilesGenerator.absolute and SmiFlavor to describe which structures cannot be generated as output, similar to how it documents "With delocalised charges the generated SMILES can be non-canonical." This is almost certainly the easiest.

I'm fine with any of these.

**Comment by johnmay** [comment]
Fixed: https://github.com/cdk/cdk/pull/276

New canonicalisation will be added eventually but the hack using Rf (highest I could use to due old JNI InChI build) works okay. The only limitation is if there is both an [Rf] and a '*' in the output.
