### ISSUE TITLE
some isotopes missing in SMILES generation

### ISSUE THREAD

**Issue by adalke** [cdk/cdk#273]
The following Jython code gives two examples where round-tripping a SMILES causes it to lose some isotope information:
```
>>> from org.openscience.cdk.smiles import SmilesParser
>>> from org.openscience.cdk.silent import SilentChemObjectBuilder
>>> from org.openscience.cdk.smiles import SmilesGenerator
>>> sp = SmilesParser(SilentChemObjectBuilder.getInstance())
>>> sg = SmilesGenerator.isomeric()
>>> mol = sp.parseSmiles("[13CH3][12CH3]")
>>> sg.create(mol)
u'[13CH3]C'
>>> mol = sp.parseSmiles("[13CH3][16OH]")
>>> sg.create(mol)
u'[13CH3]O'
```
I expected those create() to return a SMILES with the isotopically labelled 12C and 16O, respectively.

My guess is that if the atomic mass is close to the natural abundance then the isotopic SMILES generator omits the isotope.

**Comment by johnmay** [comment]
Historically, many users add on the atomic mass automatically (Isotope
configuration) and so a compromise had to made where by any major isotope
can not be round tripped.

Essentially the 'normal' configured state for CDK atoms is to have a set
atomic mass hence without this compromise everyone's SMILES would have all
isotopes specified.

https://github.com/cdk/cdk/blob/master/storage/smiles/src/main/java/org/openscience/cdk/smiles/CDKToBeam.java#L205

**Comment by johnmay** [comment]
In fact, I can now just add an option for this... as it has annoyed me for
a while. SmiFlavor.AtomMassStrict will now give the expected behaviour.

**Comment by adalke** [comment]
A flag would work for me, thanks.

[79Br] with mass of 78.918 is, after all, lighter than [Br] with a mass of 79.904.

**Comment by johnmay** [comment]
Yeah it's nasty, patched now: https://github.com/cdk/cdk/pull/275

**Comment by johnmay** [comment]
Resolved
