### ISSUE TITLE
atom map classes not included in canonical SMILES ordering

### ISSUE THREAD

**Issue by adalke** [cdk/cdk#274]
I can ask the canonical SMILES generation to include the atom map class in the output. However, the map class values are not included in the canonicalization ordering. This means I cannot canonicalize a SMILES string which differ only by the atom class. Here's an example using Jython:
```
>>> from org.openscience.cdk.smiles import SmilesParser
>>> from org.openscience.cdk.silent import SilentChemObjectBuilder
>>> from org.openscience.cdk.smiles import SmilesGenerator
>>> sp = SmilesParser(SilentChemObjectBuilder.getInstance())
>>> sg = SmilesGenerator.unique().withAtomClasses()
>>> mol = sp.parseSmiles("[CH3:1][CH3:2]")
>>> sg.create(mol)
u'[CH3:1][CH3:2]'
>>> mol = sp.parseSmiles("[CH3:2][CH3:1]")
>>> sg.create(mol)
u'[CH3:2][CH3:1]'
```

I expected the two create() calls to be identical because 1) the equivalent SetFlavor() for OEChem uses the flavor parameters to specify the invariants, 2) RDKit includes the atom class as part of the canonicalization, if present, and 3) the CDK documentation shows that some flavors (like SmiFlavor.Stereo | SmiFlavor.AtomicMass) affect the canonical ordering, and doesn't say which flavors don't affect the ordering; I assumed that all of the ones which could affect the ordering, do affect the ordering.

(As expected, I get the same output when I used ".absolute()" instead of ".unique()".)

A frequent work-around for the lack of canonical atom maps is to overload the isotope number. However, issue #273 means that if I rewrite "[C:16]" to "[16C]" then I risk losing the 16.

If the code is meant to work this way, then my alternative  suggestion is to modify the documentation slightly to distinguish between the flavors that may affect the canonicalization ordering and those which only affect the output symbols.

**Comment by johnmay** [comment]
Possible on the Unique flavour but again due to the InChI/Universal SMILES
not possible on absolute ATM.

**Comment by johnmay** [comment]
I actually think the current behaviour is correct - Roger also believed so. It might be a useful option? but I'm trying to find a use case...

We actually had a bug a NextMove due to the RDKit behaviour. OEChem does the same as CDK for `OECreateCanSmiString`.

```
$> cat tmp.smi
[CH3:1][CH3:2]
[CH3:2][CH3:1]
$> oecansmi tmp.smi
[CH3:1][CH3:2] 
[CH3:2][CH3:1] 
```

**Comment by adalke** [comment]
Thanks for the correction. I thought OEChem included the atom classes in the canonicalization, just like RDKit does. Upon close reading, the documentation even says it doesn't: "Controls whether atom map indices are written to the generated SMILES string".

The real-world cases I can think of can all be recast to use isotopes for the label rather than atom classes, so it's not essential. I do think it's odd that labeling my cut positions as "[1*]", "[2*]", and "[3*]" and asking for a canonical SMILES will give me a canonical SMILES, while using "[*:1]", etc. will not. I'm surprised to hear you all think it's the correct behavior. 

The case I was thinking of was the Jameed Hussain MMP algorithm contributed to the RDKit. However, it was written before RDKit supported atom classes, so it uses [1*], etc. for the canonicalization step, not [*:1], etc. It does a post-canonicalization syntactical rewrite from 1* to *:1. In 2015 I spent some time optimizing this algorithm for a client. One of the things I did was to set the atom class directly, so that RDKit would produce the canonical SMILES without a rewrite step. This also meant that the resulting SMILES was canonical, rather than transform-into-isotope-labels canonical.

However, the underlying algorithm is the same. Working with isotopes and translating is like working in imperial units instead of metric; a bit tedious, but that's all.

Double however, Hussain's MMP code doesn't always give canonical output, because the initial cut assignment was arbitrary. It needed a post-processing step to match possible symmetries correctly, and the final result still wasn't canonical; it could have up to n! representations for a rule, where n is the number of cuts. This required some additional processing to use effectively. What makes is a 'double however' is that I developed an improved algorithm for a client which solves this problem by getting rid of the atom labels entirely.

As a variation, consider if you have a SMARTS used to find the core and identify bonds to cut, where the bonds are replaced with -[*:1], -[*:2], -[*:3]. If you canonicalize after cutting then you'll have 4 dot-disconnected components. The core term is trivially identified as the only one having 3 ":" characters in it.

Suppose also that the core is symmetric, such that the SMARTS could match twice and assign either -[*:1] and -[*:2] or vice versa to a given pair of atoms, arbitrarily. If the atom maps aren't used in the canonicalization then the resulting SMILES for the core will sometimes have :1 before :2 and sometimes the other way. It wouldn't be canonical even if you asked for it to be canonical.

There are ways to resolve it. The simplest is to use -[1*] and -[2*] as the labels so the resulting canonical SMILES string would really be canonical.

This example is a bit of a red herring as it's not chemically driven. I give it as a more concrete example to show my confusion about why you think the existing non-canonical output behavior is what you want.

**Comment by johnmay** [comment]
Hmm interesting, It is somewhat complicated by the atom class/map on molecules. Originally these were only for reactions - correct? I tend to think of the atom-atom mapping is a derived property (although in truth there is normally one correct mapping). Should another derived property like coordinates affect canonicalisation order? I think most people would agree probably not.

I can see your use case and never liked the common isotope hack... I think ultimately I am going to make this an option as it's also useful for markush attachment points:

![image](https://cdkdepict-openchem.rhcloud.com/depict/bow/svg?smi=*c1cc(*)cc(*)c1%20%7C%24_AP1%3B%3B%3B%3B_AP2%3B%3B%3B_AP3%3B%24%7C&w=80&h=50&abbr=on&suppressh=true&showtitle=false&zoom=1.3&annotate=none)

I think the bug we actually had at NextMove was RDKit used to consider the atom maps even when they weren't written...

```
Input:
[*:1]c1cc(C)c([*:2])cc1
[*:2]c1cc(C)c([*:1])cc1
Output:
*c1cc(C)c(*)cc1
Cc1cc(*)ccc1*
```
