### ISSUE TITLE
Update the README and project name

### ISSUE THREAD

**Issue by tomas-pluskal** [cdk/cdk#286]
Update the README and project name to point to the new homepage instead of http://cdk.sf.net/ ?

**Comment by johnmay** [comment]
Sure... we can also point cdk.sf.net at the new homepage.

**Comment by egonw** [comment]
Latter is done now.

**Comment by tomas-pluskal** [comment]
<img width="1218" alt="screen shot 2017-03-26 at 18 08 16" src="https://cloud.githubusercontent.com/assets/1796692/24335619/44f001e8-124f-11e7-9c0b-cc3a0f3e437e.png">

**Comment by tomas-pluskal** [comment]
<img width="1260" alt="screen shot 2017-03-26 at 18 09 33" src="https://cloud.githubusercontent.com/assets/1796692/24335625/6aa5d0c0-124f-11e7-9983-2673a9932a48.png">

**Comment by egonw** [comment]
Both updated.
