### ISSUE TITLE
org.openscience.cdk.hash.HashCodeScenariosTest runs into infinite loop?

### ISSUE THREAD

**Issue by egonw** [cdk/cdk#293]
At least, the test is slow now... maybe you should use @SlowTest ;)

@johnmay, I'll explore the cause tomorrow, but I guess you see the problem immediately...

**Comment by johnmay** [comment]
Oh right okay I see the hash test. Yep I'll look into.

**Comment by johnmay** [comment]
Done. Works okay with valid SDfile but missed a condition in the SDfile reader patch

**Comment by egonw** [comment]
Well, that's why we have the unit tests :)
