### ISSUE TITLE
Insufficient chi descriptor patterns?

### ISSUE THREAD

**Issue by philopon** [cdk/cdk#333]
Hi.

Kier & Hall molecular connectivity index definition on this (http://www.esi.umontreal.ca/accelrys/life/cerius46/qsar/theory_descriptors.html#285013) page says:

```
 Given a connected subgraph G:

(i) If G contains a cycle it is of type CH (chain).

Otherwise:

(ii) If all vertex valencies of G (valencies with respect to G, not the entire graph) are either greater than 2 or equal to 1, G is of type C (cluster).

Otherwise:

(iii) If all vertex valencies (as in (ii)) are either equal to 2 or 1, G is of type P (path).

Otherwise:

(iv) G is of type PC (Path/Cluster). 
```

So, I think order6 patterns of [ChiCluster](https://github.com/cdk/cdk/blob/master/descriptor/qsarmolecular/src/main/java/org/openscience/cdk/qsar/descriptors/molecular/ChiClusterDescriptor.java) shouldn't contain "C1(C)C(C)C1(C)" (I think it is order6 chain),
and order6 patterns of [ChiPathCluster](https://github.com/cdk/cdk/blob/master/descriptor/qsarmolecular/src/main/java/org/openscience/cdk/qsar/descriptors/molecular/ChiPathClusterDescriptor.java) should contain "CC(C)(CC)CC". Do I understand correctly?

I'll send PR if my understand is correct.

Thanks.

**Comment by johnmay** [comment]
```(i) If G contains a cycle it is of type CH (chain).```

That sounds wrong but i'm sure it's what is written. A chain is normally considered to be acyclic. 

If it's not a big PR please make it and will be easier to see what's going on via tests etc

**Comment by philopon** [comment]
I agree it's strange that chain means cyclic graph.
However, some references says so.

ref: https://books.google.co.jp/books?id=6Zp7Yrqzv8AC&pg=PA530&lpg=PA530&dq=chain+path+path-cluster+cluster&source=bl&ots=Jo3LDM1HAk&sig=YYhHOFQYXwGYb6Lfq26IEhEgAbk&hl=ja&sa=X&ved=0ahUKEwjh9sb27bfUAhVBN5QKHUQ1CpEQ6AEILzAB#v=onepage&q=chain%20path%20path-cluster%20cluster&f=false

I created 2 PRs. Please check these.
