### ISSUE TITLE
How to compile a small java program using cdk from the command line?

### ISSUE THREAD

**Issue by UnixJunkie** [cdk/cdk#342]
Hello,

    javac Test.java

gives me:

Test.java:5: error: package org.openscience.cdk.io.iterator does not exist
import org.openscience.cdk.io.iterator.IteratingSMILESReader;

I am looking for a simple command line. I would prefer not to have to start a whole project with eclipse/netbeans/...
Adding -cp /usr/share/java/cdk-io.jar doesn't solve the problem.

**Comment by steinbeck** [comment]
Did you add the cdk library jars to your CLASSPATH variable?

Kind regards, 

Chris


--
Prof. Dr. Christoph Steinbeck
Analytical Chemistry - Cheminformatics and Chemometrics
Institute for Inorganic and Analytical Chemistry
Friedrich-Schiller-University
Lessingstr. 8, D-07743 Jena, Germany
Phone Secretariat: +49-3641-948171
Email: christoph.steinbeck@uni-jena.de
http://orcid.org/0000-0001-6966-0814

**Comment by johnmay** [comment]
```
$> javac -cp cdk-2.0.jar Test.java
$> java -cp cdk-2.0.jar:. Test
```

**Comment by UnixJunkie** [comment]
thanks, it compiles further now
