### ISSUE TITLE
.NET port of CDK

### ISSUE THREAD

**Issue by JimSEOW** [cdk/cdk#345]
Anyone here interested to have a .NET port of CDK, [please check this.](https://github.com/kazuyaujihara/NCDK)
It would help the community as a whole if we could help the Author of NCDK to sort out any issues to keep up with the CDK development

**Comment by johnmay** [comment]
Yes, he has submitted patches back the Java. Please post this to the mailing list.

**Comment by JimSEOW** [comment]
@johnmay  Currently I think NCDK is the NON ikvm solution to CDK. 
The community needs to aware to coordinate the contribution

Is there conflict of interest of NCDK to the java community?

**Comment by johnmay** [comment]
> Is there conflict of interest of NCDK to the java community?

No, but I don't understand what you're asking/why here? GitHub issues are for problems with the code, bugs, etc. Not for general discussion. The only people who get this notifications is the core dev team or people who have actively subscribed. We already know about NCDK so you're posting in the wrong place.

As I said before the best place to draw attention to the project is on the mailing lists: cdk-user. NCDK is linked from the main page: http://cdk.github.io

**Comment by JimSEOW** [comment]
@johnmay thanks for the [link](https://kazuyaujihara.github.io/) through the main page http://cdk.github.io
