### ISSUE TITLE
LongestAliphaticChainDescriptor doesn't work

### ISSUE THREAD

**Issue by johnmay** [cdk/cdk#362]
Personal communication from Nichola McCann

> I am relatively new to using the cdk, but I have a question about the descriptor generation. When I calculate the Longest Aliphatic Chain (nAtomLAC) for ethanol, I get different answers, depending on how I enter the molecule. If I use CCO, I get a value of 2, but if I use OCC (the canonical version from cdk), I get 0.
> I have attached below the R code that I used to generate these results – could you please explain the discrepancy?

```java
    @Test
    public void debug() throws ClassNotFoundException, CDKException, java.lang.Exception {
        SmilesParser sp = new SmilesParser(SilentChemObjectBuilder.getInstance());
        IAtomContainer mol1 = sp.parseSmiles("CCO");
        IAtomContainer mol2 = sp.parseSmiles("OCC");
        System.out.println(descriptor.calculate(mol1).getValue());
        System.out.println(descriptor.calculate(mol2).getValue());
    }
```

**Comment by steinbeck** [comment]
The source code for the LongestAliphaticChain descriptor isn’t overly long (attached) and while I currently don’t have time to look at it, as quick inspection shows that it might be one of those beautiful off-by-one bugs :) in the breadth-first-search. Or maybe not.
Enjoy debugging. :)

Cheers, 

Chris

— 
Prof. Dr. Christoph Steinbeck
Analytical Chemistry - Cheminformatics and Chemometrics
Friedrich-Schiller-University Jena, Germany
Phone Secretariat: +49-3641-948171
http://cheminf.uni-jena.de
http://orcid.org/0000-0001-6966-0814

What is man but that lofty spirit - that sense of enterprise.
... Kirk, "I, Mudd," stardate 4513.3..

**Comment by johnmay** [comment]
Here's a correct non-optimal way of doing it but mirrors what is done ATM :-)

```
private boolean isAcyclicCarbon(IAtom atom) {
        return atom.getAtomicNumber() == 6 && !atom.isInRing();
    }
    private int longestAliphaticChain(IAtomContainer mol) {
        IAtomContainer part = mol.getBuilder().newAtomContainer();
        Cycles.markRingAtomsAndBonds(mol); // ensure ring flags are set
        for (IAtom atom : mol.atoms())
            if (isAcyclicCarbon(atom))
                part.addAtom(atom);
        for (IBond bond : mol.bonds())
            if (isAcyclicCarbon(bond.getBegin()) && isAcyclicCarbon(bond.getEnd()))
                part.addBond(bond);
        AllPairsShortestPaths apsp = new AllPairsShortestPaths(part);
        int max = 0;
                  // NxN can be avoided here if apsp 
        for (int beg = 0; beg < part.getAtomCount(); beg++) {
            for (int end = 0; end < part.getAtomCount(); end++) {
                int dist = apsp.from(beg).distanceTo(end);
                if (dist > max) {
                    max = dist;
                }
            }
        }
        return 1+max;
    }
```
