### ISSUE TITLE
Two different SMILES representations of the same molecule give different results when calculating some atom descriptors

### ISSUE THREAD

**Issue by martin-sicho** [cdk/cdk#363]
Hello everyone,

first of all, thanks for developing CDK. It's nice to have a cheminformatics framework available for Java too!

I was calculating some atom descriptors in CDK (v2.0) and I noticed some dodgy results when using different forms of SMILES. For example, this code:

```java
IAtomicDescriptor eatmpol = new EffectiveAtomPolarizabilityDescriptor();

IAtomContainer benzene = parseSMILES("c1ccccc1");
for (IAtom atm : benzene.atoms()) {
    System.out.println(eatmpol.calculate(atm, benzene).getValue().toString());
}

System.out.println();

IAtomContainer benzene_kek = parseSMILES("C1=CC=CC=C1");
for (IAtom atm : benzene_kek.atoms()) {
     System.out.println(eatmpol.calculate(atm, benzene_kek).getValue().toString());
}
```

generates the following output:

```
6.243375000000002
6.243375
6.243375
6.243375
6.243375
6.243375000000002

6.838375000000001
6.838375000000001
6.838375000000001
6.838375000000001
6.838375000000001
6.838375000000001
```

I think there is something wrong with the perception of bond types because the difference between the two representations is that in the first case the double bonds are marked aromatic while in the latter case they are not.

I think the following descriptors might also be affected:

```
PartialSigmaChargeDescriptor
PiElectronegativityDescriptor
SigmaElectronegativityDescriptor
```

Does anyone have an idea what might be happening here? How should I prepare my structures to get consistent results? Thanks!

**Comment by johnmay** [comment]
As a rule of thumb before calculating descriptors you should mark ring atoms and set aromaticity flags. Some descriptors have options to do this for you but it's a lot of wasted effort if you are running multiple descriptors.

```
        IAtomicDescriptor eatmpol = new EffectiveAtomPolarizabilityDescriptor();
        SmilesParser smilesParser = new SmilesParser(SilentChemObjectBuilder.getInstance());

        IAtomContainer benzene = smilesParser.parseSmiles("c1ccccc1");

        Aromaticity aromaticity = new Aromaticity(ElectronDonation.daylight(),
                                                  Cycles.all());
        aromaticity.apply(benzene);
        for (IAtom atm : benzene.atoms()) {
            System.out.println(eatmpol.calculate(atm, benzene).getValue().toString());
        }

        System.out.println();

        IAtomContainer benzene_kek = smilesParser.parseSmiles("C1=CC=CC=C1");
        aromaticity.apply(benzene_kek);
        for (IAtom atm : benzene_kek.atoms()) {
            System.out.println(eatmpol.calculate(atm, benzene_kek).getValue().toString());
        }
```
Result:
```
6.243375000000002
6.243375
6.243375
6.243375
6.243375
6.243375000000002

6.243375000000002
6.243375
6.243375
6.243375
6.243375
6.243375000000002
```

**Comment by martin-sicho** [comment]
Oh, I didn't know you had to do that. Thanks!

By the way, is there a way to accomplish the same thing in CDK 1.4 by any chance? I depend on some legacy software and rewriting all the interfaces would be rather daunting. I looked at the [org.openscience.cdk.aromaticity](https://cdk.github.io/cdk/1.4/docs/api/org/openscience/cdk/aromaticity/package-summary.html) package, but was not able to figure it out...

**Comment by johnmay** [comment]
Maybe... but i would strongly advise against using 1.4 - see recent paper with benchmarks on SMILES reading etc. 

Whilst you can apply aromaticity with [``CDKHueckelAromaticityDetector``](http://cdk.github.io/cdk/1.4/docs/api/index.html?org/openscience/cdk/aromaticity/CDKHueckelAromaticityDetector.html), you will likely need to assign bond order, atom types, and hydrogen counts first. The assigning of bond orders is done automatically in 2.0 but there are some options with [``FixBondOrdersTool``](http://cdk.github.io/cdk/1.4/docs/api/index.html?org/openscience/cdk/smiles/FixBondOrdersTool.html) or [``DeAromatizationTool``](http://cdk.github.io/cdk/1.4/docs/api/index.html?org/openscience/cdk/tools/DeAromatizationTool.html) but neither of these are very good CDK 2.0 does it correctly - (my colleague Noel O'Boyle actually did a recent [talk on this at the ACS about integrating the correct way in to Open Babel](https://baoilleach.blogspot.co.uk/2017/08/my-acs-talk-on-kekulization-and.html)).

Will need to experiment but will be something like this, some operations may be out of order.

```java
IAtomContainer mol = ...;
FixBondOrdersTool.kekuliseAromaticRings(mol);
AtomContainerManipulator.percieveAtomTypesAndConfigureUnsetProperties(mol);
CDKHydrogenAdder.getInstance(mol). addImplicitHydrogens(mol);
CDKHueckelAromaticityDetector.detectAromaticity(mol);
```

**Comment by egonw** [comment]
@martin-sicho, I echo John's comment: it is really worth the effort...

That said, migrating is non-trivial, but a guidance can help a lot... https://github.com/egonw/cdk-migration/blob/master/migration.pdf

**Comment by martin-sicho** [comment]
@johnmay, thanks a lot. I was able to resolve that issue quick and dirty using the hints you provided.

I completely agree that the best solution would be to migrate as soon as possible and it is definitely high on the priority list. It's just time is scarce at the moment.

Thanks, @egonw, for providing the migration guide. It will definitely be useful once I get to it.
