### ISSUE TITLE
Suppress drawing of wiggly bonds in CDK 2.0

### ISSUE THREAD

**Issue by ayedo** [cdk/cdk#369]
First of all I would like to thank you for your awesome work on the CDK!

The issue arises after upgrading from CDK 1.5.10 to 2.0: a molecule is rendered with "wiggly" bonds which was not rendered like that before:

![wiggly_lines](https://user-images.githubusercontent.com/4739734/30532390-63da8670-9c54-11e7-8087-58508295cc53.png)

I guess it might have something to do with StereoElements, since the wiggly bonds may represent unknown stereo chemistry? 

I've tried resetting the StereoElements like so:
`molecule.setStereoElements(new ArrayList<>());`

Unfortunately, this did not resolve my problem.

Is there a way I can suppress this novel behaviour?

**Comment by johnmay** [comment]
The wiggly bonds indicate undefined double bond stereochemistry (in the style preferred by [IUPAC](https://www.iupac.org/publications/pac/2006/pdf/7810x1897.pdf)). The alternative is a crossed double bond which we can also do.

If you remove the wiggly bonds the depiction is not correct as you have accidentally indicated double bond cis/trans configuration where there is none. This results in error propagation between tools and databases - are you sure you really want to remove them?

**Comment by johnmay** [comment]
Two options:

a) Preferred - ensure the stereochemistry is defined around those double bonds in the input or artificially add it in (this will be slightly easier in future), the list should not be empty:
```java
molecule.setStereoElements(functionToDefineDoubleBonds(mol));
```
b) **Discouraged** - generate a 2D layout with ``StructureDiagramGenerator`` then go through the bonds and wipe and display information (called 'Stereo' in CDK's world).
```java
for (IBond bond : mol.bonds()) {
  switch (bond.getStereo()) {
    case UP_OR_DOWN:
    case UP_OR_DOWN_INVERTED:
    case E_OR_Z:
      bond.setStereo(IBond.Stereo.NONE);
      break;
  }
}
```

**Comment by ayedo** [comment]
I could resolve my problem with your help! Thank you very much for your quick and elaborate answer.
