### ISSUE TITLE
MDLV2000Writer writes radical information incorrectly

### ISSUE THREAD

**Issue by galgonek** [cdk/cdk#371]
Dear all,

My colleague @exaexa discovered that MDLV2000Writer writes radical information incorrectly if there is more than nine radical values. We prepare the [MDLV2000Writer-patch.txt](https://github.com/cdk/cdk/files/1343531/MDLV2000Writer-patch.txt) patch that solves the issue.

Best regards,
Jakub Galgonek

**Comment by johnmay** [comment]
Any chance you can add this is a pull request?

**Comment by exaexa** [comment]
👍
