### ISSUE TITLE
Problem with Inchi generator

### ISSUE THREAD

**Issue by flmon** [cdk/cdk#375]
When we parse a SDF file to build a structure and next calculate inchi, the inchi generator fails when the sdf file contains bond description aromatic (bond block with bond type 4)
The error message is : org.openscience.cdk.exception.CDKException: Failed to generate InChI: Unsupported bond type

**Comment by johnmay** [comment]
Bond order 4 (see [CTfile formats](http://accelrys.com/products/collaborative-science/biovia-draw/ctfile-no-fee.html)) is a query feature in molecules and you can not compute InChIs for that as you can not computer InChIs for things with pseudo atoms ``*CO``. 

However if you really want to do this there is an option to allow the InChI (see [setIgnoreAromaticBonds](http://cdk.github.io/cdk/2.0/docs/api/index.html?org/openscience/cdk/inchi/InChIGeneratorFactory.html))

**Comment by johnmay** [comment]
Just add to that, the bond order 4 causes problems because the number of hydrogens can not be specified. For example in SMILES we can differentiate between a pyrrole-like and pyridine-like nitrogen with the hydrogens being specified.

n1ccccc1 pyridine
[nH]1cccc1 pyrrole

Which toolkit did you use to produce the SDF?

**Comment by flmon** [comment]
I didn't generate the sdf; I received it from a supplier and started to parse with CDK until I noted that Inchi fails. I don't know which tool they used to build it.

**Comment by johnmay** [comment]
It tells you in the header of the file. Anyways doesn't matter, SDFiles bond order 4 can not be portably used to exchange chemical information.
