### ISSUE TITLE
Match results when doing substructure search

### ISSUE THREAD

**Issue by flmon** [cdk/cdk#376]
When doing substructure search, I got sometimes incorrect results.
For example, I tried to look if I can find just C-F substructure in the following molecule: FC=1C(F)=C2C(=C(F)C1S)C(F)(F)C(F)(F)C2(F)F

Obviously there are 9 match cases and indeed we can find 9 match cases but the method  UniversalIsomorphismTester:: getSubgraphAtomsMaps returns a list of 9 empty RMap.

**Comment by johnmay** [comment]
The UniversalIsomorphismTester should not be used, please use the newer and faster APIs:

[Pattern](https://cdk.github.io/cdk/2.0/docs/api/index.html?org/openscience/cdk/isomorphism/Pattern.htmll) or [SmartsPattern](http://cdk.github.io/cdk/2.0/docs/api/index.html?org/openscience/cdk/smiles/smarts/SmartsPattern.html)

```java
Pattern ptrn = SmartsPattern.create("[#6]-F");
for (int[] mapping : ptrn.matchAll(mol)) {
   mol.getAtom(mapping[0]); // C
   mol.getAtom(mapping[1]); // F
}
```
