### ISSUE TITLE
StructureDiagramGenerator ignores setBondLength for ring bonds

### ISSUE THREAD

**Issue by bw800402** [cdk/cdk#384]
Setting bond length for StructureDiagramGenerator  has no affect on the bond length of ring bonds.  A minimal demonstration:

SmilesParser   sp  = new SmilesParser(SilentChemObjectBuilder.getInstance());
IAtomContainer m   = null;
m   = sp.parseSmiles("CCCCCC1CCCCC1");
StructureDiagramGenerator sdg =	new StructureDiagramGenerator();
sdg.setBondLength(28);		
sdg.setMolecule(m);
sdg.generateCoordinates();
ByteArrayOutputStream baos = new ByteArrayOutputStream();
MDLV2000Writer writer = new MDLV2000Writer(
	baos
	);
writer.write((IAtomContainer)sdg.getMolecule());
System.out.println(new String(baos.toByteArray()));
writer.close();

This results in a molecule with very long acyclic bonds and tiny (relatively) ring bonds.

**Comment by johnmay** [comment]
I'll deprecate that method, the correct way to do this is layout the molecule then scale it.

**Comment by bw800402** [comment]
It might be useful to have the method work using the set bond length in a
scenario in which you have coordinates for most of the molecule and need to
get coordinates for atoms you added while converting super atom
representations to their expanded representation e.g. OBn to OCc1ccccc1.
Just my two cents.

Ben

**Comment by johnmay** [comment]
Possible - but abbreviations are best implemented as display shortcuts, the entire structure is laid out but the abbreviations is tagged to simply hide the contracted parts. ChemAxon have this idea that you can contract and expand the physical connection table but if this isn't really how it works in the MDL and ChemDraw formats.

More here:
http://efficientbits.blogspot.co.uk/2015/11/bringing-molfile-sgroups-to-cdk.html
