### ISSUE TITLE
Stereocenters.of causes NullPointerException for some ChEBI molecules

### ISSUE THREAD

**Issue by galgonek** [cdk/cdk#389]
Method `Stereocenters.of` causes `NullPointerException` for some ChEBI molecules (e.g., CHEBI:2762). To reproduce the issue, you can use the following code:

```import java.net.URL;
import org.openscience.cdk.io.MDLV2000Reader;
import org.openscience.cdk.silent.AtomContainer;
import org.openscience.cdk.stereo.Stereocenters;

public class Test
{
    public static void main(String[] args) throws Exception
    {
        URL url = new URL("http://www.ebi.ac.uk/chebi/saveStructure.do?" +
                "sdf=true&chebiId=2762");
        MDLV2000Reader reader = new MDLV2000Reader(url.openStream());
        AtomContainer molecule = reader.read(new AtomContainer());
        Stereocenters.of(molecule);
    }
}
```

**Comment by johnmay** [comment]
Hmm, odd - the Stereocentres.of is called already inside the MDLV2000Reader.

**Comment by galgonek** [comment]
Are you sure? I load all ChEBI compounds and none of them calls `Stereocentres.of` inside `MDLV2000Reader`.

**Comment by johnmay** [comment]
The molfile contains query bonds (bond order 4, aromatic) and you cannot assign unambiguous hydrogen counts (see MDL valence model etc) in all cases. Note this is a 2-star non-curated entry and should probably be avoided.

For most code in the CDK, it is an invariant that the hydrogen counts are defined. I can add an extra check here to throw an IllegalArugmentException but the issue is really the molecule input is a duff.

**Comment by galgonek** [comment]
The same issue occurs also for CHEBI:5015 that has the 3-star status.

**Comment by galgonek** [comment]
Note: It seems that the ChEBI website cannot generate big images for compounds that have this issue. You can see it, for example, at https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:5015.

**Comment by johnmay** [comment]
A good check after you read in a molecule is to check the hydrogen counts are non-null. 

Example: 
https://github.com/cdk/cdk-paper-3/blob/master/benchmark/cdk-2.0/src/main/java/org/openscience/cdk/CliExecutable.java#L191-L205

**Comment by galgonek** [comment]
I think that it should be possible to detect stereocenters for parts of a compound that have unambiguous hydrogen counts.

**Comment by johnmay** [comment]
The stereocentres should already be detected?

```
URL url = new URL("http://www.ebi.ac.uk/chebi/saveStructure.do?sdf=true&chebiId=2762");
MDLV2000Reader reader   = new MDLV2000Reader(url.openStream());
AtomContainer  molecule = reader.read(new AtomContainer());
for (IStereoElement se : molecule.stereoElements()) {
    System.out.println(se.getClass());
}
```

**Comment by johnmay** [comment]
If you still want to run through there Stereocentres code put in some token values:
```
for (IAtom atom : molecule.atoms())
            if (atom.getImplicitHydrogenCount() == null)
                atom.setImplicitHydrogenCount(0);
```
Removing the NPE will still cause a failure further down in the symmetry checking.
