### ISSUE TITLE
image hosting gone bad in the README

### ISSUE THREAD

**Issue by egonw** [cdk/cdk#391]
![image](https://user-images.githubusercontent.com/26721/33523567-d91522be-d80a-11e7-9ea5-39a81f9f8810.png)

**Comment by johnmay** [comment]
Where is that? Only one I can find is on RingSearch:

find 2.0/ -type f -exec grep -F photobucket {} \;
 fused cycle systems" src="http://i56.photobucket.com/albums/g187/johnymay/isolated-and-fused-cycles-01_zpse0311377.png">

**Comment by johnmay** [comment]
Ah right found it...

**Comment by egonw** [comment]
Oh, sorry... forgot to mention it was in the README.md ... :(

**Comment by johnmay** [comment]
Resolved
