### ISSUE TITLE
Atoms may be invisible depending on background

### ISSUE THREAD

**Issue by stefhk3** [cdk/cdk#425]
In the RendererModel it is possible to set the background color. If this background color happens to be the same as an element color the respective elements become invisible. Ideally if the element color is the same as the background color there should be a frame round the element or so. Of course if the color is slightly off this might still be a problem and ideally some "color similarity" measure would be needed.

**Comment by stefhk3** [comment]
Related: In CDK2DAtomColors hydrogen is still defined as black, it seems. This was done, I think, to make it visible on while background. With a general solution this could go away and hydrogen be made white.

**Comment by johnmay** [comment]
It's a parameter of the [BasicSceneGenerator.BackgroundColor](http://cdk.github.io/cdk/2.1/docs/api/index.html?org/openscience/cdk/renderer/generators/BasicSceneGenerator.BackgroundColor.html), but shouldn't really be using the RenderModel API directly...

```java
DepictionGenerator dg = new DepictionGenerator();
dg = dg.withBackgroundColor(Color.GRAY)
       .withAtomColors(new CDK2DAtomColors());
dg.depict(mol)
  .writeTo("~/mol.svg"); // png, pdf, etc
```

**Comment by johnmay** [comment]
and to answer your other question yes there is a general solution this:

```java
```

**Comment by johnmay** [comment]
Sorry actually read the question now, long day. Anyways the point is all things are possible, you can put backgrounds on atoms with an outer glow, but having worked a lot on the depiction code the best solution is not choose conflicting colors:

Neon on Black for Example:
 ![](http://simolecule.com/cdkdepict/depict/nob/svg?smi=CN1C=NC2=C1C(=O)N(C(=O)N2C)C%20caffeine&abbr=on&hdisp=bridgehead&showtitle=false&zoom=1.6&annotate=none)

**Comment by stefhk3** [comment]
Well, I am sure it can be done. On the other hand does the user expect he has to make sure there is no such problem (by choosing non-conflicting colours or some other trick)? Is it documented? It would be much nicer if it would work automatically, I believe. And I still find it inconsistent that the "white hydrogen on white background" case is dealt with, but not very well.

**Comment by johnmay** [comment]
https://github.com/cdk/cdk/wiki/Standard-Generator
