### ISSUE TITLE
Current CIF reader fails to read uni cell parameters and overreads atoms

### ISSUE THREAD

**Issue by sauliusg** [cdk/cdk#426]
The current CIFReader reads unit cell constants incorrectly (returns all zeros) and overreads the _atom_site loop, yielding incorrect atoms and eventually a NullPointerException.

How to reproduce:
- compile cdkcifrd.java from the attached cdkcifrd.zip;
[cdkcifrd.zip](https://github.com/cdk/cdk/files/1767473/cdkcifrd.zip)
- read a CIF from the COD (http://crystallography.net/cod/1502693.cif); a copy is provided.
On Ubuntu-16.04 under bash the following commands demonstrate the issue (assuming the cdk clone is build in ../cdk):
```
saulius@koala smiles-scripts/ $ javac -cp ../cdk/bundle/target/cdk-2.2-SNAPSHOT.jar cdkcifrd.java
```
- with standard latest CDK snapshot, cell parameters are all 0.0, there are too many atoms reported and the code triggers assertion for null pointer:
```
saulius@koala smiles-scripts/ $ java -ea -cp ../cdk/bundle/target/cdk-2.2-SNAPSHOT.jar:. cdkcifrd tests/inputs/1502693.cif | head
269
tests/inputs/1502693.cif; CELL = (0.0, 0.0, 0.0) (0.0, 0.0, 0.0) (0.0, 0.0, 0.0)
Exception in thread "main" java.lang.AssertionError: f is null at atom No 87
	at cdkcifrd.computeOrthogonalCoordinates(cdkcifrd.java:101)
	at cdkcifrd.main(cdkcifrd.java:70)
```
- with a patched code (will offer a PR shortly) the file is read correctly:
```
saulius@koala smiles-scripts/ $ java -ea -cp jars/cdk-2.2-SNAPSHOT.jar:. cdkcifrd tests/inputs/1502693.cif | head
86
tests/inputs/1502693.cif; CELL = (21.33, 0.0, 0.0) (4.759283623186401E-16, 7.7725, 0.0) (-4.2317488823956815, 1.6591361069663173E-15, 22.4689741064505)
C     16.6686    8.77671   -3.86916
C     17.0263    9.47468   -5.15663
H     17.6069    8.89563   -5.69139
H     17.4937    10.3110   -4.95441
H     16.2077    9.67132   -5.65769
C     17.6021    5.62729   -2.16601
C     18.5319    4.51038   -2.52776
H     19.2362    4.84926   -3.11869
```

**Comment by johnmay** [comment]
Don't need to an open an issue if you give a PR, but thanks

**Comment by sauliusg** [comment]
OK, will know in the future :)
