### ISSUE TITLE
Private Constructor InChiGeneratorFactory() does not exist ...

### ISSUE THREAD

**Issue by steinbeck** [cdk/cdk#431]
... but is called by public static InChIGeneratorFactory getInstance(). Which of course causes a compile error.
Weirdly, that only popped up when I used the getInstanceMethod() in my code which forced Eclipse to compile the module. It does not appear when doing a mvn install of CDK, so presumably this code is neither build nor tested?!

**Comment by johnmay** [comment]
No it builds fine, something else is going on...

**Comment by johnmay** [comment]
What's the precise stack trace you get? The only way I could see this happening is if you on an operating system not supported by the InChI code.

**Comment by johnmay** [comment]
Here is the private constructor (it exists): https://github.com/cdk/cdk/blob/master/storage/inchi/src/main/java/org/openscience/cdk/inchi/InChIGeneratorFactory.java#L83-L89

**Comment by steinbeck** [comment]
I have no idea what happened here. Did a fresh checkout and indeed the empty contructor was there. But then again I have not touch the code of this class at all and got the build error that the empty constructor was missing. Never mind - case closed
