### ISSUE TITLE
CDK unique smiles flavour generates identical smiles for some non-identical cyclobutadiens

### ISSUE THREAD

**Issue by steinbeck** [cdk/cdk#432]
I was looking at whether RandomGenerator covers all of constitutional isomer space that it is supposed to do (it seems to do) and used CDK unique smiles as a hash. In this test code, RandomGenerator found only 4308 of the 4315 compounds that Molgen (http://www.molgen.de/literature.html) predicted. 

Turned out that the reason was that the CDK unique smiles implementation generates identical ‘unique’ smiles for non-identical molecules. They are all mesomeric cyclobutadiens. See attached graphics and SDF file.

Both RDKIT and Openbabel generate the right number 4315 non-identical unique smiles. 

<img width="1223" alt="pastedgraphic-1" src="https://user-images.githubusercontent.com/107318/37146822-29ac3348-22c5-11e8-8c5d-2a3575b50ce2.png">
[C10H16-isomers-with-degenerate-smiles.sdf.zip](https://github.com/cdk/cdk/files/1792790/C10H16-isomers-with-degenerate-smiles.sdf.zip)

**Comment by johnmay** [comment]
See mailing list, as per IUPAC InChI all double bonds in rings are allowed to move even if they would normally be considered anti-aromatic.
