### ISSUE TITLE
Javadoc for IsotopeFactory.getMajorIsotope(int) doesn't match implementation

### ISSUE THREAD

**Issue by rajarshi** [cdk/cdk#445]
The Javadocs for `IsotopeFactory` give the definition of major isotope as

> Returns the most abundant (major) isotope with a given atomic number.
The isotope's abundance is for atoms with atomic number 60 and smaller defined as a number that is proportional to the 100 of the most abundant isotope. For atoms with higher atomic numbers, the abundance is defined as a percentage.

However looking at the [implementation ](https://github.com/cdk/cdk/blob/cef1fff58cdc5f0bf084322b3d4c4616182acf95/base/core/src/main/java/org/openscience/cdk/config/IsotopeFactory.java#L193-L214) it appears that the distinction between elements with atomic number > or < 60 is not made, and major isotope is simply the most abundant isotope.

Should the Javadocs be updated? Or am I missing something?

**Comment by johnmay** [comment]
updated I think

**Comment by johnmay** [comment]
Resolved https://github.com/cdk/cdk/commit/72bec9185eac7fca1709d4eaa537b216e2efcb95
