### ISSUE TITLE
InChIGeneratorFactory.getInChIToStructure ignores deuterium atoms

### ISSUE THREAD

**Issue by meier-rene** [cdk/cdk#449]
I try to create a String with a molecular formula of a molecule from a InChI String. The InChI contains some deuterium atoms which are somehow ignored in the conversion process. As far as I can find out, the deuterium don't make it into the IAtomContainer. Example code is given below:

```
String inchi = "InChI=1S/C22H32O2/c1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16-17-18-19-20-21-22(23)24/h3-4,6-7,9-10,12-13,15-16,18-19H,2,5,8,11,14,17,20-21H2,1H3,(H,23,24)/b4-3-,7-6-,10-9-,13-12-,16-15-,19-18-/i1D3,2D2";
InChIToStructure intostruct = InChIGeneratorFactory.getInstance().getInChIToStructure(inchi, DefaultChemObjectBuilder.getInstance());
INCHI_RET ret = intostruct.getReturnStatus();
if (ret == INCHI_RET.WARNING) {
	// Structure generated, but with warning message
	System.out.println("InChI warning: " + intostruct.getMessage());
}
else if (ret != INCHI_RET.OKAY) {
	// Structure generation failed
	System.out.println("Can not parse INCHI string. Structure generation failed: " + ret.toString() + " [" + intostruct.getMessage() + "]");
	System.exit(0); 
}
IAtomContainer m = intostruct.getAtomContainer();
String formula_inchi = MolecularFormulaManipulator.getString(MolecularFormulaManipulator.getMolecularFormula(m));
System.out.println(formula_inchi);
```
The expected output would be either of `C22H32O2` or `C22H27D5O2` or `C22H27[2H]5O2`but it is `C22H27O2`. 

The compound can be seen here: https://pubchem.ncbi.nlm.nih.gov/compound/24778483#section=Top

Any suggestions?

**Comment by johnmay** [comment]
You shouldn't be reading InChI, it's an identifier not a representation.

John

**Comment by johnmay** [comment]
I will fix this though, the problem is InChI stores implicit H/D/T, CDK only stores implicit H so we need to "promote" the D/Ts to real atoms.

**Comment by meier-rene** [comment]
Thank you for pointing me to the right place in code and providing an initial piece of code to fix this issue. But there is a little mistake in your code:  There might be more than one D/T per carbon. Please pull #451 to correct this.
Rene
