### ISSUE TITLE
Hardcoded use of java.awt.Color

### ISSUE THREAD

**Issue by Krzmbrzl** [cdk/cdk#463]
A few classes inside `org.openscience.cdk.renderer.elements` are using `java.awt.Color` objects in order to represent their color.

This does become an issue if one is working outside of AWT (SWT for example). Therefore I'd suggest the introduction of a custom `Color` class that can be used to represent colors independently from the used toolkit.
One could the supply a new interface `IColorFactory<T>` that transforms the internal color representation into the actual color object as used by the respective toolkit. As a default one could also include an `AWTColorFactory` that implements `IColorFactory<java.awt.Color>` and can be used in all places the `java.awt.Color` object is currently used directly.

If one considers the constant creating of new color objects one could think about buffering the created object. That would best fit inside the `AWTColorFactory` as a `Map<Color,java.awt.color>` (where `Color` is the internal color representation).

**Comment by Krzmbrzl** [comment]
In fact there are quite few uses of `java.awt.Color` throughout the CDK:
https://github.com/cdk/cdk/search?q=%22java.awt.Color%22&unscoped_q=%22java.awt.Color%22

**Comment by johnmay** [comment]
Really don't like this, I really hate the number of "types" we already have, adding more and factories too is just bonkers if you ask me.

> This does become an issue if one is working outside of AWT (SWT for example).

Why does it not exist or do you need to convert to.

If you need a portable color class, why not just use an integer?

int red = 0xff0000;

**Comment by Krzmbrzl** [comment]
> Why does it not exist or do you need to convert to.
I am currently implementing an `IDrawListener` for SWT. And for example the `LineElement` specifies its color as a `java.awt.Color` object which I can't use with SWT. Therefore I have to transform it respectively.

And I can't use an integer or something like this as SWT requires `org.eclipse.swt.graphics.Color` objects.

I mean I can simply write the whole conversion-logic for my application on my own but I thought it would bring the CDK a step closer to being independent from any specific rendering toolkit...

**Comment by egonw** [comment]
I have to look up the details, but with CDK 1.5.13 we have it work well together with a SWT stack...

I'll try to dig up the source code... but should be somewhere here: https://github.com/bioclipse/bioclipse.cheminformatics

cc @goglepox

**Comment by Krzmbrzl** [comment]
Thanks for that!

From what I see there's still a conversion happening whenever the color has to be passed to SWT though...

**Comment by johnmay** [comment]
So works fine without the need to add new classes? I understand trying to modularise and decouple code but it needs a delicate touch. I'm not completely against an abstract "Color" type in the rendering stack (RGB integer hexcodes being the best option there) but it will break backwards compatibility with all existing code which is non-starter for me. I'm strongly opposed to bloat such as "IColorFactory" etc.

**Comment by Krzmbrzl** [comment]
As I said before: It does work if one implements the whole conversion-stuff locally for each individual project.

And as far as backwards compatibility is concerned I think it is manageable: If we simply introduce a new abstract class and change the current classes to implementations of said class, taking care of all conversions to `java.awt.Color` objects then none of the currently existing API needs to be changed.

**Comment by johnmay** [comment]
Please let me know if not resolved
