### ISSUE TITLE
Wrong image when rendering nicotine from SMILES.

### ISSUE THREAD

**Issue by islean** [cdk/cdk#473]
Hi!

When rendering nicotine (SMILES: CN1CCC[C@H]1c2cccnc2) it renders an image with the "@"-bond between two carbons:
![mymolecule](https://user-images.githubusercontent.com/40887124/42372086-99b8f7d4-8111-11e8-99a7-db3ba9cfc9d4.png)

Instead of between the carbon and the hydrogen as it should.

I've tried verifying that it just isn't my code but CDK Depict( http://www.simolecule.com/cdkdepict/depict.html) also gives the same image.

**Comment by islean** [comment]
Aaa okay, thanks! So I have to modify the SMILES manually in order for my code to work? That is, if I'm not using the web depictor?

**Comment by islean** [comment]
And I am having trouble making it work by changing the SMILES. It seems that not having the hydrogen inside the brackets makes the depictiongenerator assume that the there is a stereobond to the next carbon as well?

**Comment by johnmay** [comment]
Take a look at the code in the depictor, specifcally:

https://github.com/cdk/depict/blob/master/src/main/java/org/openscience/cdk/app/DepictController.java#L505-L548

**Comment by islean** [comment]
I see, nice code! Thank you
