### ISSUE TITLE
BasicValidator.ValidateIsotopeExistence(IIsotope isotope) when isotope.mass is null

### ISSUE THREAD

**Issue by kazuyaujihara** [cdk/cdk#477]
This post is transferred from the post on <https://github.com/kazuyaujihara/NCDK/issues/10>.
I don't know what is the proper behavior of  org.openscience.cdk.validate.BasicValidator.ValidateIsotopeExistence(IIsotope isotope) method when isotope.getMassNumber() is null or 0. 
I guess report.addWarning(isotopeExists) is better than addError. 

Do you have any idea?

**Comment by johnmay** [comment]
Closed via #489
