### ISSUE TITLE
Error when parsing InChIs of molecules containing the substructure R-N-C=O

### ISSUE THREAD

**Issue by kaibioinfo** [cdk/cdk#483]
Hi,
I observed a strange bug in the way CDK (and many other toolkits like RDkit or OpenBabel) parse molecules containing the substructure R-N-C=O. In many cases, the substructure is changed to R-N=C-OH when parsing the molecule. I ASSUME it is a bug in the InChI library, but maybe someone can confirm this before posting a bug report to the InChI mailing list.

Small example: InChI=1S/C4H9NO/c1-3-4(6)5-2/h3H2,1-2H3,(H,5,6)

When I parse this molecule in CDK and check for the SMARTS string "C=O" I get no hit. Instead, the SMARTS "N=C-[OH]" is matching.

This is what CDK outputs for InChI=1S/C4H9NO/c1-3-4(6)5-2/h3H2,1-2H3,(H,5,6)

![a](https://user-images.githubusercontent.com/1015048/46805841-6b93b280-cd66-11e8-8325-84ce5a2c9404.png)

This is, what I would expect as output:

![b](https://user-images.githubusercontent.com/1015048/46805872-7cdcbf00-cd66-11e8-9612-fe2353589b87.png)

There are also examples where the substructure is changing depending on the stereochemistry:

When I parse this InChI I get this (correct) molecule back:
InChI=1S/C20H33NO3/c1-4-6-8-9-11-12-16(3)14-17(22)15-19-21-20(23)18(24-19)13-10-7-5-2/h14-15,18H,4-13H2,1-3H3,(H,21,23)/b16-14+,19-15+

![3](https://user-images.githubusercontent.com/1015048/46806088-fecce800-cd66-11e8-8c83-9ce58d113042.png)

If I remove the last stereochemistry layer, connectivity is changing and i get the wrong molecule
InChI=1S/C20H33NO3/c1-4-6-8-9-11-12-16(3)14-17(22)15-19-21-20(23)18(24-19)13-10-7-5-2/h14-15,18H,4-13H2,1-3H3,(H,21,23)

![4](https://user-images.githubusercontent.com/1015048/46806410-d396c880-cd67-11e8-924d-651b00eeefb0.png)
 

This error is quite common: In my dataset 33% of all nitrogen containing molecules are parsed incorrect. It is somewhat critical for all tools working with InChIs (like in my case, CSI:FingerID, but I observed the same error for tools like CFM-ID). 

Here are a few other examples, all parsed wrongly in CDK:
InChI=1S/C2H6N4O/c3-1(4)6-2(5)7/h(H6,3,4,5,6,7)
InChI=1S/C6H13NO/c1-6(2,3)5(8)7-4/h1-4H3,(H,7,8)
InChI=1S/C6H11NO/c8-6-4-2-1-3-5-7-6/h1-5H2,(H,7,8)
InChI=1S/C7H7NO/c8-7(9)6-4-2-1-3-5-6/h1-5H,(H2,8,9)
InChI=1S/C4H8ClNO/c1-4(7)6-3-2-5/h2-3H2,1H3,(H,6,7)
InChI=1S/C7H7NO/c8-7(9)6-4-2-1-3-5-6/h1-5H,(H2,8,9)
InChI=1S/C5H5N3O/c6-5(9)4-3-7-1-2-8-4/h1-3H,(H2,6,9)
InChI=1S/C3H6N2O2/c4-2-1-7-5-3(2)6/h2H,1,4H2,(H,5,6)
InChI=1S/C6H6N2O/c7-6(9)5-3-1-2-4-8-5/h1-4H,(H2,7,9)
InChI=1S/C7H13NO/c9-7-5-3-1-2-4-6-8-7/h1-6H2,(H,8,9)
InChI=1S/C3H5NO3/c4-2(5)1-3(6)7/h1H2,(H2,4,5)(H,6,7)
InChI=1S/C6H6N2O/c7-6(9)5-2-1-3-8-4-5/h1-4H,(H2,7,9)
InChI=1S/C6H6N2O/c7-6(9)5-2-1-3-8-4-5/h1-4H,(H2,7,9)
InChI=1S/C3H6N2O2/c4-2(6)1-3(5)7/h1H2,(H2,4,6)(H2,5,7)
InChI=1S/C5H9NO3/c1-4(7)6-3-5(8)9-2/h3H2,1-2H3,(H,6,7)
InChI=1S/C3H5NO3/c5-2-4-1-3(6)7/h2H,1H2,(H,4,5)(H,6,7)
InChI=1S/C4H7N3O/c1-7-2-3(8)6-4(7)5/h2H2,1H3,(H2,5,6,8)
InChI=1S/C4H6N2O2/c1-6-2-3(7)5-4(6)8/h2H2,1H3,(H,5,7,8)
InChI=1S/C7H15NO/c1-3-5-6-8-7(9)4-2/h3-6H2,1-2H3,(H,8,9)
InChI=1S/C4H6N2O2/c7-3-1-2-5-4(8)6-3/h1-2H2,(H2,5,6,7,8)
InChI=1S/C5H10N2O2S/c1-4(10-3)7-9-5(8)6-2/h1-3H3,(H,6,8)

Currently, I add a postprocessing routine after parsing the InChI that corrects this error. But as it effects a wide range of different other tools, it would be nice to fix this error instead of adding such a workaround.

Can somebody confirm that this is an error of the InChI library and not of the CDK?

**Comment by kaibioinfo** [comment]
okay, i can confirm that this is a problem of the InChI library:

Input: N-Methylpropanamide from https://pubchem.ncbi.nlm.nih.gov/compound/14470
[input.sdf.zip](https://github.com/cdk/cdk/files/2469125/input.sdf.zip)

./inchi-1 -InChI2Struct input.sdf inchi.txt
./inchi-1 -OutputSDF inchi.txt output.sdf

The resulting sdf file differs in connectivity from the input sdf file.

**Comment by meier-rene** [comment]
Just a comment: To my understanding its not a problem, but a feature of InChI. Please have a look at the [https://www.inchi-trust.org/technical-faq/#6.1](InChI faq). In case of tautomeric structures you need to assign the positions of the hydrogen.

**Comment by egonw** [comment]
Yes, this is a feature of the Standard InChI: it does not store the locations of all double bonds, when the double bond is involved in movable hydrogens (following the InChI heuristics). Therefore, parsing a Standard InChI into a chemical structure gives you some information, but not the locations of the hydrogens. This has to be established afterwards. Parsers in the CDK read in as closely as possible as what is described in the file or format and not make assumptions, which the CDK user can (and should) do explicitly later.

**Comment by johnmay** [comment]
InChI is an identifier not a representation, the original authors say it was a mistake to allow it to be read in. Unfortunately their hand was forced. Running them through a canonical tautomer  function should fix them. for CDK there is a prototype on a branch somewhere, maybe i’ll Patch that in for the next realese

**Comment by kaibioinfo** [comment]
I was afraid that it could be something like this. Many tools use the InChI as representation (because for us non-cheminformatics this seemed to be a very smart solution) and fall into this trap.

It would be good if there is some warning in the InChIToStructure class. This "bug/feature" effects A LOT of molecules, so its not a rare exception. If InChI is not a good way to store molecules (but just an identifier for them) then this should be noted somewhere.

A canonical tautomer function would be nice of course.

**Comment by kaibioinfo** [comment]
Short Question: What would be the preferred way to store molecules? I assume MDL/MOL/SDF is the most comprehensive format, but it is also quite large (in particular if we do not care about 2D coordinates). Is SMILES a good alternative, or are there some strange traps in SMILES, too? Is a tripple of (InChI-Key, InChI, SMILES) a proper way to store molecules in a database without having all these trouble with tautomeres, strange charge states or anything else?

**Comment by johnmay** [comment]
> then this should be noted somewhere.

No one reads documentation :-). One would think IUPAC International Chemical **Identifier** might be a hint. There are many talks from Steve (InChI director) with this slide - "InChI is not a replacement for any existing internal structure representations. InChI is in ADDITION to what one uses internally. Its value to chemists is in FINDING and LINKING information" http://www.hellers.com/steve/pub-talks/schrodinger-6-17.pdf

Depends on what you're doing, in flatland cheminformatics SMILES is best (IMO). But SDF is useful for 3D.

**Comment by johnmay** [comment]
Out of interest why do you presume MDL/MOL/SDF is the most comprehensive? One of my more fun talks I gave at an InChI meeting [Building on Sand: Standard InChIs on non-standard molfiles](https://www.inchi-trust.org/wp/wp-content/uploads/2017/11/12.-John-Mayfield-JWM_BuildingOnSand_InChIFall17.pdf)

**Comment by kaibioinfo** [comment]
> No one reads documentation :-)
I think any programmer who is using a library is definitely reading the corresponding API docs

>  One would think IUPAC International Chemical Identifier might be a hint. 
Not really. Having a canonical representation of something does not mean that you can only use it as identifier.

> Depends on what you're doing, in flatland cheminformatics SMILES is best (IMO). But SDF is useful for 3D.
Thanks!

> Out of interest why do you presume MDL/MOL/SDF is the most comprehensive?
As said, I'm not from cheminformatics. I know that chemical reality is quite complex, but I'm fine with working on simple molecular graphs and with any data format that translates into a graph structure in a consistent way.
