### ISSUE TITLE
Reading IMolecularFormula from String and converting back to String produce different results

### ISSUE THREAD

**Issue by meier-rene** [cdk/cdk#484]
In case of charged molecules its not possible to read in a String with MolecularFormulaManipulator.getMolecularFormula and convert back to the same String with MolecularFormulaManipulator.getString. Example code:

```
String f="[C3H7]+";
System.out.println(f);
IMolecularFormula m = MolecularFormulaManipulator.getMolecularFormula(f, DefaultChemObjectBuilder.getInstance());
System.out.println(String zurück=MolecularFormulaManipulator.getString(m));
```

will print out:
```
[C3H7]+
C3H7
```

For MolecularFormulaManipulator.getHTML its possible to get the charge information back. It would be really nice if it would be possible to get the same information from an internal data structure back which was used to construct it.
Could you please provide a method or would you accept a patch which includes this?

**Comment by johnmay** [comment]
Resolved, thanks.
