### ISSUE TITLE
InChIGeneratorTest hangs on 64bit Java8/Debian

### ISSUE THREAD

**Issue by egonw** [cdk/cdk#507]
When I run the test suite with:

```shell
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 mvn -Dmaven.test.failure.ignore=true install
```

One of the cdk-inchi modules hangs, with a pristine master, last commit https://github.com/cdk/cdk/commit/5950ab8bbd2bdd5c955ce9ce23391241dacaa5ab:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.openscience.cdk.graph.invariant.InChINumbersToolsTest
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.256 s - in org.openscience.cdk.graph.invariant.InChINumbersToolsTest
[INFO] Running org.openscience.cdk.inchi.InChIToStructureTest
[INFO] Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 s - in org.openscience.cdk.inchi.InChIToStructureTest
[INFO] Running org.openscience.cdk.inchi.InChIGeneratorFactoryTest
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.111 s - in org.openscience.cdk.inchi.InChIGeneratorFactoryTest
[INFO] Running org.openscience.cdk.inchi.InChIGeneratorTest
```

It then takes up one CPU computing fully, but the test does not end... (more details after I had time for more exploration).

**Comment by johnmay** [comment]
InChI is not thread safe, at least definitely not the one we're using.

Maybe we should switch to a JNA approach: https://github.com/dan2097/jna-inchi

**Comment by johnmay** [comment]
Sorry to add clarity, forked tests and InChI will not mix.

**Comment by egonw** [comment]
That's a problem then, because it seems that newer Surefire version use that by default... and first tests suggest that using an explicit forkCount=0 does not improve the situation...

Either case, we will need to update to pom.xml to explicitly say to not do forking for this module then... 

(I think this change of behavior of Surefire also explains why I got all those Jenkins compile issues all of a sudden...)

**Comment by johnmay** [comment]
But we didn't change the surefire version...

**Comment by egonw** [comment]
Well, not directly... but the current pom says 2.20, which can be any of the minor releases... now 2.20.1 has a regression that 2.20.0 did not have... I have not been able to figure out of that is causing the problems I see, but SO shows this has caused problems for others...

**Comment by egonw** [comment]
Getting to it. Sorry for the delay.

**Comment by egonw** [comment]
OK, they problem is the test for the time out, where the time out in the InChI library does not happen. The CDK code writes:

```java
public static final String FIVE_SECOND_TIMEOUT = "-W5";
```

But clearly, it doesn't time out for me...

**Comment by egonw** [comment]
Mmm... that 8 sec time out on the test, works, but there seems to be more going on:

![image](https://user-images.githubusercontent.com/26721/50729311-f7379800-1137-11e9-9043-a41651b70313.png)

**Comment by egonw** [comment]
I think I pinned it down to recognition of the time out `inchiFact.getInChIGenerator(mol, "W0.01");`... making that option `W1` makes it properly time out after a second...

**Comment by egonw** [comment]
@johnmay, it seems anything like `W0.xxx` seems to fail. It gets recognized is `W0` (infinite). And this seems to be in the JNI-InChI library, not the CDK code.

**Comment by egonw** [comment]
I added a patch here: https://github.com/cdk/cdk/pull/528/commits/08286b9869adf6220928da08cbf009ad347d6bdf

**Comment by johnmay** [comment]
Curious... is this a locale problem again? Does Netherlands use ',' for decimal -W0,001?

**Comment by egonw** [comment]
I just realize I did not actually try to have the Java code just reformat the number according to the current platform to see what happens...

**Comment by johnmay** [comment]
Yes we should reformat, so changing to -W0,001 on your default localce also fixes?

**Comment by egonw** [comment]
To be confirmed... I was looking at a different issue (see the email I just send to cdk-devel...)

**Comment by egonw** [comment]
OK, seems confirmed: https://github.com/cdk/cdk/pull/529

**Comment by egonw** [comment]
seems to work fine now.

**Comment by studur** [comment]
Hi, I experienced the timeout test hang on my PC with master branch. I use JDK1.8_144 64 bits. Thank you.

**Comment by egonw** [comment]
Hi @studur, is that with the latest version from the `master` branch?

**Comment by studur** [comment]
Hi @egonw , yes I pulled the lastest and greatest yesterday

**Comment by johnmay** [comment]
Are you one Windows?

**Comment by studur** [comment]
Yes, Windows 10 pro

**Comment by johnmay** [comment]
Do you run Java in a different Locale to your system?


Can you put a print in here and see what comes out:

```java
            } else if (isTimeoutOptions(op)) {
                if (op.contains(".") || op.contains(",")) { // only reformat if we actually have a decimal
                    // because the JNI-InChI library is expecting an platform number, format it as such
	                Double time = Double.parseDouble(op.substring(1));
	                DecimalFormat format = new DecimalFormat("#.##");
                    sbOptions.append(FLAG_CHAR).append('W').append(format.format(time));
                    System.out.println(Locale.getDefault() + ": " + sbOptions.toString()); // add this line
                } else {
                    sbOptions.append(FLAG_CHAR).append(op);
                }
                hasUserSpecifiedTimeout = true;
                if (tok.hasMoreTokens()) {
                    sbOptions.append(" ");
                }
            }
```

**Comment by johnmay** [comment]
BTW you need to update ``isTimeoutOptions`` method as well but wouldn't affect this case.

**Comment by studur** [comment]
@johnmay I can't right now, will do when I get home. But in any case, if the test is strongly dependent on the machine where is it executed, should it be only run in the build server by activating a build profile to the pom? Just an idea to make the build process more portable for general population. Thanx

**Comment by johnmay** [comment]
Well we do want this code to run universally...  and it should. The problem is actually a problem with the InChI but since the InChI isn't Open Source I can't patch it.... curiously at a meeting discussing exactly that earlier this but the conclusion was mixed and InChI won't be on GitHub anytime soon. 

I am very curious now whether you had it working before Egon's patch.

**Comment by studur** [comment]
@johnmay I added the line you specified and I got
`fr_CA: /W0,01`

**Comment by egonw** [comment]
@johnmay, what if we give people to just overwrite the Locale or even allow them to just say it should use a period or a comma on their platform? Just can in case the code does not get it right?

**Comment by johnmay** [comment]
Okay that's the problem: *I got fr_CA as the System locale option and en_CA as the regional input locale.*

@studur Could you run:

```
System.out.println(Locale.getDefault(Locale.Category.DISPLAY));
System.out.println(Locale.getDefault(Locale.Category.FORMAT));
```

**Comment by johnmay** [comment]
``@johnmay, what if we give people to just overwrite the Locale or even allow them to just say it should use a period or a comma on their platform? Just can in case the code does not get it right?``

No because it's not obvious and depends on locale which can be changed.

**Comment by studur** [comment]
I may have found a fix, The code snippet only change the decimal separator to a digit in the option String. But this String is probably parsed back to a Double containing a period. For the sake of the test, you can change the default locale to en_US before the test and set it back to its original value after. Of course, it only works for the test so in real life a long InChi string would not timeout if the locale is not set properly in the main but it might be the source of a probable fix.
`  @Test()
    public void timeout() throws Exception {
        Locale currentLocale = Locale.getDefault();
        Locale.setDefault(new Locale("en", "US"));
        IChemObjectBuilder bldr = SilentChemObjectBuilder.getInstance();
        SmilesParser smipar = new SmilesParser(bldr);
        String smiles = "....."
        IAtomContainer mol = smipar.parseSmiles(smiles);
        InChIGeneratorFactory inchiFact = InChIGeneratorFactory.getInstance();
        InChIGenerator generator = inchiFact.getInChIGenerator(mol, "W0.01");
        assertThat(generator.getReturnStatus(), is(INCHI_RET.ERROR));
        assertThat(generator.getLog(), containsString("Time limit exceeded"));
        Locale.setDefault(currentLocale);
`

**Comment by egonw** [comment]
Or if the InChI library would accept digits in both locale's... with a period and a comma...

**Comment by studur** [comment]
@johnmay Both Locale.Category.DISPLAY and FORMAT gave ","

**Comment by studur** [comment]
This line generates the number using Locale default decimal separator (not period by default)
I added the following and it worked on my machine 
```
} else if (isTimeoutOptions(op)) {
                if (op.contains(".") || op.contains(",")) { // only reformat if we actually have a decimal
                    // because the JNI-InChI library is expecting an platform number, format it as such
                    Double time = Double.parseDouble(op.substring(1));
                    DecimalFormat decimalFormat = new DecimalFormat("#.##");
                    String timeoutOption = decimalFormat.format(time).replace(",", "."); // add this line
                    sbOptions.append(FLAG_CHAR).append('W').append(timeoutOption);  // update this line with new variable
                } else {
                    sbOptions.append(FLAG_CHAR).append(op);
                }
```

**Comment by johnmay** [comment]
> Both Locale.Category.DISPLAY and FORMAT gave ","

So they both said fr_CA, I'm tempted to say this is also a windows bug. http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=7073906

> I added the following and it worked on my machine

This is unfortunately not the solution, that will again break Egon's machine.

> Or if the InChI library would accept digits in both locale's... with a period and a comma...

This is the correct fix but that's not going to happen, a) we're not even on the latest InChI code base and b) I know bugs that were submitted years ago and not fixed.

```
Locale currentLocale = Locale.getDefault();
Locale.setDefault(new Locale("en", "US"));
//do test
Locale.setDefault(currentLocale);
```

This may be possible, the issue is whether the JNI code picks up the formatting, Egon would have to confirm this I think at the least it will be when ``System.loadLibrary()`` is called which again is out of our control in JNI-InChI wrapper (we could override this though).

**Comment by johnmay** [comment]
Confirmed the native code does not pick up the locale. For example even if I set at JVM startup to fr_CA it should mean the native code would load as this too. 

```
Locale currentLocale = Locale.getDefault();
Locale.setDefault(new Locale("en", "US"));
//do test
Locale.setDefault(currentLocale);
```

**Comment by johnmay** [comment]
One option is to inspect the locales in a system dependant way
