### ISSUE TITLE
WeightDescriptor calculates monoisotopic mass

### ISSUE THREAD

**Issue by kazuyaujihara** [cdk/cdk#510]
Although WeightDescriptor's Javadoc explains calculating molecular weight, it calculates the monoisotopic mass.

**Comment by johnmay** [comment]
Am currently discussing naming with Emma et al. but it should update to Average Mol Weight and call the correct method.

**Comment by studur** [comment]
Actually, the method adds the natural atomic weight of hydrogen (1.00794) to the element isotopic exact mass. Debugging stepping through the testWeightDescriptor method in the WeightDescriptorTest clearly shows the calculation.

**Comment by studur** [comment]
I created a branch and modified the calculate method to return the natural weight but is that what you want ? What is the typical behavior expected for this class ?

**Comment by studur** [comment]
Submitted fix in PR https://github.com/cdk/cdk/pull/543 @kazuyaujihara @johnmay.
Would it be useful to create another IsotopicWeightDescriptor for exact mass ? If someone want to get the exact mass of a molecule containing deuterium or 13C for example ?

**Comment by johnmay** [comment]
> Would it be useful to create another IsotopicWeightDescriptor for exact mass

No, sorry we decided what to do with this off-list a few months ago but not got round to implementing yet. Essentially there will be a variable to control which one you want.

**Comment by studur** [comment]
OK thank you.
