### ISSUE TITLE
Smiles parser behaviour "Ring closure bonds" error

### ISSUE THREAD

**Issue by vedina** [cdk/cdk#516]
@johnmay , could you please help - the current strict [behaviour](http://efficientbits.blogspot.com/2013/12/new-smiles-behaviour-parsing-cdk-154.html) of the SMILES parser giving errors like the one below is a showstopper.

` Ring closure bonds did not match. Ring was opened with '/' and closed with '\'. Note - directional bonds ('/','\') are relative.`

Could you suggest a way to relax it?

**Comment by johnmay** [comment]
Why is it a showstopper? The SMILES are invalid. 

The issue I had with relaxing this was toolkits did different things. When the SMILES is written incorrectly ChemDraw, OEChem, BIOVIA and ChemAxon ignore the first definition, RDKit ignores the second.

```
C\1.C/C=C\1 erroneous input
C1.C/C=C\1 cis (as read by ChemDraw, OEChem, BIOVIA, and ChemAxon)
C\1.C/C=C1 trans (as read by RDKit)
```

However I now think is the nicer behaviour is to ignore the stereochemistry completely (this is Open Babel's behaviour). It's still a pretty serious problem though and you should question the molecules coming in.

**Comment by egonw** [comment]
This is why I have been fan of the idea to have a strict and a relaxed mode. The latter throws warnings of problems, while the first fails one them.

The people that have these unclear SMILES may want to get the message that their structures do not actually specify the stereochemistry, and they may want to revisit that.

**Comment by johnmay** [comment]
There is already a strict and relaxed mode... I just felt this was too bad
to overlook.

**Comment by egonw** [comment]
Sorry about that :( in January I'll work on updating my groovy CDK book and learn about all the new apis...

**Comment by vedina** [comment]
John, do you mean there is already a way to switch off the "ring closure"  error ?

**Comment by johnmay** [comment]
> John, do you mean there is already a way to switch off the "ring closure" error ?

No, it's already in "non-strict" mode and still considered an error. The distinction for "warnings/errors" is non-strict will not allow ambiguous input. However now I think the way to go is to ignore the stereo on that bond completely it's no longer ambiguous. Kekulization errors for example will still be failures.

Come to think of it I don't think you can configure this from CDK but I'll add that when I add the patch for ignoring bond stereo.

**Comment by vedina** [comment]
> Come to think of it I don't think you can currently configure strict/non-strict this from CDK (it's within Beam) but I'll add that when I add the patch for ignoring bond stereo.

Thanks!

**Comment by johnmay** [comment]
I'm think of making the warning, "Your SMILES are bad you should feel bad."

**Comment by johnmay** [comment]
Resolve in #522
