### ISSUE TITLE
Get java.lang.NullPointerException when call getAllSurfacePoints()

### ISSUE THREAD

**Issue by Luckick** [cdk/cdk#519]
Hi, 

I am new to CDK.
I just followed an example in groovy, and I want to read a pdf file, get the points on molecule surface.

The code is below:
`
PDBReader reader = new PDBReader(new FileInputStream(file));
ChemFile crambin = reader.read(new ChemFile());
List<IAtomContainer> containers= ChemFileManipulator.getAllAtomContainers(crambin);
for (int i = 0; i< containers.size(); i++) {
	IAtomContainer container = containers.get(i);
	String description = container.toString();
	NumericalSurface new_surface = new NumericalSurface(container);
        Point3d[] points= new_surface.getAllSurfacePoints();
}
`
catch the exception java.lang.NullPointerException in last step.

Anyone can help me with this? 
Thanks a lot!

**Comment by Luckick** [comment]
> Thanks for reporting the issue, I presume you used `1CRN.pdb`?

No I am not. I tried 1x7a, 1a1e, 2y80, 1a4r etc...
No one works now. 

Thank you!

**Comment by johnmay** [comment]
Sorry only just got round to this as busy time of year. You need to call:

```
new_surface.calculateSurface(); 
```

before accessing the points.  However there's

**Comment by johnmay** [comment]
Sorry to clarify, I've made a patch so in future your current code will work fine. For now call the calculate method before accessing the points.

**Comment by Luckick** [comment]
Thank you a lot! It works now!

**Comment by johnmay** [comment]
I'm not quite sure what you mean? If you mean which atoms are associated with points on the surface then not that I can see.

**Comment by Luckick** [comment]
Yes, points belong to which atom is one of my interest. Then we can assign the properties of the atom on points. 
I am also interested in other properties about the surface itself instead of atom properties.
Thank you for your kind help!
