### ISSUE TITLE
Assertions that test nothing (found by static analysis)

### ISSUE THREAD

**Issue by amaembo** [cdk/cdk#530]
Hello!

One more set of issues found by IntelliJ IDEA static analysis, this time it's about assertions that test nothing.

1. org.openscience.cdk.atomtype.AbstractAtomTypeTest#addTestedAtomType (line 153)
```java
        } catch (NoSuchAtomTypeException exception) {
            Assert.assertNotNull("Attempt to test atom type which is not defined in the " + getAtomTypeListName()
                    + ": " + exception.getMessage());
        }
```
This assertion never fails as it tests that the message is not null. Probably second argument is missing or `Assert.fail` was intended.

2. org.openscience.cdk.charges.GasteigerMarsiliPartialChargesTest#testAssignGasteigerSigmaMarsiliFactors_IAtomContainer (line 129)
```java
Assert.assertNotNull(peoe.assignGasteigerSigmaMarsiliFactors(molecule).length);
```
Comparing array length to null is ridiculous. Probably `Assert.assertTrue(peoe.assignGasteigerSigmaMarsiliFactors(molecule).length > 0);` was intended

3. org.openscience.cdk.qsar.descriptors.atomic.IPAtomicLearningDescriptorTest#testIPDescriptor_14
```java
double result = ((DoubleResult) descriptor.calculate(mol.getAtom(2), mol).getValue()).doubleValue();
Assert.assertNotNull(result);

result = ((DoubleResult) descriptor.calculate(mol.getAtom(7), mol).getValue()).doubleValue();
Assert.assertNotNull(result);
```
Again a primitive value is tested to be not-null which can never fail. At least checking for some result range would be more reasonable.

Similar: org.openscience.cdk.charges.PolarizabilityTest#testGetPolarizabilitiyFactorForAtom_IAtomContainer_IAtom
org.openscience.cdk.charges.PolarizabilityTest#testCalculateBondPolarizability_IAtomContainer_IBond

4. org.openscience.cdk.qsar.descriptors.atomic.PartialPiChargeDescriptorTest#testPartialPiChargeDescriptor_Methyl_Fluoride (line 99)
```java
double result = ((DoubleResult) descriptor.calculate(molecule.getAtom(i), molecule).getValue())
                    .doubleValue();
Assert.assertNotNull(result); // similar, though result is examined afterwards, probably could be removed

if (testResult[i] == 0.0)
   Assert.assertTrue(result == 0.0);
else {
   Assert.assertTrue(result != 0.0);
```
Other similar cases in the same file: lines 152,203,262,332,404,471,543,597,684,767,827,866,867,918,974,1008

5. org.openscience.cdk.io.formats.ResourceFormatTest#testIsXMLBased
```java
Assert.assertNotNull(resourceFormat.isXMLBased());
```
Probably `assertTrue(resourceFormat.isXMLBased());` was intended

Also you have about 25 assertions where it's checked that newly created object is not-null. E.g. org.openscience.cdk.charges.PiElectronegativityTest#testPiElectronegativity_Int_Int:
```java
Assert.assertNotNull(new PiElectronegativity(6, 50));
```
According to Java specification the result of `new` is never null, so such assertion is also useless. If you test that constructor correctly finishes without throwing an exception, it's less confusing to write simply `new PiElectronegativity(6, 50);`. Though probably it's better to check something afterwards. E.g.:
```java
PiElectronegativity p = new PiElectronegativity(6, 50);
assertEquals(6, p.getMaxIterations());
assertEquals(50, p.getMaxResonStruc());
```
Improving all of these cases is not mechanical, so I'm not sure whether you'd like to do this. However if you want I can supply the full list of such assertions.

**Comment by johnmay** [comment]
Resolved
