### ISSUE TITLE
Problem loading InChI libraries

### ISSUE THREAD

**Issue by tdudgeon** [cdk/cdk#534]
I'm having a problem loading the InChI libraries with JNI and would like some advice on this.
This is happening from a Tomcat servlet running inside a Docker container.
When Tomcat is running as the root user it works fine. But when Tomcat runs as a non-root user, which is much better practice, I see errors like this in the logs:
```
Error loading JNI InChI native code.
You may need to compile the native code for your platform.
See http://jni-inchi.sourceforge.net for instructions.
```
So there seems to be something that needs elevated privs to do this.
But there's nothing fundamentally wrong with doing this from Tomcat as a non-root user as I'm successfully loading the RDKit Java wrappers from inside the same Tomcat/Container instance using a non-root user.

Can someone point me to information on how and where the InChI libraries are being loaded, and maybe give me some hints as to what might be wrong here?
Thanks.

**Comment by johnmay** [comment]
CDK uses [JNI-InChI](http://jni-inchi.sourceforge.net/) but that's no longer maintained. Only thing I could suggest is make sure the docker user has a home directory, the native libraries get unpacked and loaded from there and if it worked as root that sounds like a reason. Someone did have another problem with InChI (via CDK) in docker where they needed to compile the InChI library and the insert it in the JAR but this sounds unrelated if it worked as root (hence my guess on the home dir).

There is scope to switch to not using JNI-InChI and [use JNA](https://github.com/dan2097/jna-inchi/issues) but since i'm not really a fan of the InChI in the first place I'm not very motivated to do it.

**Comment by tdudgeon** [comment]
Hi John, yes you were right, the user does need a home directory and in my case it didn't have one.
Creating a home directory seems to have fixed this.
Thanks for the suggestion.

**Comment by Danissss** [comment]
Hi @johnmay, 
May I ask how to build the JNI-InChI from source?
The repo is gone [jni-inchi](https://jni-inchi.svn.sourceforge.net/svnroot/jni-inchi)
Thanks

**Comment by johnmay** [comment]
Never tried, the tricky part is you need to build it on all platforms Windows/Linux/OS X 32 bit/64 bit...

https://sourceforge.net/p/jni-inchi/code/HEAD/tree/
https://sourceforge.net/projects/jni-inchi/files/

**Comment by johnmay** [comment]
If it's just for you you can build it for your platform.

**Comment by Danissss** [comment]
Hi @johnmay 

Thanks for reply.
The CDK code seems look for jni-inchi remote repository
 `DEBUG net.sf.jnati.deploy.repository.RemoteRepository  - Not found: http://jnati.sourceforge.net/jnati-repo/jniinchi/1.03_1/jniinchi-1.03_1-LINUX-AMD64.jar`

May I ask how should I change the CDK to look for local jar file?

Thanks!

**Comment by johnmay** [comment]
You need to install the jar in your local maven repo (mvn
install:install-file -Dfile=myjar.jar -D... etc etc) and then change the
CDK pom to use that version.

**Comment by Danissss** [comment]
Hi @johnmay 
Thanks for reply.

I got the `jni-inchi-0.9-SNAPSHOT.jar` from `mvn package`, but I don't know how to change CDK pom.xml to point that jar. Should I re-build CDK on my machine with that jar file?

Thanks!

**Comment by johnmay** [comment]
Yes, in the root CDK pom just change the version to 0.9-SNAPSHOT.

e.g. Here:
https://github.com/cdk/cdk/blob/master/pom.xml#L466-L470

```xml
            <dependency>
                <groupId>net.sf.jni-inchi</groupId>
                <artifactId>jni-inchi</artifactId>
                <version>0.9-SNAPSHOT</version>
            </dependency>
```

Make sure you've installed it first...

```bash
mvn install:install-file -Dfile=jni-inchi-0.9-SNAPSHOT.jar \ 
                         -Dpackaging=jar \
                         -DgeneratePom=true \
                         -DgroupdId=net.sf.jni-inchi \
                         -DartifactId=jni-inchi \
                         -Dversion=0.9-SNAPSHOT
```

When you're installing custom deps like I would actually give it a more distinctive name for the version, for example:

```bash
mvn install:install-file -Dfile=jni-inchi-0.9-SNAPSHOT.jar \ 
                         -Dpackaging=jar \
                         -DgeneratePom=true \
                         -DgroupdId=net.sf.jni-inchi \
                         -DartifactId=jni-inchi \
                         -Dversion=0.9-danissss
```

Then just change the ``pom.xml`` to:

```xml
            <dependency>
                <groupId>net.sf.jni-inchi</groupId>
                <artifactId>jni-inchi</artifactId>
                <version>0.9-danissss</version>
            </dependency>
```

**Comment by Danissss** [comment]
Hi @johnmay 

Thank you for your detailed instruction.
I learned a lot about maven.
Thanks!
