### ISSUE TITLE
SmilesGenerator 2.2 

### ISSUE THREAD

**Issue by bartailey** [cdk/cdk#535]

**Comment by johnmay** [comment]
?

**Comment by bartailey** [comment]
Sorry I realised as I was constructing the post what the issue was. I thought I had closed the issue. 

Thanks for the prompt reply. Been very impressed with the software, used for it for both deep learning project and searching an in house chemistry database. 

Yours Bart. 

--
E: bartlettailey@yahoo.co.uk
