### ISSUE TITLE
mac installation 

### ISSUE THREAD

**Issue by diosphenol** [cdk/cdk#537]
I tried every possible advise to install it on Mac-Os mojave but all unfortunately not working and always getting check the console for possible error messages.
thanks in advance 
MAZ

**Comment by egonw** [comment]
Can you please provide more information? Versions of your OS, Java, and the error message?

**Comment by egonw** [comment]
Okay, that's not a Java exception. What jar are you executing and with what specific command?

**Comment by diosphenol** [comment]
i am opening CDK-2.2.jar on the terminal using java --jar (the file location) and got this

Mazs-MacBook-Pro:~ Maz$ java --jar/Users/Maz/Downloads/cdk-2.2\ \(1\).jar 
Unrecognized option: --jar/Users/Maz/Downloads/cdk-2.2 (1).jar
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Mazs-MacBook-Pro:~ Maz$

**Comment by egonw** [comment]
Please try this one by adding a space after the `--jar`. But that said, CDK is a library and not a program with a CLI of UI. What are you trying to do?

**Comment by diosphenol** [comment]
I am totally ignorant in this stuff, If I got what you mean, This isn't a stand alone program and I can utilise it on other platforms like python!

**Comment by egonw** [comment]
Indeed. The chapter needs updating, but check Ch. 14 here: https://figshare.com/articles/Edition_1_4_1_0_of_Groovy_Cheminformatics_with_the_Chemistry_Development_Kit/2057790

**Comment by johnmay** [comment]
BTW it's ``java -jar` not `java --jar``

**Comment by diosphenol** [comment]
Thanks mate
