### ISSUE TITLE
Cite Articles

### ISSUE THREAD

**Issue by Luckick** [cdk/cdk#542]
Hi,

There are some cite information at the beginning of .java file.
e.g. {@cdk.cite EIS95} in NeighborList.java.

Where can I find the name of the cited paper?
Or at least for EIS95, which paper does it refer to?

Thank you!

**Comment by johnmay** [comment]
They get inserted in to  the documentation, for example: [NeighborList](http://cdk.github.io/cdk/latest/docs/api/index.html?org/openscience/cdk/geometry/surface/NeighborList.html).

**Comment by Luckick** [comment]
It mentioned in the documentation that the routine is a simplified version of the neighbor list described in (Eisenhaber, F. et. al.. Journal of Computational Chemistry. 1995. 16) and is based on the implementation by Peter McCluskey.

Any document refer to describe the simplified version details and the implementation by Peter McCluskey?
Thanks.

**Comment by egonw** [comment]
If it is not cited, then probably not other than the source code itself.

PS. you can find the "bibtex" file with all the references here: https://github.com/cdk/cdk-build-util/blob/master/src/main/resources/net/sf/cdk/tools/doclets/cheminf.bibx#L1174
