### ISSUE TITLE
Compare atomic number rather than symbol.

### ISSUE THREAD

**Issue by kazuyaujihara** [cdk/cdk#546]
There are a lot of codes for checking which atom IElement object is. 
For example,
`if (atom.getSymbol().equals("H")) { ... }`
`if (!(bond.getBegin().getSymbol().equals("H") && bond.getEnd().getSymbol().equals("H"))) { ... }`

These can be modified like the following and which should show better performance.
`if (atom.getAtomicNumber() == 1) { ... }`
`if (!(bond.getBegin().getAtomicNumber() == 1 && bond.getEnd().getAtomicNumber() == 1)) { ... }`

In fact, current implementation of getSymbol() in org.openscience.cdk.Element.java get the symbol through `Elements.ofNumber(atomicNumber)` method. It is possible to implement an Element class in which getSymbol() returns "H" and getAtomicNumber() returns 5, but it is nonsense to think about such a thing.
I implemented such changes with NCDK, and it seems to work.

**Comment by johnmay** [comment]
> In fact, current implementation of getSymbol() in org.openscience.cdk.Element.java get the symbol through `Elements.ofNumber(atomicNumber)` method. It is possible to implement an Element class in which getSymbol() returns "H" and getAtomicNumber() returns 5, but it is nonsense to think about such a thing.

So that's actually a relatively recent change, **atomic number** and **symbol** were previously independent and "could" be inconsistent. As you say nonsense hence why it's no longer like this but explains why a lot of the existing code checks the symbol.

Maybe "Junior Task" Egon?

**Comment by kazuyaujihara** [comment]
I believe that getSymbol() method is not stable because the return value can be changed by assigning new elements like "Uut" to "Nh". In some case, element symbol written in local language is useful. For example, "氢" for H.
I recommend updating this problem from this point.

**Comment by egonw** [comment]
@johnmay, something like https://github.com/cdk/junior-jobs/issues/1 ?

**Comment by kazuyaujihara** [comment]
@egonw @johnmay 
So it is not destructive change, I consider that it is more convenient to treat this issue in branch rather than junior job. 
By the way, in order to avoid to use the magic number and to make effective optimization, something like the following class is needed. What do you think about it? And if you agree, which package is good place to put it? 
```
public final class AtomicNumbers {
    public final static int H = 1,
    public final static int He = 2,
    public final static int Li = 3,
    ....
}
```

**Comment by egonw** [comment]
The idea of the junior job is just that it is a lot of work to update all the code. That's all. It's not mean that you should wait, or someone else should do it; more that just all hands are welcome. All patches should come in as pull request, just as useful.

Regarding the `AtomicNumers`, would https://github.com/cdk/cdk/blob/master/base/core/src/main/java/org/openscience/cdk/config/Elements.java not work fine?

**Comment by johnmay** [comment]
Yes we have the enum for this, ``Elements.Hydrogen.number()` it has always annoyed me with pluralisation though and in hindsight I do prefer the simpler integer based enums as it's a little more elegant. In fact I do that in BEAM v2!

**Comment by kazuyaujihara** [comment]
Elements.number is read-only field but we can treat an atomic number as a constant. It is desirable from optimization.

**Comment by johnmay** [comment]
Egon miss-typed, you need to access by a method - ``Elements.Hydrogen.number()``. The JIT will definitely inline the the method call and hopefully actually remove the enum entirely. Of course hoping such optimisations occur isn't ideal.

**Comment by egonw** [comment]
@blurock, for atoms groups the `IPseudoAtom` interface was created.

**Comment by johnmay** [comment]
Actually for the the specific example of CO and CN for functional groups these should be as **Sgroups** since they are just display short cuts. The **Abbreviations** API allows you to create these and these can round tripped though ChemDraw, MarvinSketch etc using MOLfile.

```
SmilesParser smipar = new SmilesParser(SilentChemObjectBuilder.getInstance());
IAtomContainer mol = smipar.parseSmiles("c1ccc([N+](=O)[O-])cc1CN");
Abbreviations abbr = new Abbreviations();
abbr.add("*CN CN");
abbr.add("*[N+](=O)O NO2");
abbr.apply(mol);
try (MDLV2000Writer mdlw = new MDLV2000Writer(System.out)) {
    mdlw.write(mol);
}
```

```

  CDK     0209211134

 13 13  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 N   0  3  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 O   0  5  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
  3  4  2  0  0  0  0
  4  5  1  0  0  0  0
  5  6  2  0  0  0  0
  6  7  1  0  0  0  0
  7  8  2  0  0  0  0
  7  9  1  0  0  0  0
  6 10  1  0  0  0  0
 10 11  2  0  0  0  0
  3 11  1  0  0  0  0
 11 12  1  0  0  0  0
 12 13  1  0  0  0  0
M  CHG  1   7   1
M  CHG  1   9  -1
M  STY  2   1 SUP   2 SUP
M  SAL   1  3   7   8   9
M  SBL   1  1   6
M  SMT   1 NO2
M  SAL   2  2  12  13
M  SBL   2  1  12
M  SMT   2 CN
M  END
```

**Comment by blurock** [comment]
The problem I have with IPseudoAtom is that I would like to have my 'meta-atoms', what you would call pseudo atoms, to actually act like atoms -- It is not just a label, I need both the atom and the pseudo/meta to look the same (in an object-oriented way).
I do not what special code to differentiate whether the atom is a 'normal' atom or one of my meta-atoms. Thus my solution was to define a class above Atom which redefines the setSymbol and getSymbol methods. For my brand of matching I have a class that implements IQueryAtom and is above Atom (for the use of the isomorphism routines UniversalIsomorphismTester

Some documentation on my usage
https://sites.google.com/view/jthergas/fundamentals/molecular-representations/meta-atoms?authuser=0

**Comment by egonw** [comment]
Check @johnmay's comment. We originally had `IFragmentAtom` for exactly that: https://cdk.github.io/cdk/latest/docs/api/org/openscience/cdk/interfaces/IFragmentAtom.html

**Comment by blurock** [comment]
That looks interesting for me...
But that it is derived from IPseudoAtom, I think I still have the problem with Symbol..
Is the symbol null for this IFragmentAtom?
(sorry, haven't looked at the code yet)

**Comment by johnmay** [comment]
It was bad design to have both atomic number and a symbol that can contradict. What is the issue using IPseudoAtom, it inherits from IAtom so you can use it anywhere at atom is used? They even get loaded in automatically from SMILES e.g. ``c1ccccc1[CN]`. I was thinking we may make getSymbol() for pseudo atom return the label but I really don't think there is an issue.

Let's back up a bit, what are you trying to do, why do you need these in the first place? https://en.wikipedia.org/wiki/XY_problem

**Comment by blurock** [comment]
@johnmay -- As I said several times, the root of my problem is that I want to check an atom and my meta-atom in the same way.
In my solution, this involves checking (often among other things, I use IQueryAtom) the symbol match. 
Using IPseudoAtom or IFragment (which I like, BTW, and might in a rewrite incorporate it) uses label, so in comparing, I would have to, in a very non-object-oriented way, make a check whether i should look at symbol or label to have a match.

I understand the consistency problem of symbol and atomic number -- Inconsistencies arise because pseudoatoms and fragments are derived from Atom and do not necessarily have unique (meaning isomers) atomic weights or, in how they are used, symbols.
But not making them derived from Atom causes more problems (In my opinion)
So I understand the dilemma -- 
Historically, I wrote the core of this code when Symbol and Atomic number were not bound and it is only in recent debugging (the code slept for a bit) that i ran into this problem. I found the problem hen I could bind an artibrary name to symbol - it became null and then everything matched.

As you can read in some of my documentation (incomplete, still in progress) link, I use meta-atoms in several ways,
sometimes as fragments, sometimes including valence information (such as single double triple, aromatic etc). This is to differentiate simply with a text symbol, the different types.
https://sites.google.com/view/jthergas/fundamentals/molecular-representations/meta-atoms?authuser=0
(you can see exactly how -- and a bit of why -- I use this in my application in searching about the docs around the link).

I hope that helps... at the moment I found my solution that works... my meta atom overrides get and set symbol.
But I am open for a consistent solution.

**Comment by egonw** [comment]
> to have both atomic number and a symbol that can contradict.

It was.

**Comment by johnmay** [comment]
> my meta atom overrides get and set symbol. But I am open for a consistent solution.

I think this is a good way forward and is what Pseudo atom should (will) do. You could always just have a custom QueryAtom that checks if the atom is an IPseudoAtom and checks the label otherwise checks the symbol

**Comment by johnmay** [comment]
@xperrylinn Made some great patches for this and now the Canonical way of checking Atom is 


```
if (atom.getAtomicNumber() == IAtom.C) {
}
```
or (preferred by SonarCloud):
```
if (atom.getAtomicNumber() == IElement.C) {
}
```
However there are still lots of cases comparing Strings which we could remove so leaving this open.
