### ISSUE TITLE
Warning when read Mol2 file

### ISSUE THREAD

**Issue by Luckick** [cdk/cdk#548]
Hi,

I got the 2 kinds of warnings when I use Mol2Reader as follows:
`
Mol2Reader reader = new Mol2Reader(new FileInputStream(file));
ChemFile crambin = reader.read(new ChemFile());   
`
The warnings are:
org.openscience.cdk.config.atomtypes.AtomTypeHandler WARN: Unrecognized hybridization in config file: tetrahedral
org.openscience.cdk.config.atomtypes.AtomTypeHandler WARN: Unrecognized hybridization in config file: octahedral
org.openscience.cdk.io.Mol2Reader WARN: Not reading molecule qualifiers

What does these warning mean (anything wrong within the mol2 file itself)? How should I handle them?

Thank you for your help!

**Comment by johnmay** [comment]
It's likely the parse does doesn't support some information in the file. In general I would avoid using Mol2.

**Comment by Luckick** [comment]
> It's likely the parse does doesn't support some information in the file. In general I would avoid using Mol2.

Then how about the SDF format? 
I found that the MDLReader has been Deprecated. How can I read SDF format into a 
ChemFile?

Thank you!

**Comment by johnmay** [comment]
Yeah it really is a bit muddled there, SDF/MOLfile or SMILES is best. For molfile you can use the MDLV2000Reader or the IteratingSDFReader. The iterating one is most general and therefore is what I would recommend, even if you have a single molecule as it will choose the one you need (i.e. V2000/V3000). Urgh don't read into a ChemFile...

```java
final boolean            noStopOnError = true;
final IChemObjectBuilder builder       = SilentChemObjectBuilder.getInstance();
try (InputStream in = new FileInputStream("/data/my.sdf"); // .mol also fine!
     IteratingSDFReader sdfr = new IteratingSDFReader(in, builder, noStopOnError)) {
    while (sdfr.hasNext()) {
        IAtomContainer mol = sdfr.next();
        // process molecule here
    }
} catch (IOException e) {
    System.err.println("Error: " + e.getMessage());
}
```

BTW Deprecated should does tell you want to use instead, for example MDLReader says:

![image](https://user-images.githubusercontent.com/983232/53591041-090f4780-3b8b-11e9-953c-e2b0f900b33d.png)

You may find this page useful: https://github.com/cdk/cdk/wiki/Toolkit-Rosetta

**Comment by Luckick** [comment]
Thank you so much!
This helps a lot!
