### ISSUE TITLE
CDK Depiction Bug

### ISSUE THREAD

**Issue by Kohulan** [cdk/cdk#551]
When I tried to depict a large molecule (EX: CHEMBL1090293) after generating coordinates using Structure diagram generator  , I saw some of the bonds and atoms are getting depicted through the molecule, which should have depicted into the canvas.

![Error](https://user-images.githubusercontent.com/30716951/54677720-cbf00280-4b03-11e9-867a-45f08b7562a4.png)

Snippet of the code used
`
IteratingSDFReader sdf = new IteratingSDFReader(sdfile, SilentChemObjectBuilder.getInstance());

sdg = new StructureDiagramGenerator();

while (sdf.hasNext()) {

	     molecule = sdf.next();
	     sdg.generateCoordinates(molecule);
	     DepictionGenerator dptgen = new DepictionGenerator().withSize(1024, 1024).withAtomValues();
}
`

**Comment by kazuyaujihara** [comment]
What is your solution?

**Comment by steinbeck** [comment]
No solution. Just a bug report. Obviously, either the SDG placement algorithm for the methoxy group ring substituents is buggy or the overlap resolution algorithm (some the methoxy groups will likely clash if laid out in a classical way) is failing.

**Comment by johnmay** [comment]
If you're reading from a ChEMBL SDF you already have some coordinates and don't need to re-generate them.

In general there will always be some molecules that don't have a nice 2D embedding without overlaps. In this case the bonds overlap if they point inwards so it tries to improve things by flipping them around but actually no better and so using some scoring functions it chooses the lesser of two evils. Some tools (e.g. ChemDraw/MOE) use much more expensive layout algorithms which is fine for a single or few molecule so if you need the best possible layout use those or draw it manually.

**Comment by steinbeck** [comment]
We are generating coordinates due to some reasons related to the research project in which we use this. Apart from that fact, ChEMBL also seems to use automatic layout. See https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL1090293
