### ISSUE TITLE
Wrongly calculates Lipinski's rule of 5 failures

### ISSUE THREAD

**Issue by Dirkie88** [cdk/cdk#552]
For about 20% of my compounds the Lipinski's rule of 5 failures are calculated wrongly.

Luckaly I can calculate the 5 properties, MW, nHbD, nHbA, nRB and LogP, from which I can calculate what the amount of Lipinski failures really should be.

Maybe this can be fixed? Maybe they have an implementation of the rule that is slightly different from the standard? Where/how can I find out how they've implemented the rules to calculate the number of failures?

**Comment by johnmay** [comment]
Can you provide more details on what is failing? For example is the rotatable bonds consistently wrong. Examples would be useful, thanks.

**Comment by egonw** [comment]
@johnmay, I was thinking the same thing. BTW, which logP algorithm is the RoF code using? Is that using the new JpLogP code or your reviewer ALogP code?

**Comment by johnmay** [comment]
It uses XLogP which could be the issue, switching to the patched ALogP or JpLogP may improve things. Unlikely to be the MW or rotatable bonds (but possible) that are wrong. So I think it may be H bond donors/acceptors. In fact there was an issue with the donor/acceptor counting at some point that got fixed.

@Dirkie88 which version are you using?

**Comment by kazuyaujihara** [comment]
In my opinion, stability for molecular descriptor is more important than precision because the calculated values are stored in the database on each compound's registration. And more they are predicted values before all. I consider that so the logic of XLogP is so simple and wildly used for a long time, it is applicable to use for default logP calculation method. In a case of Ro5, so original Lipinski's paper uses  Moriguchi's logP, Moriguchi's logP is the other option.
Anyway, adding an option to specify call back function for calculating logP is not so difficult.

**Comment by johnmay** [comment]
True but if people are using it as a hard filter (even when they shouldn't) it's best to be a precise as possible. If there is an obvious programming error in one of the thresholds that should be fixed.

I think we need more info from @Dirkie88 as can only guess it's LogP but possible it's one of the other thresholds.

**Comment by Dirkie88** [comment]
[Compounds_for_Lipinski.xlsx](https://github.com/cdk/cdk/files/3002689/Compounds_for_Lipinski.xlsx)

A few examples are attached. Jchem for Excel were used to generate the structures in column C. I apologize if you do not have that extention (academic license is free), nonetheless the smiles is given in column B. I should probably have mentioned this earlier but I use PaDEL to calculate descriptors (I was under the intention that PaDEL uses CDK without any alterations). In other words the issue would not be with PaDEL but with CDK itself. I apologize for not mentioning this, that's why I closed the feed but then decided I might just as well leave it open.

I've determined Lipinski failures (column J) with the following 5 criteria: MW>500, nHbD & LogP > 5, nHbA & nRB > 10. I've checked and these decriptors are all calculated correctly, no errors. AlogP is calculated with Ghose-Crippen LogKow. I've found that I can get the same result as the program by excluding the MW from my criteria. 

My comments then:
1. Either CDK only uses the latter 4 criteria and excludes MW but I base that guess only from what I've observed from about 50 compounds.
2. Maybe logP for the Lipinski failures is calculated with a different method than Ghose-Crippen LogKow, that alone, however, won't explain the result.
3. PaDEL could have introduced some alterations. I doubt this, but I haven't been able to figure out how to check this.

In any case, if needed I can calculate Lipinski failures myself, no need to rely on the number the program gives me. Nonetheless I though I'd mention my concern. Thanks for the comments. I'll end here.

Regards

**Comment by egonw** [comment]
@Dirkie88, PaDEL uses a very old version of the CDK. CDK 2.x fixes quite a number of inaccuracies in CDK 1.x and I recommend you use a recent version of the CDK.

**Comment by Dirkie88** [comment]
@egonw Thank you! Will do.

**Comment by egonw** [comment]
@Dirkie88, not that I have time this week, but would Groovy work for you? If so, I can write up an example in a section of https://egonw.github.io/cdkbook/descriptor.html ...

**Comment by Dirkie88** [comment]
I am aware now that PaDEL (2010) (with CDK 1), although a nice tool, is outdated and I should be looking for more updated software. PaDEL was easily accessible and usable (user friendly GUI) which was what I needed at the time. I've probably been putting it off because off the learning curve and time, I don't have experience with Groovy, nor with Java programming but I am keen to learn. I read the article on CDK: https://jcheminf.biomedcentral.com/articles/10.1186/s13321-017-0220-4. It's a no-brainer that I should be using the latest release on the CDK. I don't seem to find programs (such as PaDEL) that makes use of the latest CDK kit so I will have to figure this out myself. On that note yes I would appreciate the offer!

A final note and way off topic from the feed, for the record I've read up and tried Mordred (https://jcheminf.biomedcentral.com/articles/10.1186/s13321-018-0258-y), which you are probably familiar with. Also very promising software I think but I haven't been able to get it installed (although I haven't put a huge amount of effort into it). I am more familiar with the CDK and would prefer to stick to it if I can figure out how to use the latest version(s).
