### ISSUE TITLE
Bug in descriptor ... NeighborList.java ?

### ISSUE THREAD

**Issue by Luckick** [cdk/cdk#556]
In cdk/descriptor/qsarmolecular/src/main/java/org/openscience/cdk/geometry/surface/NeighborList.java
Line 60:
```
if (this.boxes.containsKey(key)) {
                List arl = this.boxes.get(key);
                arl.add(i);
                this.boxes.put(key, arl);
            } else {
                this.boxes.put(key, new ArrayList());
            }

```
In this circumstance, not all atoms are put into the neighbor list.

Should this be revised to: 
```
if (this.boxes.containsKey(key)) {
                List arl = this.boxes.get(key);
                arl.add(i);
                this.boxes.put(key, arl);
            } else {
            	ArrayList arl = new ArrayList();
            	arl.add(i);
                this.boxes.put(key, arl);
                // this.boxes.put(key, new ArrayList());
            }
```
?
Thanks.

**Comment by johnmay** [comment]
Yes I think so, will have to look at what this descriptor is doing but the better way to write this doing 1/2 the work and in less lines... 

```java
List arl = this.boxes.get(key);
if (list == null)
  this.boxes.put(arl, arl = new ArrayList<>());
arl.add(i);
```

Java 8 has computeIfAbsent which is the same but this is the way to do it in Java 7.

**Comment by johnmay** [comment]
Fancy making the Patch/PR?

**Comment by Luckick** [comment]
> Fancy making the Patch/PR?

How can I contribute to it? Revise and Pull request?

**Comment by johnmay** [comment]
Yes please, same way you did with the other one #533. I will get round to that this week, sorry for the delay.

**Comment by johnmay** [comment]
This was resolved https://github.com/cdk/cdk/pull/559
