### ISSUE TITLE
Incorrect Numerical Surface when read sdf file

### ISSUE THREAD

**Issue by Luckick** [cdk/cdk#561]
Hi,

I follow the steps you mentioned in https://github.com/cdk/cdk/issues/548 to read the sdf file.
However, I found that I can not get the right numerical surface. (0 radius was used for all atoms)

I tried to dive in, and I notice that for sdf files, atoms are AtomContainer2$PsuedoAtomRef, the identifier is null.
(Compare to mol2 file I read successfully, AtomContainer2$BaseAtomRef, the identifier of atoms are like C, C.2, O, etc...)
Not sure if this is the reason.

Do you have any suggestion to get the right numerical surface?
Thanks.

The sdf file is like:
4NCG_2KW_A_601
  RCSB PDB12061713523D
Coordinates from PDB:4NCG:A:601 Model:1 without hydrogens
 29 31  0  0  0  0            999 V2000
   10.9060   12.1810   15.2640   C 0  0  0  0  0  0  0  0  0  0  0  0
   10.2180   11.7640   16.3350   C 0  0  0  0  0  0  0  0  0  0  0  0
   10.2410   12.5560   14.0550   C 0  0  0  0  0  0  0  0  0  0  0  0
    8.9110   12.4570   13.9840   C 0  0  0  0  0  0  0  0  0  0  0  0
    9.7250   10.9220   22.0720   C 0  0  0  0  0  0  0  0  0  0  0  0
   10.1050   13.1030   21.1230   C 0  0  0  0  0  0  0  0  0  0  0  0
   10.0430   11.7350   20.9620   C 0  0  0  0  0  0  0  0  0  0  0  0
   10.2970   11.1600   19.7380   C 0  0  0  0  0  0  0  0  0  0  0  0
   10.6170   11.9720   18.6700   C 0  0  0  0  0  0  0  0  0  0  0  0

**Comment by johnmay** [comment]
Where did you get the SDfile from? Please attach it.

The Atom IDs are completely arbitrary in mol2 it uses the Tripos atom type but you could alway set those after.

**Comment by johnmay** [comment]
SDfile is sensitive to spaces, all the columns should line up they don't in the snippet you posted but could be a formatting error use a block of triple back tick to quote fixed spaces:

\`\`\`
stuff
\`\`\`

Will come out like this:

```
stuff
```

**Comment by Luckick** [comment]
I download from https://www.rcsb.org/structure/4ncg , Small Molecules. (I test several sdf files from PDBbank, all with same issue.)
There is a label attribute for atom when read sdf, it shows like 'C6', 'C8', 'O23', 'C24' etc, which looks contain atom info. But just not be used in surface somehow.

The sdf file:
```
4NCG_2KW_A_601
  RCSB PDB12061713523D
Coordinates from PDB:4NCG:A:601 Model:1 without hydrogens
 29 31  0  0  0  0            999 V2000
   10.9060   12.1810   15.2640   C 0  0  0  0  0  0  0  0  0  0  0  0
   10.2180   11.7640   16.3350   C 0  0  0  0  0  0  0  0  0  0  0  0
   10.2410   12.5560   14.0550   C 0  0  0  0  0  0  0  0  0  0  0  0
    8.9110   12.4570   13.9840   C 0  0  0  0  0  0  0  0  0  0  0  0
    9.7250   10.9220   22.0720   C 0  0  0  0  0  0  0  0  0  0  0  0
   10.1050   13.1030   21.1230   C 0  0  0  0  0  0  0  0  0  0  0  0
```

**Comment by johnmay** [comment]
Ah okay thanks very useful, the issue is it sets the alias of the atom below the connection table. Technically valid use of atom alias but I need to think how we could handle this better. You can delete these lines... (but we need to think of a better option).

```
A    1
C8
A    2
C7
A    3
C9
A    4
C10
A    5
C6
A    6
C5
A    7
C4
A    8
C3
A    9
C2
A   10
C1
A   11
C13
A   12
C12
A   13
C24
A   14
C18
A   15
C17
A   16
C21
A   17
C
A   18
F
A   19
N
A   20
O
A   21
CL
A   22
N11
A   23
F14
A   24
F15
A   25
O16
A   26
N19
A   27
N20
A   28
N22
A   29
O23
```

**Comment by Luckick** [comment]
Amazing, after delete those lines, it works.
Thank you.
