### ISSUE TITLE
ConformerContainer.get(index) always returns same object

### ISSUE THREAD

**Issue by kazuyaujihara** [cdk/cdk#563]
ConformerContainer.get(int i) always same object. The value of point3d just after calling get(i) is correct not after calling more. See below. The code of ConformerContainer.get(int i) is tricky and the method name may not be appropriate rather than bug.
We need to at least add a notification to the document.

```
    	// prepare container 
    	IAtomContainer[] mols = new IAtomContainer[4];
    	for (int i = 0; i < mols.length; i++) {
        	IAtomContainer mol = DefaultChemObjectBuilder.getInstance().newAtomContainer();
        	mol.setTitle("mol");
        	IAtom c = mol.getBuilder().newAtom();
        	c.setPoint3d(new Point3d(i, i, i));
    		mol.addAtom(c);
    		mols[i] = mol;
    	}
    	ConformerContainer container = new ConformerContainer(mols);

    	IAtomContainer mol1 = container.get(1);
        IAtomContainer mol3 = container.get(3);
        int i1, i3;
        i1 = container.indexOf(mol1);
        i3 = container.indexOf(mol3);
        Assert.assertEquals(1, i1); // expected 1 but was 3
        Assert.assertEquals(3, i3);
        i1 = container.lastIndexOf(mol1);
        i3 = container.lastIndexOf(mol3);
        Assert.assertEquals(1, i1); // expected 1 but was 3
        Assert.assertEquals(3, i3);
```

**Comment by johnmay** [comment]
From the code this looks, expected. It stores multiple conformers on a single molecule. The coordinates change the molecule does not. From the doc:

> A memory-efficient data structure to store conformers for a single molecule.
> Since all the conformers for a given molecule only differ in their 3D coordinates this data structure stores a single {@link IAtomContainer} containing the atom and bond  details and a List of 3D coordinate sets, each element being the set of 3D coordinates for a given conformer.

If you want to compare conformers you need to copy one of them and then compare.

**Comment by johnmay** [comment]
Okay to close?

**Comment by kazuyaujihara** [comment]
Ok. Thanks.
