### ISSUE TITLE
Reaction Based on Smarts

### ISSUE THREAD

**Issue by Flora-Feng** [cdk/cdk#566]
I am new here and I found that cdk supports reaction based on smarts. 
Is there any tutorial about it?
Here is what I was trying to do and it got wrong results.Please Help
                 // Here comes reaction smarts
		String  rsmi = "[N!H0:2].[C:3](=[O:4])[OX1H0-,OX2H1]>>[C:3]([N:2])=[O:4]";
		SmilesParser smipar = new SmilesParser(SilentChemObjectBuilder.getInstance());
		IReaction rxn = smipar.parseReactionSmiles(rsmi);
		IChemObjectBuilder bldr   = SilentChemObjectBuilder.getInstance();
		SmilesParser s1 = new SmilesParser(bldr);
		IAtomContainer reactant = s1.parseSmiles("N12C[C@H](C(CC1)CC2)N");
		IAtomContainer reactant2 = s1.parseSmiles("CCC[C@H](C)C(O)=O");
		rxn.addReactant(reactant);
		rxn.addReactant(reactant2);
		IAtomContainer oneproduct = rxn.getProducts().getAtomContainer(0);

**Comment by johnmay** [comment]
What are you trying to do, note that SMARTS != SMARTS. Reaction SMARTS is for matching not transforming, SMIRKS is for transforming - we do not support SMIRKS.

http://efficientbits.blogspot.com/2018/04/rdkit-reaction-smarts.html

**Comment by Flora-Feng** [comment]
Thanks for replying!
