### ISSUE TITLE
IteratingSDFReader skips content when empty line follows M  END before associated data

### ISSUE THREAD

**Issue by nilshoffmann** [cdk/cdk#567]
I am trying to consume a large concatenated SDF file from LipidMaps with the IteratingSDFReader. The file happens to have an empty line following the `M  END` part. 
```
M  END

> <LM_ID>
LMFA00000001
```
This leads to missing associated information in the IAtomContainer's property table.
If I remove the new line, the file parses just fine with the IteratingSDFReader. It seems that IteratingSDFReader simply skips the next content until it finds the `$$$$` record terminator.

If split and parsed individually with the MDLV2000Reader, the information is properly read with and without the empty line.

**Comment by nilshoffmann** [comment]
Tests are available in pull request #568

**Comment by johnmay** [comment]
Which program generated the SDfile? We can handle it but technically still not valid and should be fixed upstream.

**Comment by johnmay** [comment]
Here is the spec:

![image](https://user-images.githubusercontent.com/983232/58966558-662e2100-87aa-11e9-807f-a8afe7b733dc.png)

**Comment by egonw** [comment]
Since a few weeks I know the curators. I will contact them.

**Comment by nilshoffmann** [comment]
Yes, it seems LipidMaps changed their export output in other places as well. I will contact them as well, Egon.

Thanks for posting the SDF spec, that clearly shows that the new line must not occur after M  END. I fixed my version of the export locally, and that resolves the issue, as one of the test cases also demonstrates.

However, the V2000 parser still consumes the record, if I feed it to it in isolation. 
Is that parser more lenient than the iterating SDF reader, or am I erroneously assuming the two should behave similar?

**Comment by dcucsd** [comment]
Thank you for alerting us (LIPID MAPS). We generate the SDF via a PHP script. I will update the script and generate a new file. Regards, Dawn Cotter -- LIPID MAPS

**Comment by dcucsd** [comment]
We now have updated SDF files available for download at http://www.lipidmaps.org/data/structure/download.php (compressed as both .zip and .gz). I removed the blank line that followed the molfile in the previous version; removed DOS carriage returns from about 1100 records; updated the filename to use ISO 8601 international date format; added a "help" box with description of page contents; updated the list of annotations, now shown in the "help" box, to match annotations contained in the SDF file; and restyled the page to improve usability. Regards, Dawn

**Comment by egonw** [comment]
Thanks

**Comment by nilshoffmann** [comment]
Checked successfully with CDK 2.2.
Thanks a lot!
