### ISSUE TITLE
Cannot read mol file

### ISSUE THREAD

**Issue by likusta** [cdk/cdk#569]
Hello! I want to convert mol file into inchi, how can i do it in the simplest way?
I have problem with mol file reading. 

>   String filename = "C:\\Users\\-\\Desktop\\example.MOL";
>         InputStream in = new FileInputStream(filename);
>         Mol2Reader reader = new Mol2Reader(in);
>         IAtomContainer mol = (IAtomContainer) reader.read(new AtomContainer());
>         String inchi = InChIGeneratorFactory.getInstance().getInChIGenerator(mol).getInchi();
>         System.out.println(inchi);
>         reader.close();

> org.openscience.cdk.config.atomtypes.AtomTypeHandler WARN: Unrecognized hybridization in config file: tetrahedral
org.openscience.cdk.config.atomtypes.AtomTypeHandler WARN: Unrecognized hybridization in config file: octahedral
org.openscience.cdk.config.atomtypes.AtomTypeHandler WARN: Unrecognized hybridization in config file: octahedral
Exception in thread "main" java.util.NoSuchElementException
	at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
	at org.openscience.cdk.io.Mol2Reader.readMolecule(Mol2Reader.java:268)
	at org.openscience.cdk.io.Mol2Reader.read(Mol2Reader.java:151)
	at Test.method(Test.java:22)
	at Runner.main(Runner.java:8)

[molfile.txt](https://github.com/cdk/cdk/files/3257349/molfile.txt)

**Comment by johnmay** [comment]
mol2 and molfile are different things, mol2 is a tripos format with partial charges etc, molfile is a member of the MDL (originally) CTfiles. You need to use either IteratingSDFReader or MDLV2000Reader.
