### ISSUE TITLE
Highlight entire molecule

### ISSUE THREAD

**Issue by johnmay** [cdk/cdk#571]
The DepictionGenerator allows IChemObject's to be highlighted but is currently restricted to atoms/bonds. It is reasonable to allow entire molecules to be highlighted, particularly in reactions.

**Comment by egonw** [comment]
Thinking internally and talking to himself: _Oh, never actually tried that, but doesn't highlighting all atoms in a molecule do it?_

**Comment by johnmay** [comment]
It does, but just saw some code where someone was passing in an IAtomContainer so thought it's reasonable to do it.

**Comment by egonw** [comment]
Yes, saw them from your patch. Agreed, very handy indeed. I guess it also works if they now pass an `IAtomContainer` with a substructure, which is also handy.
