### ISSUE TITLE
Problem with MDLV3000Writer on a system with Locale.de_DE (Windows 10, OpenJDK8)

### ISSUE THREAD

**Issue by markussitzmann** [cdk/cdk#579]
Hi,

after a fresh clone of the CDK/master I was running the test suite. During this, some MDLV3000Writer tests failed because the molfiles were created with "," instead of "." for 3D coordinates/floating points.

After changing line 794-796 in MDLV3000Writer from

`private static final class V30LineWriter implements Closeable {
		// note: non-static
		private final DecimalFormat decimalFmt = new DecimalFormat("#.#####");`

to 

`private static final class V30LineWriter implements Closeable {
		// note: non-static
		private final DecimalFormat decimalFmt = new DecimalFormat("#.#####",
				DecimalFormatSymbols.getInstance(Locale.ROOT));`

the tests pass now but I am not sure whether this is a good solution (and I would be surprised if I'm the first one who runs into this problem ... do I miss something?)

Markus

**Comment by egonw** [comment]
It turned out to be difficult, see https://github.com/cdk/cdk/issues/507 Now looking up what solution we used in the end...

**Comment by egonw** [comment]
Oh, no, that situation we actually needed the "," on platforms that use that (German, Dutch, many more).

But here's another patch, this one similar to yours: https://github.com/cdk/cdk/commit/6d6d58fdf7eb3d2ac5970e3ad7974ec39f30350e#diff-933df31adc899e0d09707e28cde403e9

So, looking forward to your patch and pull request :)

**Comment by johnmay** [comment]
That's my bad Egon I think I forgot to add the Locale back in. As a rule of thumb you should nearly always run with ```LC_ALL=C```. Even programs like ``sort`` and ``grep`` will run faster.

**Comment by johnmay** [comment]
e.g.

```
LC_ALL=C sort myfile.txt
```

**Comment by egonw** [comment]
Problem is, I don't think people always have control over that... even scholars are frequently bound to ICT departments doing the installation of stuff :(

PS. what kind of "faster" are we talking about here? Percent points??

**Comment by johnmay** [comment]
https://www.inmotionhosting.com/support/website/ssh/speed-up-grep-searches-with-lc-all

**Comment by johnmay** [comment]
Essentially unicode is a pain :-) LC_ALL=C essentially means "I only care
about ASCII for now". Not always possible of course but good to know.

**Comment by markussitzmann** [comment]
Sorry, I am still working on my pull request (I was busy) - I found a few other places where a fix like  https://github.com/cdk/cdk/commit/ed58e009219de4d787467878884f5ad60ae52eba might be useful.
