### ISSUE TITLE
IAtomContainer to InChi and back to IAtomContainer

### ISSUE THREAD

**Issue by likusta** [cdk/cdk#583]
Hello! I got IAtomContainer from .MOL file then convert it into INchi and back to IAtomContainer. Why i got two diffrent IAtomContainers?
![FROM INCHI](https://user-images.githubusercontent.com/22011418/60975571-dba28980-a334-11e9-8ff2-7f51aab2a0e2.png)
![FROM MOL FILE](https://user-images.githubusercontent.com/22011418/60975573-dba28980-a334-11e9-80e3-643191aa3907.png)

` String fileName = "E:\\ResourcesForProjects\\ParseMolToInchi\\MolFiles\\testMOLfile.MOL";
        IAtomContainer molecule;
        MDLV2000Reader reader;
        FileInputStream in = new FileInputStream(fileName);
        reader = new MDLV2000Reader(in, IChemObjectReader.Mode.RELAXED);
        molecule = DefaultChemObjectBuilder.getInstance().newInstance(IAtomContainer.class);
        molecule = reader.read(molecule);
        System.out.println("IATOMCONTAINER_MOLFILE: " + molecule);
        String inchi = InChIGeneratorFactory.getInstance().getInChIGenerator(molecule).getInchi();
        molecule = InChIGeneratorFactory.getInstance().getInChIToStructure(inchi, SilentChemObjectBuilder.getInstance()).getAtomContainer();
        System.out.println("IATOMCONTAINER_INCHICODE" + molecule);`

[testMOLfile.txt](https://github.com/cdk/cdk/files/3377840/testMOLfile.txt)

**Comment by egonw** [comment]
Hi @likusta. This is because the InChI is not a storage format. That causes information to be lost in the process. The InChI is an identifier, not a chemical graph representation. If you want to letter, use SMILES or Chemical Markup Language, or MDL molfiles.

**Comment by likusta** [comment]
@egonw thank you for answer! May be you can answer to following questing. Why after convertation to inchi and back to IAtomContainer extra atoms and bonds were added?

**Comment by egonw** [comment]
I don't see that in the images... Can you plz elaborate?

**Comment by likusta** [comment]
First png i got after convertation InChi to IAtomContainer. In first picture we can see atoms with number 48 and 49. 
Second png i got after read .MOL file in IAtomContainer.

**Comment by egonw** [comment]
I assume those are two hydrogens. They are not extra, but just not shown in the second drawing
