### ISSUE TITLE
Molecule render

### ISSUE THREAD

**Issue by likusta** [cdk/cdk#584]
Hello! What settings i need to put to show the number of the atom and its name completely and without exception.
Right now my settings are like this:

       'AtomContainerRenderer renderer = new AtomContainerRenderer(generators, awtFontManager);
        renderer.setup(molecule, drawArea);
        RendererModel model = renderer.getRenderer2DModel();
        model.set(BasicSceneGenerator.Margin.class, (double) 0.1);
        model.set(BasicSceneGenerator.ZoomFactor.class, (double) 1.0);
        model.set(BasicSceneGenerator.Scale.class, (double) 70.0);
        model.set(BasicSceneGenerator.BondLength.class, (double) 1.5);
        model.set(BasicAtomGenerator.AtomRadius.class, (double) 40.0);
        model.set(AtomNumberGenerator.WillDrawAtomNumbers.class,true);
        model.set(HighlightGenerator.HighlightRadius.class,50.0);'
![Inchi](https://user-images.githubusercontent.com/22011418/61045866-65f5f680-a3e4-11e9-92ec-fead475bc3d9.png)
Here is statistics
atom_id::::atom_symbol:::::atom_number
1::::C::::::6 - Why in png 1 - H but here 1 - C?
2::::C::::::6
3::::C::::::6
4::::C::::::6
5::::C::::::6
6::::C::::::6
7::::F::::::9
8::::C::::::6
9::::O::::::8
10::::N::::::7
11::::C::::::6
12::::C::::::6
13::::C::::::6
14::::C::::::6
15::::C::::::6
16::::C::::::6
17::::C::::::6
18::::C::::::6
19::::C::::::6
20::::C::::::6
21::::C::::::6
22::::N::::::7
23::::C::::::6
24::::C::::::6
25::::C::::::6
26::::C::::::6
27::::C::::::6
28::::C::::::6
29::::N::::::7
30::::O::::::8
31::::C::::::6
32::::C::::::6
33::::C::::::6
34::::C::::::6
35::::C::::::6
36::::C::::::6
37::::C::::::6
38::::H::::::1
39::::H::::::1
40::::C::::::6
41::::H::::::1
42::::H::::::1
43::::H::::::1
44::::C::::::6
45::::F::::::9
46::::F::::::9
47::::F::::::9

**Comment by johnmay** [comment]
Use the depiction generator..?

```java
        IChemObjectBuilder builder = SilentChemObjectBuilder.getInstance();
        SmilesParser       smipar  = new SmilesParser(builder);
        IAtomContainer     mol     = smipar.parseSmiles("c1ccccc1N(=O)=O");
        DepictionGenerator depict  = new DepictionGenerator();
        depict.withAtomNumbers()
              .depict(mol)
              .writeTo("/tmp/tmp1.png");
        mol.getAtom(0).setProperty(StandardGenerator.ANNOTATION_LABEL,
                                   "a1");
        mol.getAtom(0).setProperty(StandardGenerator.ANNOTATION_LABEL,
                                   "a2");
        depict.withAnnotationColor(Color.BLUE)
              .depict(mol)
              .writeTo("/tmp/tmp2.png");
```

![image](https://user-images.githubusercontent.com/983232/61067184-e4f82880-a3fe-11e9-8b74-ed2fa59ae319.png)

![image](https://user-images.githubusercontent.com/983232/61067179-e0cc0b00-a3fe-11e9-8a94-2e60a4dc68e2.png)
