### ISSUE TITLE
Issues with Fingerprinting

### ISSUE THREAD

**Issue by melody0617** [cdk/cdk#587]
Hi, I am having issues for using fingerprinting. I am looping through all scenarios could have occurred by alternating the product and comparing it to the reactant. For some reason, 
![prod1](https://user-images.githubusercontent.com/53573505/62304927-f5735000-b44c-11e9-8e78-bdddee5fb0a8.png)
![reac](https://user-images.githubusercontent.com/53573505/62304928-f5735000-b44c-11e9-9e81-f8ebf6f9e4f9.png)
these two images are generating 0.8113207547169812 as its fingerprinting.
The other scenario, 
![prod0](https://user-images.githubusercontent.com/53573505/62304985-0e7c0100-b44d-11e9-822f-36d705be6249.png)
![reac](https://user-images.githubusercontent.com/53573505/62304986-0f149780-b44d-11e9-8853-92d530efed97.png) 
are also generating the same fingerprintng of 0.81132. 
Then, I tried 
![prod0](https://user-images.githubusercontent.com/53573505/62305036-22bffe00-b44d-11e9-9468-f425263dc576.png)
![prod1](https://user-images.githubusercontent.com/53573505/62305037-22bffe00-b44d-11e9-8f74-79c705ef1ff4.png) 
and I got a fingerprinting of 1, even though the structures are different. What would be the issue here? Thanks!

**Comment by johnmay** [comment]
First of there are many types of fingerprints, which type are you using?

Second what exactly is the problem you're trying to solve and why did you decide on fingerprints? - [XY Problem](http://xyproblem.info/).

Fingerprints are hash of structure features, "all the same notes but in a different order". The default [``Fingerprint``](http://cdk.github.io/cdk/latest/docs/api/index.html?org/openscience/cdk/fingerprint/Fingerprinter.html) encodes linear paths up to length 7. As a simpler example, consider the linear alcohols ``CCCCCCCCCO`` and ``CCCCCCCCCCO``, when you make a list of all paths length 1-3 you end up with:

```
O
C
OC (and CO)
CC
CCC
OCC (and CCO)
```

etc. more explanation here: [Daylight Doc](https://www.daylight.com/dayhtml/doc/theory/theory.finger.html).

You should be able to inspect the raw data with the ``getRawFingerprint``  method and see in your case the paths found are identical.

P.S. images of structures are less useful than SMILES strings.
