### ISSUE TITLE
Classes missing from cdk-smsd since 1.5.15

### ISSUE THREAD

**Issue by tdudgeon** [cdk/cdk#590]
Since version 1.5.15 (so including all 2.x releases) the cdk-smsd.jar file that is published to JCenter is missing all classes.
Yes, I know these classes are deprecated but they should still be there!

**Comment by johnmay** [comment]
Answered on mailing list but SMSD was updated externally and proved difficult to merge it back in. You should use the external library: https://github.com/asad/smsd.

Alternatively you can Include the ``cdk-legacy`` package and use the old version.
