### ISSUE TITLE
A few molecules in .MOL file

### ISSUE THREAD

**Issue by likusta** [cdk/cdk#595]
Hello!
Can you tell me please is there a simple way to split molecules in IAtomContainers if .MOL file contains several molecules? 
[1.MOL.txt](https://github.com/cdk/cdk/files/3701919/1.MOL.txt)

**Comment by steinbeck** [comment]
Check this out:

https://cdk.github.io/cdk/1.5/docs/api/org/openscience/cdk/graph/ConnectivityChecker.html

Kind regards,   Chris

— 
Prof. Dr. Christoph Steinbeck
Analytical Chemistry - Cheminformatics and Chemometrics
Friedrich-Schiller-University Jena, Germany
Phone Secretariat: +49-3641-948171
http://cheminf.uni-jena.de
http://orcid.org/0000-0001-6966-0814

What is man but that lofty spirit - that sense of enterprise.
... Kirk, "I, Mudd," stardate 4513.3..

**Comment by egonw** [comment]
@likusta, you can find a code example here: https://egonw.github.io/cdkbook/graph.html#sec:partitioning
