### ISSUE TITLE
Property isInRing dissapears in inChi format.

### ISSUE THREAD

**Issue by likusta** [cdk/cdk#598]
Hello!
I ussualy work with two data formats: .MOL files and InChi code. Sometimes i need to get isInRing property from atom. I noticed that in case of InChi code this property does not work(it always equals to False). Perhaps this is due to the fact that I do not correctly translate InChi to IAtomContainer. Please tell me what can I do to solve this problem?

Part of code where i translate InChi into IAtomContainer:
IAtomContainer molecule = InChIGeneratorFactory.getInstance().getInChIToStructure(inchi, SilentChemObjectBuilder.getInstance()).getAtomContainer();

**Comment by egonw** [comment]
Hi @likusta, as far as I know, the InChI does not explicitly encode what atoms are involved in a ring. You will have to do ring perception after parsing the InChI. Actually, you also likely want to assign some double bonds here and there, and select which tautomer you want to pick from the list of tautomers with the same InChI.

**Comment by johnmay** [comment]
In-fact no format stores which atoms are in a ring. Some formats (e.g. MOLfile) need to do ring marking when reading to sort out other properties like stereochemistry which may only be implicitly stored as coordinates. Since this property is invariant to the graph (and very cheap) you should simply recalculate it.

```
IAtomContainer mol = ...;
Cycles.markRingAtomsAndBonds(mol);
```

**Comment by johnmay** [comment]
Also you really should not use InChI to store structures it is an identifier not representation.
