### ISSUE TITLE
Aromatic amino acids from peptide sequence wrong ring structure

### ISSUE THREAD

**Issue by araskind** [cdk/cdk#612]
It looks like there is some error in the function that creates AtomContainer from the peptide sequence. (I am using CDK 2.0, so maybe this is a mute issue in later releases)

The code is as follows:
	private void drawPeptideStructure(String oneLetterSequence) {
		
		IChemObjectBuilder bldr = SilentChemObjectBuilder.getInstance();
		SmilesParser smipar = new SmilesParser(bldr);
		smilesGenerator = new SmilesGenerator(SmiFlavor.Canonical);
		DepictionGenerator dptgen = new DepictionGenerator().withAtomColors();
		IBioPolymer peptide = null;
		String smiles = null;
		try {
			peptide = ProteinBuilderTool.createProtein(oneLetterSequence);
		} catch (CDKException e) {
			e.printStackTrace();
		}
		if(peptide != null){
			try {
				AtomContainer mpep = new AtomContainer(peptide);
				AtomContainerManipulator.percieveAtomTypesAndConfigureAtoms(mpep);
				CDKHydrogenAdder.getInstance(mpep.getBuilder()).addImplicitHydrogens(mpep);
				smiles = smilesGenerator.create(mpep);
			} catch (CDKException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		if(smiles == null)
			return;
		
		structureLabel.setIcon(null);
		Depiction dpic = null;
		IAtomContainer mol = null;
		try {
			mol = smipar.parseSmiles(smiles);
		} catch (Exception e1) {
			e1.printStackTrace();
		}
		if (mol != null) {
			try {
				dpic = dptgen.depict(mol);
			}
			catch (CDKException e) {
				e.printStackTrace();
			}
		}
		if (dpic != null) {
			structureLabel.setIcon(new ImageIcon(dpic.toImg()));
			structureLabel.setHorizontalAlignment(SwingConstants.CENTER);
			structureLabel.setVerticalAlignment(SwingConstants.CENTER);
		}
	}

Using peptide sequence WFY I am getting the following SMILES:
O=C(O)C(NC(=O)C(NC(=O)C(N)CC1=CN[C]2[CH][CH][CH][CH][C]21)C[C]3[CH][CH][CH][CH][CH]3)C[C]4[CH][CH][C](O)[CH][CH]4

This SMILES string is depicted as on the picture below with aromatic wrings clearly wrong:
![image](https://user-images.githubusercontent.com/8289427/72637613-b91aaa00-392f-11ea-83ce-226e26e31b79.png)

**Comment by johnmay** [comment]
Nope still and issue will get it fixed. If you tell the SMILES generate to output lower case (aromatic) you see what the problem is....

```
Exception in thread "main" java.lang.IllegalStateException: Aromatic bond connects non-aromatic atomic atoms
	at org.openscience.cdk.smiles.CDKToBeam.toBeamEdgeLabel(CDKToBeam.java:278)
	at org.openscience.cdk.smiles.CDKToBeam.toBeamEdge(CDKToBeam.java:262)
	at org.openscience.cdk.smiles.CDKToBeam.toBeamGraph(CDKToBeam.java:145)
	at org.openscience.cdk.smiles.SmilesGenerator.create(SmilesGenerator.java:444)
	at org.openscience.cdk.smiles.SmilesGenerator.create(SmilesGenerator.java:400)
	at org.openscience.cdk.smiles.SmilesGenerator.create(SmilesGenerator.java:361)
	at org.openscience.cdk.depict.Main.main(Main.java:46)
```

I also don't like that the CDK atom type perception/hydrogen added is required. The peptide generator should return the molecule in a reasonable state.

```
    IChemObjectBuilder bldr = SilentChemObjectBuilder.getInstance();
    SmilesParser smipar = new SmilesParser(bldr);
    SmilesGenerator smilesGenerator = new SmilesGenerator(SmiFlavor.Canonical|SmiFlavor.UseAromaticSymbols);
    DepictionGenerator dptgen  = new DepictionGenerator().withAtomColors();
    IBioPolymer        peptide = null;
    String             smiles  = null;
    try {
      peptide = ProteinBuilderTool.createProtein("WFY");
      AtomContainerManipulator.percieveAtomTypesAndConfigureAtoms(peptide);
      CDKHydrogenAdder.getInstance(peptide.getBuilder())
                      .addImplicitHydrogens(peptide);
    } catch (CDKException e) {
      e.printStackTrace();
    }
    if(peptide != null){
      try {
        smiles = smilesGenerator.create(peptide);
      } catch (CDKException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
      }
    }
    if(smiles == null)
      return;
    System.err.println(smiles);
```

**Comment by johnmay** [comment]
Here's a work around if you need it... call Aromaticity perception with the CDK model.

```java
  public static void main(String[] args) throws CDKException, IOException {
    IChemObjectBuilder bldr = SilentChemObjectBuilder.getInstance();
    SmilesParser smipar = new SmilesParser(bldr);
    SmilesGenerator smilesGenerator = new SmilesGenerator(SmiFlavor.Canonical|SmiFlavor.UseAromaticSymbols);
    DepictionGenerator dptgen  = new DepictionGenerator().withAtomColors();
    Aromaticity arom = new Aromaticity(ElectronDonation.cdk(),
                                       Cycles.or(Cycles.all(), Cycles.all(6)));
    IBioPolymer        peptide = null;
    String             smiles  = null;
    try {
      peptide = ProteinBuilderTool.createProtein("WFY");
      AtomContainerManipulator.percieveAtomTypesAndConfigureAtoms(peptide);
      CDKHydrogenAdder.getInstance(peptide.getBuilder())
                      .addImplicitHydrogens(peptide);
      arom.apply(peptide);
    } catch (CDKException e) {
      e.printStackTrace();
    }
    if(peptide != null){
      try {
        smiles = smilesGenerator.create(peptide);
      } catch (CDKException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
      }
    }
    if(smiles == null)
      return;
    System.err.println(smiles);
  }
```

**Comment by egonw** [comment]
@johnmay, I very much agree that `ProteinBuilderTool.createProtein("WFY")` should do the atom typing, hydrogens, and likely also aromaticity (given the aromaticity of the side chains is pretty well defined).

**Comment by johnmay** [comment]
@egonw I think just ditch the CML and use SMILES non?

**Comment by egonw** [comment]
Yes, given the quality of your SMILES stack, I can live with this :)

**Comment by johnmay** [comment]
Just noticed the APIs should probable use IAminoAcid... (currently default.AminoAcid)

**Comment by egonw** [comment]
Agreed!

**Comment by johnmay** [comment]
> Ideally: combination of explicit double bonds locations and lower case elements to capture the aromaticity.

```
```

**Comment by egonw** [comment]
Yes, I understand that. Still, I prefer them in the template explicit.

**Comment by araskind** [comment]
The "Aromaticity" workaround seems good for now, thanks!
