### ISSUE TITLE
Exist way how to standardize molecule?

### ISSUE THREAD

**Issue by likusta** [cdk/cdk#613]
Hello!
Is in CDK a way how to standardtize molecule? (like in https://molvs.readthedocs.io/en/latest/guide/standardize.html) 
I want to use this where tautomers meet.

**Comment by johnmay** [comment]
If you want to know if two things are tautomers of each other you can calculate an InChI or use the TautomerGenerator class.

We don't provide an off the shelf standardiser like MolVS, if you need a full standardiser then [AMBIT](http://ambit.sourceforge.net/) can help there.
