### ISSUE TITLE
SubstructureFingerprints

### ISSUE THREAD

**Issue by likusta** [cdk/cdk#619]
Hello!
I'm trying to find similar molecules. For this i try to use SubstructureFingerprints. In this archive in the folder errors you will find files on which getCountFingerprint gives an error message. 
Is there any way to avoid this? Preprocessing? Additional settings?

Maybe you can give me advice on what fingerprints should I also pay attention to?
[fingerprints_cases.zip](https://github.com/cdk/cdk/files/4148441/fingerprints_cases.zip)

**Comment by johnmay** [comment]
Very few fingerprints currently support the counted option. For similarity generally the ``CircularFingerprinter`` is the best.
