### ISSUE TITLE
JPlogPDescriptor sometimes returns NaN

### ISSUE THREAD

**Issue by Jan-Mathis** [cdk/cdk#629]
With some molecules the JPlogPDescriptor returns NaN and prints a message in the form of:
 _"115201 not found"_
I assume that this number refers to the atomtype as described in [https://doi.org/10.1186/s13321-018-0316-5](https://doi.org/10.1186/s13321-018-0316-5)
I also understand that there are 13 atomtypes missing in the CDK implementation as mentioned in the conclusion of the above article. But in total I found 17 atomtypes to be missing. I will list them below with the corresponding SMILES for which the atomtype is missing
- 115210 **P1N(N=C(C=1)C)C(OCC)=O**
- 115202 **P(OCCCCCCC)=O**
- 115201 **P(OC(=O)CC)=C=C**
- 115100 **PC(N(C1=CC=CC=C1)C2=CC=CC=C2)C**
- 153202 **I(N(CN=IO)C)=NCO**
- 153201 **I(=O)C1=CC=C(C=C1)C(F)(F)F**
- 153403 **I1(OC(=O)C2=C1C(=CC(OC)=C2)C)(O)=O**
- 109102 **FC1OC(=O)CC1C#CF**
- 116503 **S(O)(O)(=O)(CC(F)(F)F)C1C(F)=CC=CC=1**
- 116500 **S(F)(F)(F)(=C(C)C)C**
- 116504 **S(S(O)(=O)=O)(O)(O)(=O)CC**
- 116502 **S(OCCCCC)(O)(CCC)(C=C)=C**
- 116501 **S(F)(F)(F)(NCCN1C(=O)C=CC1=O)=C(OC)O**
- 116604 **S(O)(O)(O)(N)(CCO)CCO**
- 116400 **S(F)(F)(F)C**
- 105200 **N2C1N=CC=CC=1B=C2C**
- 105100 **S(C1=CC=C(C=C1)B)CC**

Is there any way to prevent this, so that JPlogPDescriptor doesn't return NaN, but instead uses a different atomtype to approximate the missing one?

**Comment by johnmay** [comment]
Yes - If a molecule is currently out of scope of the model then there is not much you can do unless you update the model. In other words "how long is a piece of string?". The ALogP should be improved now so you could also try that, i'm guessing the values are missing the atom types because it was proprietary data (or derived from a proprietary model).

@plantej any comments?

**Comment by plantej** [comment]
If you want to have those atom-types included then there needs to be data for them. JPlogP is trained on consensus data obtained from a few different logP predction methods. I suspect that the other prediction methods are also unable to cope with some of those atoms, but I am unsure. If you wish I can update the training set by including compounds that contain those atom-types and retraining the model. that way it wouldn't return out of domain for those structures. If you could include at least 5 examples of those atom-types then I can predict them with the methods I used earlier and update the parameters present in CDK via a pull request. Then the applicability domain will have improved and they should no longer be OOD and return NaN.

**Comment by Jan-Mathis** [comment]
I also tried the ALogP on my molecule set and got a result for every molecule. So at least it can cope with those atom-types.
Updating the parameters in the CDK would be much appreciated. Unfortunately I wasn't able to find 5 examples for every atom-type, only for 7. But I guess 7 more atom-types are better than none. 
[Here](https://github.com/cdk/cdk/files/4621891/JPlogP_rare_atom_types_with_SMILES.txt) you'll find a text-file containing the 7 atom-types with at least 5 examples each. Thanks again for doing this.

**Comment by plantej** [comment]
Created a pull request with the retrained model.
