### ISSUE TITLE
SDF writer does not adhere to 200 character limit for data field values

### ISSUE THREAD

**Issue by baoilleach** [cdk/cdk#630]
I'm interested to know what you think is the correct behaviour if I ask the SD writer to write out a data field value that has a line containing more than 200 characters.. The docs say:

"A [Data] value can extend over multiple lines containing up to 200 characters each."

Is the max 199 or 200? I don't know. My question is really about how this should be handled by a writer. Truncated? Truncated and split over several lines (to be joined on reading?)? Handled as-is but with a warning? I do think the current behaviour needs changing (handled as-is but with no warning...I think) as it can lead to trouble with downstream tools.

**Comment by johnmay** [comment]
Hmmm, I think formerly it should split it at add the continuation, i.e. trailing +". However I think the majority of SD readers now don't use a fixed size buffer will just read in the line whatever length it is.

**Comment by baoilleach** [comment]
I should have said that I'm here after tracking down an infinite loop (?) in a third party software where I had used a superlong field value. Yes - I can tell them. Yes - I can workaround by messing with the title myself. But I still think the CDK should change its behaviour to avoid this problem for others.

**Comment by johnmay** [comment]
Hah - How big is big?

**Comment by johnmay** [comment]
Curiously I wrapped the Sgroups, I've just never touched the SDF writer :-). I did at some point want to redo the entire implementation maybe this gives me an excuse.

**Comment by baoilleach** [comment]
I guesstimate 1600 characters. So not silly big.

**Comment by johnmay** [comment]
I think part of the behaviour was it really does just mirror what ever you put in there, so the user can wrap it if needed. How do you handle this in Open Babel? Urgh I need boost now to build it

**Comment by baoilleach** [comment]
As for OB, you don't need Boost, but I don't know the answer.

**Comment by johnmay** [comment]
So changing this would make it more tricky for Open Babel.... and perhaps also RDKit. I think it's perhaps more sensible to make it a write option to wrap/not wrap. Are you generating the SDF programatically or through another program?

https://github.com/openbabel/openbabel/blob/master/src/formats/mdlformat.cpp#L1905

```
[john@hal openbabel]$ obabel /tmp/tmp.sdf -osdf
==============================
*** Open Babel Warning  in WriteMolecule
  No 2D or 3D coordinates exist. Stereochemical information will be stored using an Open Babel extension. To generate 2D or 3D coordinates instead use --gen2D or --gen3D.

 OpenBabel05132017042D

  5  5  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
  3  4  2  0  0  0  0
  4  5  1  0  0  0  0
  5  1  2  0  0  0  0
M  END
>  <MyLongField>
ThisIsAVeryLongFieldThatShouldBeWrappedThisIsAVeryLongFieldThatShouldBeWrappedThisIsAVeryLongFieldThatShouldBeWrappedThisIsAVeryLongFieldThatShouldBeWrappedThisIsAVeryLongFieldThatShouldBeWrappedThisIsAVeryLongFieldThatShouldBeWrappedThisIsAVeryLongFieldThatShouldBeWrappedThisIsAVeryLongFieldThatShouldBeWrappedThisIsAVeryLongFieldThatShouldBeWrappedThisIsAVeryLongFieldThatShouldBeWrapped

$$$$
```

**Comment by johnmay** [comment]
It's actually the RDfile I was thinking of that puts a + in the 81st column:

**Comment by johnmay** [comment]
![image](https://user-images.githubusercontent.com/983232/81837664-08b75e00-953d-11ea-9cd3-3a4ea18a3579.png)

**Comment by johnmay** [comment]
Yes there is nothing about wrapping SD data - I also checked HazELNut and there is no special handling/truncation. I'm stumped both wrapping (which can't be rejoined) and truncated seem wrong since the majority of programs will not have an issue.

**Comment by baoilleach** [comment]
You could be right. The onus is on the user to be sensible. Feel free to close.

**Comment by johnmay** [comment]
Okay - hopefully the proposed patch solves your current issue, can’t decide whether to truncate by default or not

**Comment by baoilleach** [comment]
Thanks @johnmay
