### ISSUE TITLE
MDLV2000 to SMARTS

### ISSUE THREAD

**Issue by c-ruttkies** [cdk/cdk#633]
Hi,

is there a way to to create a SMARTS string from a MOL file? I have something like:

  MJ191900                      

  7  7  1  0  0  0  0  0  0  0999 V2000
   -0.3571    0.5794    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0716    0.1669    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0716   -0.6581    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3571   -1.0705    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3573   -0.6581    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3573    0.1669    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.9093    0.7800    0.0000 L   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  6  1  0  0  0  0
  2  3  1  0  0  0  0
  3  4  1  0  0  0  0
  4  5  1  0  0  0  0
  5  6  1  0  0  0  0
  6  7  1  0  0  0  0
  7 F    2   7   8
M  ALS   7  2 F N   O   
M  END

where one atom is attached to an atom list which I would like to express as a SMARTS string i.e. C1CCCCC1[O,N]
A solution might be to create a QueryAtomContainer out of this Mol string but I haven't found a way to achieve this. Any hint is appreciated. 

Thanks,
Christoph

**Comment by johnmay** [comment]
Unfortunately we only support basic query properties at the moment - but it would just work if the MDLV2000Reader created the atom list as an Expr object.

**Comment by johnmay** [comment]
I've made some changes that make reading MDL query files better, see #638 for an example.
