### ISSUE TITLE
What molecular formula format is used

### ISSUE THREAD

**Issue by lukasz-fiszer** [cdk/cdk#635]
Hi,

We are currently working on a GSoC project with @tomas-pluskal and others at [MZmine](https://github.com/mzmine). We have to parse strings describing ions, with a possibility to specify isotopes. CDK is a dependency of MZmine and it also already has some molecular parsing methods, so that is why we are opening the issue and want to get in touch.

What is the format of molecular formula strings used in methods such as `MolecularFormulaManipulator.getMolecularFormula()` and also what is the format for specifying isotopes in such strings? We tried different options such as `(15N)5`, `[15N]5` or `[15]N5` and none of them seems to be parsed correctly by methods mentioned above.

Judging by the portions of the code from that class and the comments, I suspect it tries to parse a format along the lines of `[15]N5` but seems to be bugged. Square brackets are used both for atomic masses when specifying isotopes and also for delimiting a molecule from charge indication at the end. But the methods used when parsing the charge `MolecularFormulaManipulator.extractCharge()` and `MolecularFormulaManipulator.cleanMFfromCharge()` seem to not account for the possibility that the square brackets might be nested, eg: `[[2]H]+`, they use a loop without tracking the number of opening brackets and are just being triggered by the first closing bracket as if it was the bracket closing the molecular part of the string.

For instance the following code:
```java
IMolecularFormula mf = MolecularFormulaManipulator.getMolecularFormula("[[2]H]+", SilentChemObjectBuilder.getInstance());
```
Gives an exception:
```
java.lang.NumberFormatException: For input string: "H"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at org.openscience.cdk.tools.manipulator.MolecularFormulaManipulator.extractCharge(MolecularFormulaManipulator.java:803)
	at org.openscience.cdk.tools.manipulator.MolecularFormulaManipulator.getMolecularFormula(MolecularFormulaManipulator.java:733)
	at org.openscience.cdk.tools.manipulator.MolecularFormulaManipulator.getMolecularFormula(MolecularFormulaManipulator.java:599)
	at org.openscience.cdk.tools.manipulator.MolecularFormulaManipulator.getMolecularFormula(MolecularFormulaManipulator.java:577)
```

So we are opening the issue to confirm what is the expected format of the strings and how to specify isotopes in them and whether the methods are really bugged as we suspect. 

We could decide a format for the strings, create a CFG based on that and then make a hand-written parser or use a parser generator to parse the ionic formula strings. 

But we also wanted to have a closer look at the CDK side as it already has some parsing methods and is used by MZmine and as @tomas-pluskal suggested to get in touch and open an issue with you guys.

**Comment by johnmay** [comment]
Doesn't seem to round trip but it should be round brackets for isotopes.

```
IMolecularFormula mf = MolecularFormulaManipulator.getMolecularFormula("[(2)H]+", SilentChemObjectBuilder.getInstance());
    System.err.println(MolecularFormulaManipulator.getString(mf,false,true));
```

**Comment by johnmay** [comment]
It looks like it just removes anything in brackets - by calling simplifyMolecularFormula.... which is why it doesn't round trip. Feel free to update show only be a few lines of a patch.

**Comment by tomas-pluskal** [comment]
@lukasz-fiszer Could you fix this and submit a PR? We can use our own copy of the class until the next CDK release.

**Comment by tomas-pluskal** [comment]
@lukasz-fiszer You could also update the function so it recognizes charged formulas without brackets, like C6H13O6+ instead of [C6H13O6]+.

**Comment by johnmay** [comment]
Or both... remember the original purpose of this was round tripping rather than a general purpose formula parser. Once the branch is merged you can just use the nightly snapshot

**Comment by johnmay** [comment]
(It’s not really nightly) but I push the dev version to oosrh every so often

**Comment by johnmay** [comment]
The square brackets are there to support [{formula}]2+ but that’s still ambiguous and actually if this is getting and overhaul - supporting multipliers would be cool

**Comment by lukasz-fiszer** [comment]
Could you please clarify what is the meaning of round tripping in the context of that method? I am not entirely sure. Also @johnmay what did you mean by supporting multipliers? Notation such as `(CH2)5` seems to be already supported.

**Comment by lukasz-fiszer** [comment]
> It looks like it just removes anything in brackets - by calling simplifyMolecularFormula.... which is why it doesn't round trip. Feel free to update should only be a few lines of a patch.
@johnmay

**Comment by johnmay** [comment]
Please don't use Javacc :-) overkill for this. For round-tripping I meant make sure the syntax lines up with the method that generates a String based formula:

```
mfb := fromString(toString(mfa))
mfa == mfa
```

> Did you test that snippet above you posted? It seems to remove data both in brackets but also parentheses, as the IMolecularFormula misses any data on the isotopes.
> What is wrong with the code above?

It should not remove/ignored the isotope numbers.

> I do not see at this point how that would be just a few lines of a quick edit with the current code (unless the quick edit is just replacing brackets with parentheses in the getString methods)? Could you please give me a little more details on what changes you had in mind? Even if we introduce such quick fixes it seems like the method would still accept misformatted strings such as those with unbalanced brackets, eg: [([2)H]+ is, at least currently, accepted though the isotope data seems to be ignored.

True if you want to validate too, it's more than a few lines but still not a lot. Don't worry though I'll make the changes when I find some time.

It will be something like this Smiles parser: 
https://github.com/johnmay/beam/blob/master/core/src/main/java/uk/ac/ebi/beam/Parser.java

**Comment by johnmay** [comment]
I started writing a proper parser then I realised I actually don't quite like the syntax it accepts, for example it allows multipliers in front: ``2C2H6`` or ``(C2H6)2`` => ``C4H12`` this makes handling ``(15N)`` a little complicated... since the naive interpretation of the parser is 15xN - and it why I used square brackets when I added in isotopes.

Anyways I made some minor updates to improve the charge handling and allow elements to be inside the square brackets. This unfortunately does introduce some ambiguity where there was none before.

``[2H]2+`` => ``[[2]H2]+`` or ``[[2]H]2+``? It will interpret as the second since you can write the first less ambiguously as ``[2]H2+``. A left to right parse would choose the first - but ambiguous input is ambiguous :-).

Anyways this should handle the cases you need if you use square brackets.

**Comment by johnmay** [comment]
Closing as that change is merged in

**Comment by tomas-pluskal** [comment]
Thanks a lot, @johnmay !
