### ISSUE TITLE
INChIPlainTextFormat isn't consistent with the parser

### ISSUE THREAD

**Issue by ctapobep** [cdk/cdk#639]
INChIPlainTextFormat recognizes a string as an InChI only if it starts with INChI (notice upper-cased N). But when parsing the structure into IAtomContainer it fails to recognize such string.

Expected behaviour would probably be something like:

```java
public boolean matches(int lineNumber, String line) {
    String trimmed = struct.trim();
    return trimmed.length() > 5 && trimmed.substring(0, 5).toLowerCase().equals("inchi");
}
```
And when it gets to parsing I'd correct the case if it wasn't correct:
```java
inchi = "InChI" + inchi.substring(5);
```

Here are 2 tests that reproduce the problem. They use InChI with different letter case and they fail on different lines:

```java
    @Test public void correctCase_isNotMatchedByFormat() {
        String inchi = "InChI=1S/BF3/c2-1(3)4";
        assertEquals(4, fromInchi(inchi).getAtomCount());
        assertTrue(new INChIPlainTextFormat().matches(0, inchi));
    }
    @Test public void incorrectCase_isNotRecognizedByJniLib() {
        String inchi = "INChI=1S/BF3/c2-1(3)4";
        assertEquals(4, fromInchi(inchi).getAtomCount());
        assertTrue(new INChIPlainTextFormat().matches(0, inchi));
    }
    static IAtomContainer fromInchi(String inchi){
        try {
            InChIToStructure structure = InChIGeneratorFactory.getInstance().getInChIToStructure(
                    inchi, DefaultChemObjectBuilder.getInstance());
            INCHI_RET ret = structure.getReturnStatus();
            if (ret == INCHI_RET.WARNING) {
                System.out.println("InChI warning: " + structure.getMessage());
            } else if (ret != INCHI_RET.OKAY) {
                throw new RuntimeException("Couldn't parse InChI: " + inchi + ", details: " + structure.getMessage());
            }
            return structure.getAtomContainer();
        } catch (CDKException e) {
            throw new RuntimeException("Couldn't parse InChI: " + inchi, e);
        }
    }
```

**Comment by johnmay** [comment]
Thanks, will fix the upper case N inchi. As an aside InChI is an identifier so you shouldn't be parsing them anyways... but it should at least work even if it's wrong.

**Comment by ctapobep** [comment]
> As an aside InChI is an identifier so you shouldn't be parsing them anyways

Yeah, I've seen these statements in other issues, even went through the [presentation that you advised](http://www.hellers.com/steve/pub-talks/toronto-7-14.pdf). Can't say that I agree with this statement as for now :) Neither the presentation says anything in this regard:

> InChIs are produced by computer from structures drawn on-screen with existing structure drawing software, and **the original structure can be regenerated from an InChI** with appropriate software

**Comment by egonw** [comment]
It depends on how you define the `original structure`. The InChI normalization drops information, e.g. on the location of (some) hydrogens. You can reconstruct a set of structures of which the original is part, but that is not the same thing. I'm with @johnmay here :)

**Comment by ctapobep** [comment]
Loosing information is not unique to InChI. You loose information when transforming MOL V3000 -> MOL V2000, or MOL V2000 -> SMILES. So depending on how much information you wish to retain you'll have to choose the appropriate format. And if a chemist prefers to use SMILES or InChI to copy some simple structure into an editor - why not? Some tasks simply don't require that level of precision.

The class of structures that are not reconstructable are Hashes (Digests) and Fingerprints - like InChIKey.

**Comment by johnmay** [comment]
The official line from InChI:
> InChI is not a replacement for any existing internal structure representations. InChI is in ADDITION to what one uses internally. Its value to chemists is in FINDING and LINKING information

http://www.hellers.com/steve/pub-talks/china-2019.pdf

The main developer of the InChI code base had said it was a big mistake to allow them to be read. SMILES is no problem at all, it preserves all the information. The main issue with InChIs are there are some InChIs that can't be read back in all, less of an issue but still a problem is people complain they get the "wrong" tautomer when they read it. For example peptide bonds are the wrong way :-).

It of course depends on your needs, but converting between SMILES/MOLfile is safe since it's just coordinates (and you could store those separately), the actually connection table is maintained.

**Comment by ctapobep** [comment]
I see.. But since it looses the information - is it fair to use InChI for finding/linking? Is it because in real use cases when people search/link the lost information isn't _that_ important?

> It of course depends on your needs, but converting between SMILES/MOLfile is safe since it's just coordinates (and you could store those separately), the actually connection table is maintained.

Well, it removes the Absolute/Relative Stereo flag.. In situation when we want to differentiate racemic and enantiopure substances this will be an important piece of information.

**Comment by egonw** [comment]
I think that's the point. If you use InChI for structural representation you loose info by definition. And you cannot fix that later.
