### ISSUE TITLE
Warn when stereochemistry is ambiguous.

### ISSUE THREAD

**Issue by johnmay** [cdk/cdk#641]

**Comment by johnmay** [comment]
![image](https://user-images.githubusercontent.com/983232/84882455-2ff6d300-b087-11ea-8dc6-73c2a7aff2e5.png)

**Comment by jwleath** [comment]
Hi, I've searched the net for explanations of stereochemistry but didn't find much.  Would you provide an explanation of what conditions this feature should detect?

**Comment by johnmay** [comment]
The issue is the wedge is between two stereocentres. Normally stereochemistry is only interpreted at the narrow end of the Wedge but you can also from the wide end. We currently do both but should only do the narrow end and emit a warning.

See ST-0.5 http://publications.iupac.org/pac/2006/pdf/7810x1897.pdf
