### ISSUE TITLE
No SmilesGenerator(int) constructor or SmilesGenerator#create method

### ISSUE THREAD

**Issue by cartilage-ftw** [cdk/cdk#645]
Is the documentation on http://cdk.github.io/cdk/latest/docs/api/org/openscience/cdk/smiles/SmilesGenerator.html outdated? The constructor SmilesGenerator(int flavor) apparently doesn't exist in CDK 2.3?
When I tried implementing that in Python using JPype,
```python
smilesGenerator = cdk.smiles.SmilesGenerator(SmiFlavor.Unique)
```
I got the error:
```bash
TypeError: No matching overloads found for constructor org.openscience.cdk.smiles.SmilesGenerator(JInt), options are:
        public org.openscience.cdk.smiles.SmilesGenerator(boolean)
        public org.openscience.cdk.smiles.SmilesGenerator()
```
I checked if this was a real problem while trying it in IntelliJ and it suggested the boolean constructor with the argument being "aromaticityFlag" or something. So ```SmilesGenerator(true)``` worked for me instead
There was no create() method either, I had this error while trying to implement it in Python using JPype
```bash
AttributeError: 'org.openscience.cdk.smiles.SmilesGenerator' object has no attribute 'create'
```
I hopped on to IntelliJ and tried to write a Kotlin code. IntelliJ suggested "createSMILES()" which the documentation says, is deprecated. In fact, IntelliJ didn't show "create()" at all. So I had to use ```createSMILES()``` (and it worked).

I am using the jar from https://github.com/cdk/cdk/releases/tag/cdk-2.3

**Comment by johnmay** [comment]
No it's not out of data and yes it exists. Sounds like you have a
dependency conflict and are not using the correct version (sounds like CDK
1.4).

https://github.com/cdk/cdk/blob/master/storage/smiles/src/main/java/org/openscience/cdk/smiles/SmilesGenerator.java#L232-L234

John

**Comment by cartilage-ftw** [comment]
@johnmay Thank you for your reply. Yes, I saw that it was there in the source code. But I downloaded the cdk-2.3.jar from the releases link (https://github.com/cdk/cdk/releases/tag/cdk-2.3). Do you mind checking if there's a problem with that .jar?
I'd be surprised if that wasn't the case.

**Comment by johnmay** [comment]
```
[john@harbinger:~]% cd /tmp
[john@harbinger:/tmp]% cp ~/Downloads/cdk-2.3.jar .
[john@harbinger:/tmp]% unzip cdk-2.3.jar
[john@harbinger:/tmp]% javap org/openscience/cdk/smiles/SmilesGenerator.class 
Compiled from "SmilesGenerator.java"
public final class org.openscience.cdk.smiles.SmilesGenerator {
  public org.openscience.cdk.smiles.SmilesGenerator();
  public org.openscience.cdk.smiles.SmilesGenerator(int);
  public org.openscience.cdk.smiles.SmilesGenerator aromatic();
  public org.openscience.cdk.smiles.SmilesGenerator withAtomClasses();
  public static org.openscience.cdk.smiles.SmilesGenerator generic();
  public static org.openscience.cdk.smiles.SmilesGenerator isomeric();
  public static org.openscience.cdk.smiles.SmilesGenerator unique();
  public static org.openscience.cdk.smiles.SmilesGenerator absolute();
  public java.lang.String createSMILES(org.openscience.cdk.interfaces.IAtomContainer);
  public java.lang.String createSMILES(org.openscience.cdk.interfaces.IReaction);
  public java.lang.String create(org.openscience.cdk.interfaces.IAtomContainer) throws org.openscience.cdk.exception.CDKException;
  public java.lang.String create(org.openscience.cdk.interfaces.IAtomContainer, int[]) throws org.openscience.cdk.exception.CDKException;
  public static java.lang.String create(org.openscience.cdk.interfaces.IAtomContainer, int, int[]) throws org.openscience.cdk.exception.CDKException;
  public java.lang.String createReactionSMILES(org.openscience.cdk.interfaces.IReaction) throws org.openscience.cdk.exception.CDKException;
  public java.lang.String create(org.openscience.cdk.interfaces.IReaction) throws org.openscience.cdk.exception.CDKException;
  public java.lang.String create(org.openscience.cdk.interfaces.IReaction, int[]) throws org.openscience.cdk.exception.CDKException;
  public void setUseAromaticityFlag(boolean);
  public static java.util.Comparator<org.openscience.cdk.interfaces.IAtom> createComparator(org.openscience.cdk.interfaces.IAtomContainer, int);
}

```

**Comment by egonw** [comment]
@cartilage-ftw, in Groovy I regular have trouble with it finding methods, even if there, because it doesn't handle native variables (`int` in your case) well. I wonder if this may be the same problem with JPype? In Groovy it sometimes helps me that add an extra cast:

```
smilesGenerator = cdk.smiles.SmilesGenerator((int)SmiFlavor.Unique)
```

But I do not have experience with JPype at this moment.
