### ISSUE TITLE
Fails to build with OpenJDK 11

### ISSUE THREAD

**Issue by merkys** [cdk/cdk#660]
CDK fails to build with OpenJDK 11 on Debian sid with the following:

> org.openscience.cdk.isomorphism.<class> is not abstract and does not override abstract method test(int[]) in java.util.function.Predicate

Detailed description and logs could be found here: https://bugs.debian.org/963435

It seems that overriding `test(int[])` should be enough to fix this.

**Comment by egonw** [comment]
Hi @merkys, this should be fixed in CDK 2.4, see https://travis-ci.org/github/cdk/cdk

@johnmay, another good reason for a release :)

**Comment by merkys** [comment]
> Hi @merkys, this should be fixed in CDK 2.4, see https://travis-ci.org/github/cdk/cdk

Glad to hear this is already fixed! I will try to build from git master branch.

> @johnmay, another good reason for a release :)

Yes, please! :)

**Comment by merkys** [comment]
This issue is indeed fixed as of 1bb9a6458712452a6a25ceb147587f68ffcf2cf0. Sorry for the noise.
