### ISSUE TITLE
ConnectivityChecker.partitionIntoMolecules should copy over Sgroups

### ISSUE THREAD

**Issue by dkatzel-ncats** [cdk/cdk#669]
`ConnectivityChecker.partitionIntoMolecules()` does not copy over any Sgroups so this information is lost when working on individual partitioned containers.  This could be added in a similar way to how stereo elements are currently added. 

The simplest option would be to copy over only those Sgroups which are wholly contained in a single partitioned container.  This requires some extra bookkeeping to track atom and bonds from the original container to their new partitioned containers but isn't too bad.

I've written a prototype that seems to work which I can submit as a pull request, but wasn't sure if there should be a discussion on the best approach or if other properties should also be copied over.

Thanks!

**Comment by johnmay** [comment]
Yes please submit the PR, the tracking shouldn't be too bad but needs to be relatively efficient.

**Comment by johnmay** [comment]
In fact isn't it just identical to how the stereo elements are partitioned.

**Comment by dkatzel-ncats** [comment]
thanks for merging my PR !  is this good enough now to close?
