### ISSUE TITLE
Does not write agents into mdl rxn

### ISSUE THREAD

**Issue by dtom88** [cdk/cdk#680]
I build a reaction like this:

```java
IReaction reaction = new Reaction();
reaction.setReactants(readMolecules(reactants));
for (MdlMol mol : reagents)
    reaction.addAgent(readMolecule(mol));
reaction.setProducts(readMolecules(products));
```

then write it:

```java
        try (ByteArrayOutputStream os = new ByteArrayOutputStream()) {
            MDLRXNWriter writer = new MDLRXNWriter(os);
            writer.write(reaction);
            writer.close();
            return os.toByteArray();
        } catch (CDKException | IOException e) {
            throw new RuntimeException("Some bug");
        }
```

And do not get agents molecules in the byte[].

**version 1.5.14**

**Comment by egonw** [comment]
Is CDK 2.3 an option for you?

**Comment by johnmay** [comment]
MOL/RXNfiles do not allow agents to be written. See Page 40 - http://help.accelrysonline.com/ulm/onelab/1.0/content/ulm_pdfs/direct/reference/ctfileformats2016.pdf

> Counts line
> Line 5: The counts line specifies the number ofreactants and products. Two reactants and one product
> are indicated in line 5 of Example V3000 Rxnfile for the acylation of benzene.

Many tools choose to just extend the RXN file to support agents but officially it didn't allow this. I think there was talk of them supporting this but until I see it in the spec I would be hesitant to add to and just store the records as separate MOLfiles or use CXSMILES (with fragment grouping).

**Comment by ctapobep** [comment]
Thanks @johnmay. Yeah, we didn't realize this wasn't a part of the spec. Though all the editing tools that I've seen (not many though :)) do support reagents. Which makes it a _de facto_ standard, and when it comes to compatibility with the rest of the tools this makes the use of CDK impossible for RXN.

Anyway looks like for now we'll have to write our own version of `MDLRXNWriter`. But we'd be happy to migrate to the new version of CDK if you change your mind :)

**Comment by johnmay** [comment]
We (NextMove) license BIOVIA draw so let me check the most recent spec and will add it if it's there.

**Comment by johnmay** [comment]
Just confirmed the 2020 version of the spec does not support this. I think we can add this as an common extension though hence the patch. Just need to add some test cases and then the patch is good to go.

**Comment by johnmay** [comment]
Resolved
