### ISSUE TITLE
RDKit-style SMILES Canonicalization

### ISSUE THREAD

**Issue by contrebandeco** [cdk/cdk#684]
Hi guys,

So, I love [CDK's way of using flags to configure SMILES output](http://cdk.github.io/cdk/latest/docs/api/org/openscience/cdk/smiles/SmiFlavor.html). I wish it was the same with RDKit. Because by looking at [RDKit's doc](http://www.rdkit.org/docs/RDKit_Book.html#smiles-support-and-extensions) finding a way to make it output CDK-style canonical SMILES, I get even more confused. So is the other way around possible ? Can I make CDK output RDKit-exact canonical SMILES ?

10% of the molecules ar different. I have attached a files of all the different SMILES representations :

[cdk-vs-rdk.txt](https://github.com/cdk/cdk/files/5502350/cdk-vs-rdk.txt)

Here is my for the SmilesGenerator constructor, I use `Default | UseAromaticSymbols`.

Can anyone help me with chosing SmilesGenerator that would better mimic RDKit behavior in canonicalizing SMILES representations ? Thanks !

**Comment by johnmay** [comment]
Different toolkits have different canonical SMILES you should not use the output of one toolkit to compare with another. If you need to do that you need to re-canonicalize in one toolkit or use something like InChI. Canonicalization is basically sorting the atoms/bonds of a molecule in a unique way and it depends on the invariants you use (e.g. charge, atom maps, etc), the order they are sorted and the way these invariants are propagated.

Having said that CDK and OpenBabel can generate compatible SMILES using the InChI labelling (more info:
https://jcheminf.biomedcentral.com/articles/10.1186/1758-2946-4-22/metrics)
