### ISSUE TITLE
Ignored invalid Cis/Trans specification

### ISSUE THREAD

**Issue by contrebandeco** [cdk/cdk#685]
I'm getting a lot of "org.openscience.cdk.smiles.SmilesParser WARN: Ignored invalid Cis/Trans specification" in my error console. Please see [this file for SMILES representation and their error message pointers](https://github.com/cdk/cdk/files/5502465/cdk-invalid-cis-trans-clean.txt). I don't even see from you code where this message is coming from.

Should I ignore that ? Is there a way to turn the warning off ?

Thanks.

**Comment by johnmay** [comment]
It is within Beam. It's a side effect of SMILES using / and \ to specify double bonds. Consider this molecule:

![](https://www.simolecule.com/cdkdepict/depict/bow/svg?smi=CC%3DNC%3DCN%3DCC&abbr=on&hdisp=bridgehead&showtitle=false&zoom=1.6&annotate=none)

``CC=NC=CN=CC``

I can make it all trans...

![](https://www.simolecule.com/cdkdepict/depict/bow/svg?smi=C%2FC%3DN%2FC%3DC%2FN%3DC%2FC&abbr=on&hdisp=bridgehead&showtitle=false&zoom=1.6&annotate=cip)

```C/C=N/C=C/N=C/C```

![](https://www.simolecule.com/cdkdepict/depict/bow/svg?smi=C%2FC%3DN%2FC%3DC%2FN%3DC%2FC&abbr=on&hdisp=bridgehead&showtitle=false&zoom=1.6&annotate=cip)

Flipping one / to \ changes **two** configurations.

![](https://www.simolecule.com/cdkdepict/depict/bow/svg?smi=C%2FC%3DN%2FC%3DC%5CN%3DC%2FC&abbr=on&hdisp=bridgehead&showtitle=false&zoom=1.6&annotate=cip)

```C/C=N/C=C\N=C/C```

There is no way to 

C(=C\1/C=C\C(=[N+](\C)C)/C=C/1)(\c2ccc(N(C)C)cc2)c3ccc(N(C)C)cc3

**Comment by contrebandeco** [comment]
Wow! Thanks for the very thorough answer. I understand that this warning happens when a (unnecessarily?) redundant specification of a bond "direction" is contradictory. I'm not a chemist, please excuse my lack of vocabulary. You say the SMILES string could be "sanity" preparsed and in the case of small rings, re-written to either be non-contradictory or non-redundant ? But how are they parsed by Beam currently ? Does it ignore the second redundant (and contradictory) bond direction when it issues the warning ? Can the CDK parser be configured (in the constructor or otherwise) to not display those warning or make them part of a parsing "log" in the IAtomContainer class ?

I don't know where the SMILES representations in the dataset ([The Good Scents Company](http://www.thegoodscentscompany.com/opl/54464-57-2.html)) come from. I have a feeling it might be PubChem. I get those warnings for less than 0.01% of the SMILES in there.

**Comment by johnmay** [comment]
If there is contradiction the configuration for that db is ignored. In this case it's find because they're non-stereo anyways.

Depends on what you're trying to do with the SMILES but here is the CDK call into Beam (Graph API).

``` java
            Set<String> warnings = new HashSet<>();
            Graph g = Graph.parse(smiles, strict, warnings);
            for (String warning : warnings)
              logger.warn(warning);
```

As you can see they are logged via Log4J so you can suppress by simply setting the level. I believe you should be able to do something like this:

```
Logger.getLogger(SmilesParser.class).setLevel(Level.ERROR);
```

or configure it in properties file

```
log4j.logger.org.openscience.cdk.smiles.SmilesParser=ERROR
```

https://www.tutorialspoint.com/log4j/log4j_logging_levels.htm

**Comment by contrebandeco** [comment]
Great, that covers it, thanks !
