### ISSUE TITLE
RDKit Features that CDK Lacks ?

### ISSUE THREAD

**Issue by contrebandeco** [cdk/cdk#686]
Hello,

This is not a bug report. It's more of a wish list. RDKit is getting a lot of traction these days because big corps have decided to put their weight behind it. My hunch is that they are choosing RDKit because it has put a lot of efforts in the recent years in their Python wrappers. And you know, Python and Deep Learning. A big deal. They also have a [Java wrapper that they maintain for the KNIME platform](https://github.com/rdkit/knime-rdkit). And they have [Neo4J ](https://github.com/rdkit/neo4j-rdkit) and [Lucene ](https://github.com/rdkit/org.rdkit.lucene) toolkits, but Maven packages are nowhere to be found. Also, for the life of me, after multiple attempts, and despite their numerous Java "integrations", [I have been unable to integrate RDKit with my Java application](https://github.com/rdkit/rdkit/issues/3555). We do ML in Python here too, but all of our ETL is all in open source Java (Kafka, Hadoop, Neo4J, Lucene, Streamsets, NiFi, CoreNLP, etc.). And to me, a chemistry toolkit fits in the ETL (beginning of the pipeline) and inference (end of the pipeline) stacks, not in the offline ML training (mid-pipeline) stack of a system.

All in all, I'd rather have CDK implement some RDKit features natively in Java, rather than have yet another badly packaged JINI library. Personally, there are three things I would like to see "ported" from RDKit :

1. "RDKit-exact" SMILES canonicalization. You already have flags in your SmilesGenerator class. Could it be configured as to give the exact same canonical SMILES output as RDKit, for a given input ? I have [asked about this here already](https://github.com/cdk/cdk/issues/684) and I understand your answer, but I'm just saying that maybe interoperability could be a desirable, feasible thing to do.
2. Same as the above, but for "RDKit-exact" ML-friendly fingerprinting.
3. I'm not sure what the deal is for this one, but we have been given a set of SMILES representations to predict some properties from them. Some of the SMILES contain SMIRKS/SMARTS-style dots ("."). I think we are supposed to first "compute", somehow, the single SMILES of the reaction product molecule and it was suggested RDKit could do that. Please see [attached text](https://github.com/cdk/cdk/files/5507243/smiles-reactions.txt) for examples. I might be wrong about RDKit supporting that and those might just be invalid data, or maybe I'm supposed to separate and evaluate the molecules in the SMILES individually.

Maybe those features are already in CDK and I just don't know how to use them. Maybe this is a Beam issue (I don't know about the exact CDK-Beam separation of concern). If so, I'll make an issue there. But I'm asking, nonetheless.

And if I can be of any help, I'd be happy to contribute.

**Comment by johnmay** [comment]
Please can you repose this to the mailing list. The issue tracker is not really for this type of discussion.

https://sourceforge.net/projects/cdk/lists/cdk-user

**Comment by contrebandeco** [comment]
Will do. Thanks.

**Comment by johnmay** [comment]
I can answer (3) here though, "." is completely valid in SMILES consider Sodium Chloride ([Na+].[Cl-]). While you may want to split these up often they're together for reason for example it keeps NaCl is neutral.

If you're dealing just with SMILES the most efficient thing you can do is split on the string:

```
String smi = "[Na+].[Cl-]";
String[] parts = smi.split("\\.");
for (String part : parts) {
  smipar.parseSmiles(part);
}
```

If you have read the molecule in you need to compute the [Connected Components](https://en.wikipedia.org/wiki/Component_(graph_theory)). In CDK the class for this is [ConnectivityChecker](http://cdk.github.io/cdk/latest/docs/api/index.html?org/openscience/cdk/graph/ConnectivityChecker.html).

**Comment by contrebandeco** [comment]
Ok. Thanks. Will look into this before posting on the mailing list. Also, I will be back here if I have a further question on the "." issue.
