### ISSUE TITLE
ArrayIndexOutOfBoundsException while reading mdl mol

### ISSUE THREAD

**Issue by dtom88** [cdk/cdk#687]
When I try to read the molecule which I attached with the method below 

```	
public IAtomContainerSet read(MdlMol mol) {
        IAtomContainerSet result = new AtomContainerSet();
        try (MDLV2000Reader reader = new MDLV2000Reader()) {
            reader.setReader(new ByteArrayInputStream(mol.toBytes()));
            IAtomContainer atomContainer = new AtomContainer();
            reader.read(atomContainer);
            result.addAtomContainer(copyAndSuppressedHydrogens(atomContainer));
        } catch (Exception e) {
            e.printStackTrace();
        }
        return result;
		}
```

I get

`	java.lang.ArrayOutOfBoundsException: Index 11 out of bounds for length 11`
	
`	at org.openscience.cdk.stereo.Stereocenters.visitPart(Stereocenters.java:685)
             at org.openscience.cdk.stereo.Stereocenters.visitPart(Stereocenters.java:686)
             at org.openscience.cdk.stereo.Stereocenters.visitPart(Stereocenters.java:686)
             at org.openscience.cdk.stereo.Stereocenters.isFusedBond(Stereocenters.java:715)
             at org.openscience.cdk.stereo.Stereocenters.isBridgeHead(Stereocenters.java:737)
             at org.openscience.cdk.stereo.Stereocenters.supportedType(Stereocenters.java:530)
             at org.openscience.cdk.stereo.Stereocenters.createElements(Stereocenters.java:293)
             at org.openscience.cdk.stereo.Stereocenters.<init>(Stereocenters.java:179)
             at org.openscience.cdk.stereo.StereoElementFactory.createAll(StereoElementFactory.java:207)
             at org.openscience.cdk.io.MDLV2000Reader.readAtomContainer(MDLV2000Reader.java:526)
             at org.openscience.cdk.io.MDLV2000Reader.read(MDLV2000Reader.java:228)
             ...`

**version 2.3**
	
[MFCD00137395.txt](https://github.com/cdk/cdk/files/5560303/MFCD00137395.txt)

**Comment by johnmay** [comment]
Working okay for me... which version are you using?

BTW you should not call ``new AtomContainer()`` but use the builders, this particularly important as at some point we will be switching to [``AtomContainer2``](https://github.com/cdk/cdk/wiki/AtomContainer2) (you already get these container types if you use the builder).

```
MDLV2000Reader mdlr = new MDLV2000Reader(new StringReader("\n" +
        "  -OEChem-1108191649D\n" +
        "\n" +
        " 12 11  0     0  0  0  0  0  0999 V2000\n" +
        "   -0.6500    0.4100    0.0000 C   0  0  1  0  0  0  0  0  0  0  0  0\n" +
        "    0.8300   -0.4400    0.0000 C   0  0  3  0  0  0  0  0  0  0  0  0\n" +
        "   -2.4000   -0.2500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n" +
        "   -0.6500    2.1300    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n" +
        "    0.4500   -1.0800    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n" +
        "    2.2600   -0.5900    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n" +
        "   -2.8500   -0.9900    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n" +
        "   -1.0500    1.1800    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n" +
        "   -1.0500   -2.2600    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n" +
        "   -1.0500   -1.8700    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0\n" +
        "   -2.4000   -0.2500    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0\n" +
        "   -0.6500    2.1300    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0\n" +
        "  1  2  1  0  0  0  0\n" +
        "  1  3  1  0  0  0  0\n" +
        "  1  4  1  0  0  0  0\n" +
        "  2  5  1  0  0  0  0\n" +
        "  2  6  1  0  0  0  0\n" +
        "  3  7  1  0  0  0  0\n" +
        "  4  8  1  0  0  0  0\n" +
        "  5  9  1  0  0  0  0\n" +
        "  7  9  1  0  0  0  0\n" +
        "  8  9  1  0  0  0  0\n" +
        "  1 12  1  0  0  0  0\n" +
        "M  END\n" +
        "\t\n" +
        "\t"));
IChemObjectBuilder bldr = SilentChemObjectBuilder.getInstance();
IAtomContainer mol = mdlr.read(bldr.newAtomContainer());
System.out.println(new SmilesGenerator(SmiFlavor.Default).create(mol));
```

**Comment by johnmay** [comment]
Also you don't want, copyAndSuppressedHydrogens, you're throwing away the original anyways so just call "suppressedHydrogens".

**Comment by dtom88** [comment]
We use 2.3 version.

Checked the code that you suggested and got the same result

**Comment by johnmay** [comment]
Looks like it may have been fixed then, are you able to try with the 2.4-SNAPSHOT?

**Comment by dtom88** [comment]
You're right, it works with the 2.4-SNAPSHOT

**Comment by johnmay** [comment]
Okay will close then sorry the release hasn't been made yet, hopefully soon but the SNAPSHOT should be stable.

**Comment by dtom88** [comment]
Is it possible to release 2.4-SNAPSHOT version in the near future?

**Comment by johnmay** [comment]
Maybe but you can use it now, just add the OSSRH repo or build the JAR yourself?

**Comment by dtom88** [comment]
Ok, we'll use timestamped snapshot version, thanks
