### ISSUE TITLE
Small bug in AtomTools

### ISSUE THREAD

**Issue by h4RkhW8t53e** [cdk/cdk#691]
Coordinates generated by org.openscience.cdk.geometry.AtomTools seem to be incorrect.
A modified method AtomTools.calculate3DCoordinates3 listed below could be used. 

```java
public static Point3d calculate3DCoordinates3(Point3d aPoint, Point3d bPoint, Point3d cPoint, Point3d dPoint,
            double length) {
        Vector3d v1 = new Vector3d(aPoint);
        v1.sub(bPoint);
        Vector3d v2 = new Vector3d(aPoint);
        v2.sub(cPoint);
        Vector3d v3 = new Vector3d(aPoint);
        v3.sub(dPoint);
        Vector3d v = new Vector3d(v1); // Vector3d v = new Vector3d(bPoint);
        v.add(v2);  // v.add(cPoint);
        v.add(v3);  // v.add(dPoint);
        if (v.length() < 0.00001) {
            return null;
        }
        v.normalize();
        v.scale(length);
        Point3d point = new Point3d(aPoint);
        point.add(v);
        return point;
    }

```

**Comment by johnmay** [comment]
Thanks, as a rule of thumb stuff in CDK-MISC is not super well tested or used. This is a useful method, for example adding explicit hydrogens on to a 3D structure and giving them reasonable coordinates.

**Comment by h4RkhW8t53e** [comment]
Thank you. I am not very familiar with CDK and this was the first method I found to hydrogens. I've just noticed there is a similar method in the org.openscience.cdk.modeling.builder3d.builder3dAtomTetrahedralLigandPlacer3D.java and that one works fine. Really appreciate the work, you guys are doing, many thanks!
