### ISSUE TITLE
RDF proton descriptors fail on alanine

### ISSUE THREAD

**Issue by rajarshi** [cdk/cdk#694]
Currently looking at `RDFProtonDescriptor_GSR` which reports zero non-rotatable bonds for alanine and therefore returns no values for the protons. Added a test case along with a test structure.

This class uses a different implementation of determining rotatable bonds than the rotatable bond count descriptor (which also has an issue with alanine, see #693 )

**Comment by johnmay** [comment]
Hmm.. this looks like the RDFProtonDescriptor_* stuff is all specific to a given learnt model so it's difficult to change. We could add a config parameter, but is that useful? It's not clear to me what best course of action would be.

Playing around my self I can only get NaN out

**Comment by rajarshi** [comment]
Turns out that alanine should not have rotatable bonds as defined in the original paper, so this is actually OK.

However, the test cases do not actually test for any values. Closing this out, and will put in a seperate issue once I get some examples with computed values from the authors of the original manuscript
