### ISSUE TITLE
incomplete ExtendedFingerprinter API implementation

### ISSUE THREAD

**Issue by adalke** [cdk/cdk#699]
Short version: ExtendedFingerprinter() doesn't forward all of the IFingerprint API to its has-a Fingerprinter() instance. As a result, some metadata is reported wrong and/or cannot be changed as expected from the API.

ExtendedFingerprinter() extends Fingerprinter implements IFingerprinter. The implementation uses a has-a reference to  `private Fingerprinter fingerprinter = new Fingerprinter(size - RESERVED_BITS, searchDepth)`.

This mix of is-a and has-a results in a mixup. If ExtendedFingerprinter() gets a (for example) searchDepth=2 parameter then that is correctly passed to the new Fingerprinter "has-a".

However, it was not passed to the ExtendFingerprinter base class. Thus, ExtendedFingerprinter.getSearchDepth() returns the ExtendedFingerprinter's default searchDepth of 7, and not the self.fingerprinter search depth of 2. Similarly, getVersionDescription() returns the default ExtendedFingerprinter() string, without the parameters that were set in the constructor and passed to the has-a fingerprinter.

Do note that the functionality is correct, because getBitFingerprint() forwards to fingerprinter.getBitFingerprint() then does additional processing.

On the other hand, the configurable values of pathLimit and hashPseudoAtoms, which are part of the Fingerprint API, are not forwarded to the has-a fingerprinter.

I believe this can be resolved by 1) passing the ExtendedFingerprinter() constructor parameters to both the base class Fingerprinter() constructor and the is-a Fingerprinter instance constructor, and 2) in getBitFingerprint(), copy self's pathLimit and hashPseudoAtoms settings to the has-a self.fingerprinter before calling `fingerprinter.getBitFingerprint(container)`.

**Comment by johnmay** [comment]
Add a patch, I think that fingerprint is garbage though and barely useful.

**Comment by johnmay** [comment]
I thought it was hashing all rings up to a given size but only does SSSR, even then a better method would be to hash over all bits not some subset.

**Comment by johnmay** [comment]
Anyways patch should handle the immediate issues.
