### ISSUE TITLE
Use title as comment when writing XYZ record

### ISSUE THREAD

**Issue by adalke** [cdk/cdk#703]
The XYZWriter currently emits a blank line for the second line, which is a [comment line
](https://en.wikipedia.org/wiki/XYZ_file_format). Many tools place the title in that line.

The current code comments "FIXME: add some interesting comment", which I've done with the following diff:

```
diff --git a/storage/io/src/main/java/org/openscience/cdk/io/XYZWriter.java b/storage/io/src/main/java/org/openscience/cdk/io/XYZWriter.java
index 1fffa959c..56bd0ae27 100644
--- a/storage/io/src/main/java/org/openscience/cdk/io/XYZWriter.java
+++ b/storage/io/src/main/java/org/openscience/cdk/io/XYZWriter.java
@@ -148,7 +148,7 @@ public class XYZWriter extends DefaultChemObjectWriter {
             writer.write(s1, 0, s1.length());
             writer.write('\n');

-            String s2 = null; // FIXME: add some interesting comment
+            String s2 = mol.getTitle();
             if (s2 != null) {
                 writer.write(s2, 0, s2.length());
             }
```

This also mirrors what the XYZReader does:
```
            String line = input.readLine();
              ...
                number_of_atoms = Integer.parseInt(token);
                String info = input.readLine();
                 ...
                m.setTitle(info);
```

**Comment by johnmay** [comment]
Urgh StringTokenizer in the reader, doesn't anyone actually use XYZ

**Comment by adalke** [comment]
I haven't seen anyone needing XYZ format for over 20 years. I figure that if CDK supports it then I'll have at least basic support for it in chemfp's CDK interface.

**Comment by johnmay** [comment]
Good spot the reader already expected the title. Anyways fixed now thanks
