### ISSUE TITLE
how to use the CDKConstant ACDLABS_LABEL in terms of molecule numbering?

### ISSUE THREAD

**Issue by biotech7** [cdk/cdk#707]
Hi, team!
i'm currently using CDK depict module in order to label a series of molecules(mofile format) generated by ACDLab ChemSketch. Can it be possible to label atoms by using ChemStetch labelling 
rule(IUPAC rule) in CDK? As to CDKConstant **ACDLABS_LABEL**, is it used for labeling atom in CDK  
by numbering rule of ChemSketch?

**Comment by johnmay** [comment]
Do you have an example of the molfile you get out?

**Comment by johnmay** [comment]
Pinging @mbv31602

**Comment by mbv31602** [comment]
Hi John,  
I'll try to locate some example files, give me a day or two...
Do you need some documentation from me about the tags?  There should be a reasonable amount in the javadoc I wrote at the time, let me know if you need something more...

**Comment by johnmay** [comment]
Nah it's fine can see enough with the tests etc. Just pinged you since I knew who added it.

@biotech7 

From the molfile V2000 the ZZC field is red

```
M  ZZC   1 6
```

```
// M  ZZC aaa c...
                // 
                // c: first character of the label, extends to EOL.
                //
                // Proprietary atom labels created by ACD/Labs ChemSketch using the Manual Numbering Tool.
                // This atom property appears to be undocumented, but experimentation leads to the following
                // specification (tested with ACD/ChemSketch version 12.00 Build 29305, 25 Nov 2008)
                //
                // It's not necessary to label any/all atoms but if a label is present, the following applies:
                //
                // The atom label(s) consist of an optional prefix, a required numeric label, and optional suffix.
                //                         
                // The numeric label is an integer in the range 0 - 999 inclusive.
                // 
                // If present, the prefix and suffix can each contain 1 - 50 characters, from the set of printable 
                // ASCII characters shown here
                //                            
                //    !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~"
                //                    
                // In addition, both the prefix and suffix may contain leading and/or trailing and/or embedded 
                // whitespace, included within the limit of 50 characters. These should be preserved when read.
                //                    
                // Long labels in the mol/sdfile are not truncated or wrapped onto multiple lines. As a result, the
                // line could be 114 characters in length (excluding the newline).
                //
                // By stopping and restarting the Manual Numbering Tool, it's possible to create non-sequential
                // or even duplicate numbers or labels. This is reasonable for the intended purpose of the tool - 
                // labelling the structure as you wish. If unique labels are required, downstream processing will be
                // necessary to enforce this.
                //
```

**Comment by mbv31602** [comment]
I added code to read the appropriate ACD labels from the SD files (not in STRICT reading mode...) and apply the labels to the atoms as properties, but didn't add any other code to use the labels downstream. The labels were applied to the structures using the manual numbering tool in ChemSketch - the automatic numbering almost certainly uses the same tags.

**Comment by mbv31602** [comment]
It might be nice to be able to annotate structures in JChemPaint with these labels, but that would something for the future...

**Comment by johnmay** [comment]
To get them to display you just do this:

```java
for (IAtom atom : mol.atoms()) {
   atom.setProperty(StandardGenerator.ANNOTATION_LABEL,
                                  atom.getProperty(CDKConstants.ACDLABS_LABEL));
}
```

The slightly more portable way would be to set the comment field.

``` java
for (IAtom atom : mol.atoms()) {
   atom.setProperty(CDKConstants.COMMENT,
                                  atom.getProperty(CDKConstants.ACDLABS_LABEL));
}
// then add the "atom value" annotation
new DepictionGenerator().withAtomValues().depict(mol);
```

Just a thought be should really add these to the writer as well Mark.

**Comment by johnmay** [comment]
> JChemPaint

Not actively development any more.

**Comment by mbv31602** [comment]
You're right about the writing, I'll try to do that in the near future.  If I dimly recall, the simplest way for now would be to add the ACDLABS_LABEL to the list of properties then use the method SDFwriter(OutputStream output, Set<String> propertiesToWrite) ?

**Comment by mbv31602** [comment]
(OutputStream output, Set<String> propertiesToWrite)

**Comment by mbv31602** [comment]
(OutputStream output, Set\<String\> propertiesToWrite)

**Comment by mbv31602** [comment]
Brain not engaged!  Class, markup problems!

**Comment by biotech7** [comment]
@johnmay 
solved my issue. Highly 
appreciated！ i found it could be also replaced with **atom.getID()**. 
one more question:  in a mol file, what is the reference/meaning of the parameters arrow headed(see attach.)? how to get as well as set these paras ?
Regards!
![molfile](https://user-images.githubusercontent.com/49674341/104796669-49195b00-57f3-11eb-9524-edacf9a7b7bf.png)

**Comment by johnmay** [comment]
2D coords, x and y.

https://www.daylight.com/meetings/mug05/Kappler/ctfile.pdf (old but okay)
https://discover.3ds.com/ctfile-documentation-request-form (official but needs registration)

BTW general questions are better the mailing list (cdk-user: https://sourceforge.net/projects/cdk/lists/cdk-user)

**Comment by biotech7** [comment]
@johnmay  the doc is quite detailed and useful , solved my issue.
meanwhile, the mailing list subscribing has a bug, not accomplished.
Regards!

**Comment by johnmay** [comment]
How so? Should be standard source forge mailing list - may have been a one off glitch
