### ISSUE TITLE
Cannot pass atom symbol: CA

### ISSUE THREAD

**Issue by sandr90** [cdk/cdk#713]
I have a project that was developed using CDK 1.5 as a library (jar) and worked well.
Now I would like to migrate the CDK to the last version 2.3 and got this error:
In the line:
`atom = new PDBAtom("CA");`
I got this error:
`Cannot pass atom symbol: CA`

**Comment by johnmay** [comment]
CA is the atom type (Alpha Carbon) rather than the symbol "C"
