### ISSUE TITLE
Lambda: Unzipped size must be smaller than xxx, CDK version `1.94.1 (build 60d8f91)`

### ISSUE THREAD

**Issue by semsphy** [cdk/cdk#721]
Greeting from Cambodia,

I’m facing the problem of the limit size of lambda assets below

```
Unzipped size must be smaller than 13670630 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 1fbd37cf-4323-4e95-a46c-6624cf84c29c; Proxy: null)
```
Currently, I’m using CDK version `1.94.1 (build 60d8f91)`, I have checked the asset on s3  just `30.8 MB` in zip. If I unzip it, the assets in total is  `124 MB`. Base on the lambda quota my function it should be OK. I didn’t know why I had above error. I’m stuck the whole day. Pls Kindly give me advices to move, appreciate!

P.S: If I deployed the same function with `Serverless framework`, it works fine.

**Comment by johnmay** [comment]
That is a very old CDK version so can't help there, to minimize the size you should use Maven to build your own Java project and only include what you need.
