### ISSUE TITLE
RXN to SMILES

### ISSUE THREAD

**Issue by asad** [cdk/cdk#727]
I am trying to convert an RXN file to reaction SMILES. 
Perhaps I am not using the correct method, any pointers?

/// snippet
 
        File rxnFile = new File("rxn/rhea/13962.rxn");
        IReaction reaction = null;
        try {
            MDLRXNV2000Reader reader = new MDLRXNV2000Reader(new FileReader(rxnFile));
            reaction = reader.read(new Reaction());
            reaction.setID("13962");
        } catch (FileNotFoundException | CDKException ex) {
            Logger.getLogger(RXNRead.class.getName()).log(Level.SEVERE, null, ex);
        }

        SmilesGenerator smilesGenerator = new SmilesGenerator(SmiFlavor.Generic);
        try {
            smilesGenerator.create(reaction);
        } catch (CDKException ex) {
            Logger.getLogger(RXNRead.class.getName()).log(Level.SEVERE, null, ex);
        }

Exception in thread "main" java.lang.NullPointerException: One or more atoms had an undefined number of implicit hydrogens
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897)
	at org.openscience.cdk.smiles.CDKToBeam.toBeamAtom(CDKToBeam.java:224)
	at org.openscience.cdk.smiles.CDKToBeam.toBeamGraph(CDKToBeam.java:141)
	at org.openscience.cdk.smiles.SmilesGenerator.create(SmilesGenerator.java:446)
	at org.openscience.cdk.smiles.SmilesGenerator.create(SmilesGenerator.java:580)
	at org.openscience.cdk.smiles.SmilesGenerator.create(SmilesGenerator.java:525)

RXN file attached
[13962.rxn.zip](https://github.com/cdk/cdk/files/6442047/13962.rxn.zip)

**Comment by johnmay** [comment]
One of the molecules (CHEBI:60492) has query bonds and so it cannot set the hydrogen automatically. Query bonds should be used for queries... in this case they meant dative but we don't automatically read the MARVIN extensions to indicate this (and you can't represent the dative bond in base SMILES anyways)

```
N -1 mol_idx=8
N -1 mol_idx=8
Mg -1 mol_idx=8
```

Fundamentally you can't safely convert this to SMILES. You can either just ignore that molecule or try and set some sensible defaults. This is a bit finky as if you have query bond you need to introspect the query bond and set the order.

```
List<IAtomContainer> components = ReactionManipulator.getAllAtomContainers(reaction);
        for (IAtomContainer mol : components) {
            for (IAtom atom : mol.atoms()) {
                if (atom.getImplicitHydrogenCount() == null) {
                    System.err.println("Warning: Setting hydrogen count to 0 on " + atom.getIndex() + " of " + mol.getTitle());
                    atom.setImplicitHydrogenCount(0);
                }
            }
            for (IBond bond : mol.bonds()) {
                if (bond.getOrder() == null) {
                    bond.setOrder(IBond.Order.SINGLE);
                    if (bond instanceof IQueryBond) {
                        QueryBond qbond = (QueryBond) BondRef.deref(bond);
                        Expr expr = qbond.getExpression();
                        if (expr.type() == Expr.Type.ORDER) {
                            switch (expr.value()) {
                                case 2: bond.setOrder(IBond.Order.DOUBLE); break;
                                case 3: bond.setOrder(IBond.Order.TRIPLE); break;
                            }
                        }
                    }
                    System.err.println("Warning: Setting bond order to " + bond.getOrder() + " on " + bond.getIndex() + " on query bond of " + mol.getTitle());
                }
            }
        }
        System.out.println(new SmilesGenerator(SmiFlavor.Default).create(reaction));
```

```
NC1=NC=NC2=C1N=CN2C3OC(COP(=O)(OP(=O)(OP(=O)([O-])[O-])[O-])[O-])C(O)C3O.[H]O[H].[Mg+2].C=1/2\N/C(=C\C3=NC(=C\C=4NC(/C=C/5N=C(/C1)C(=C5CCC([O-])=O)C)=C(C4C)CCC([O-])=O)/C(=C3C)C=C)C(=C2C)C=C>>NC1=NC=NC2=C1N=CN2C3OC(COP(=O)(OP(=O)([O-])[O-])[O-])C(O)C3O.[H+].[H+].[H+].C1=2N3C(C=C4[N]5=C(C=C6N7C(=CC8=[N](C(=C1)C(=C8CCC([O-])=O)C)[Mg]573)C(=C6C)CCC([O-])=O)C(=C4C)C=C)=C(C2C)C=C.P([O-])([O-])(O)=O
```

**Comment by johnmay** [comment]
You can also inspect the SGroup data and find the dative bonds and set them that way but it doesn't solve the issue you can't safely emit these as SMILES

**Comment by johnmay** [comment]
I may add some automation to this though as the MRV tags are fairly stable

**Comment by johnmay** [comment]
Closed - query bonds in MOLfile, bad input
