### ISSUE TITLE
It will be nice to have well formated source codes.

### ISSUE THREAD

**Issue by javadev** [cdk/cdk#742]
I suggest reformating all java files with help of the maven plugin.

The command is:

```
mvn com.coveo:fmt-maven-plugin:2.9.1:format -Dstyle=aosp
```

I tested it for the repository.

**Comment by johnmay** [comment]
Yes and we do, see Java-formatter described here: https://github.com/cdk/cdk/wiki/Maven-Reporting-Plugins.

we run it every so often, the trouble is it generic reformatting often messes up some subtleties in layout. Feel free to run it with the settings file shown in that wiki and submit a PR. If things look reasonable will merge

**Comment by javadev** [comment]
Hi @johnmay,

Thank you for the quick response and link with format configuration.

My idea is to use other formatting plugin and I suggest to change eclipse configuration.

May I prepare a pull request with new maven plugin formatting?

Have a nice day!

**Comment by johnmay** [comment]
Sure, what would the change be. 

I think the big issue I had before with auto formatting was how long lines got broken. Personally I try and keep under 80 chars long but many places in CDK it’s not like that and the auto formatters reflow and rebreak in odd places

**Comment by egonw** [comment]
CDK has a history of Request for Comments (like in other projects/communities), and if I remember correctly the consensus at the time was a max length of 100 or 120 characters, balancing wishes from multiple developers. (just some history, no immediate action needed)

**Comment by egonw** [comment]
We have discussions in the past about the length (unlike I thought I remembered, but as RFC), and I think the consensus/compromise was 100 or 120 characters.

**Comment by javadev** [comment]
> Sure, what would the change be.
> 
> I think the big issue I had before with auto formatting was how long lines got broken. Personally I try and keep under 80 chars long but many places in CDK it’s not like that and the auto formatters reflow and rebreak in odd places

I prepared a pull request https://github.com/cdk/cdk/pull/743
