### ISSUE TITLE
push 2.6-SNAPSHOT to maven central snapshot?

### ISSUE THREAD

**Issue by dkatzel-ncats** [cdk/cdk#744]
There have been several commits since the 2.5 release but the maven central SNAPSHOT hasn't yet been updated with a 2.6 version.  Can a 2.6-SNAPSHOT be pushed so it can be used for testing purposes?

I can build and install the latest code myself but it makes our CI/CD pipelines simpler if these dependencies are already in maven central even as a snapshot.

thanks

**Comment by egonw** [comment]
@johnmay, shall we give it a try to set up a Google Action that automatically does this for master?

**Comment by johnmay** [comment]
Not sure if it's possible as it needs to be signed via GPG and shouldn't upload key pairs to the repo

**Comment by egonw** [comment]
Indeed, but private keys can be hidden in the settings of the GitHub repo (admin level) and the workflow (in the repo) would use environment variables to access the key.

**Comment by dkatzel-ncats** [comment]
is there any status updates on this?  I still don't think there's a 2.6-SNAPSHOT out on maven snapshot respository yet is there?

thanks

**Comment by egonw** [comment]
hi @dkatzel-ncats, I think @johnmay pushed last night. I just checked the SNAPSHOT server, and find this there: https://oss.sonatype.org/service/local/repositories/snapshots/content/org/openscience/cdk/cdk-tool/2.6-SNAPSHOT/cdk-tool-2.6-20211102.111802-1.pom

So, it seems to me the most recent push is from yesterday.

@johnmay, if you give me push rights (my sonatype account is same as github), then I can make a SNAPSHOT push each time I also push commits to SourceForge.

**Comment by johnmay** [comment]
Set it up a long time ago, let me know where to login and give access again? But yes a GH action would be best

**Comment by johnmay** [comment]
Looks like the way to do it is to have a shared username/password - if you can work out another way let me know. Can chat offline

**Comment by egonw** [comment]
@dkatzel-ncats, can you confirm your tools picked up the latest SNAPSHOT now?

**Comment by egonw** [comment]
@dkatzel-ncats, yesterday I pushed updates to the server, which you can see here: https://oss.sonatype.org/service/local/repositories/snapshots/content/org/openscience/cdk/cdk-tool/2.6-SNAPSHOT/

I will close this issue now.
