### ISSUE TITLE
mol string  convert  to smiles

### ISSUE THREAD

**Issue by miracle1111111** [cdk/cdk#762]
Thank you for such an excellent tool. How to convert string type mol to smiles?

**Comment by egonw** [comment]
Hi, please have a look at the code examples here: https://egonw.github.io/cdkbook/io.html

If that doesn't answer your question, please leave a message here again.

**Comment by miracle1111111** [comment]
sorry, the code examples&nbsp;did not find what I needed..I am sorry to need your advice！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cdk/cdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月5日(星期五) 晚上10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cdk/cdk] mol string  convert  to smiles (Issue #762)





 
Hi, please have a look at the code examples here: https://egonw.github.io/cdkbook/io.html
 
If that doesn't answer your question, please leave a message here again.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by egonw** [comment]
Okay, what are you trying to do then? What do you define as a "string type mol"?

**Comment by miracle1111111** [comment]
This is the output in the code below. I need to convert this String type of mol output into&nbsp; smiles.










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cdk/cdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月5日(星期五) 晚上11:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cdk/cdk] mol string  convert  to smiles (Issue #762)





 
Okay, what are you trying to do then? What do you define as a "string type mol"?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by egonw** [comment]
What output, what code?

**Comment by miracle1111111** [comment]
> 什么输出，什么代码？

sorry，the screenshot of the email reply is not displayed. It's the following code screenshot:
![image](https://user-images.githubusercontent.com/49110370/140541522-38c46fa1-efe1-4807-a8e3-8d948b2da4d0.png)
![image](https://user-images.githubusercontent.com/49110370/140541569-4438d606-38b2-4b08-ae56-17a85039559d.png)

**Comment by egonw** [comment]
So, what you need is a combination of these code snippets:

- https://egonw.github.io/cdkbook/code/InputFromStringReader.code.html (for the `StringReader`)
- https://egonw.github.io/cdkbook/code/InputMDLMolfiles.code.html (for the `MDLV2000Reader`)
- https://egonw.github.io/cdkbook/code/WriteSMILES.code.html (for `generator.createSMILES()`)
