### ISSUE TITLE
can cdk provide efficient functional group searching capability?

### ISSUE THREAD

**Issue by biotech7** [cdk/cdk#763]
As a synthetic researcher, I usually encounter many problems mainly related to functional groups, e.g. carboxyl,halogen,amide,Cyano etc.,which play key roles on NMR prediction, retrosynthesis planning and physichemical property prediction and so on. for example on HNMR prediction:
from target molecule B for HNMR prediction, firstly searching an indole-like fused rings(molecule A). Meanwhile, some of functional groups in fused rings 'pull' or 'push' electrons dramatically. so efficient determination the position of functional groups in target molecule B based on molecule A is very important.
can cdk provide the capability of quick  functional groups retrieving method/strategy?if not, can it be added to cdk?
![figure](https://user-images.githubusercontent.com/49674341/140649739-5db6119a-65ce-4212-9234-c67d94bfe8b1.jpg)

**Comment by johnmay** [comment]
Please contact the mailing list, there are some algorithms to find function groups (e.g. P Ertl). GitHub issues are really for for bugs not feature requests/help.

**Comment by johnmay** [comment]
https://jcheminf.biomedcentral.com/articles/10.1186/s13321-019-0361-8
