### ISSUE TITLE
cannot find whole ring mapping in findSubstructure method

### ISSUE THREAD

**Issue by biotech7** [cdk/cdk#766]
try to get a six-membered ring mapping in a molecule by implementing of findSubstructure method, but failed to get whole ring mapping. is it a bug or something else?
**codes：**
```
String smiles="COC3N=C(C)N=C(NC(=O)NS(=O)(=O)c2cc(C(=O)OCCC)c(cc2OCC(Cl)c1ccc(Cl)cc1)N(=O)=O)N3C";
String smi = "C1=NC=NCN1";
IChemObjectBuilder builder = SilentChemObjectBuilder.getInstance();
SmilesParser smipar = new SmilesParser(builder);

IAtomContainer mol = smipar.parseSmiles(smiles);
IAtomContainer ac = smipar.parseSmiles(smi);

Mappings mappings = org.openscience.cdk.isomorphism.Pattern.findSubstructure(ac).matchAll(mol);
for (int[] mapping : mappings) {
          System.out.println(mapping[0]);
      }
```

**Comment by biotech7** [comment]
Meanwhile, by using another SMARTS matcher strategy, it cannot filter other rings properly.

```
QueryAtomContainer qac = QueryAtomContainer.create(ac,
                Expr.Type.HAS_HETERO_SUBSTITUENT);
String smartString = Smarts.generate(qac);
SmartsPattern ptrn = SmartsPattern.create(smartString);
mappings = ptrn.matchAll(mol);
for (int[] mapping : mappings) {
          System.out.println(mapping[0]);
      }
```

**Comment by biotech7** [comment]
there is a fault by myself where iterating the mapping, by referring to the CDK JavaDoc, this code can shuffle all values in the mapping.
for (int[] mapping : mappings) {
            for (int i = 0; i < mapping.length; i++)
                System.out.println(mapping[i]);
        }

**Comment by johnmay** [comment]
You need to prepare the molecule for matching in this case by perceiving rings. The higher level SMARTS matcher does this automatically: http://cdk.github.io/cdk/latest/docs/api/index.html?org/openscience/cdk/smarts/SmartsPattern.html

*"The class can be used for efficiently matching many queries against a single target if setPrepare(boolean) is disabled (prepare(IAtomContainer)) should be called manually once for each molecule"*

**Comment by johnmay** [comment]
You also probably want to aromatize your inputs

**Comment by biotech7** [comment]
It seems like manually aromatizing the inputs is unnecessary. It's fully automatic other than generating Smarts strings which need to set Enums   _**Expr.Type**_ on the basis of  matching condition .

**Comment by johnmay** [comment]
In this case your query was also matching aliphatic atoms, so yes under some circumstances you can avoid. But I wrote the code and trust me you should find rings and aromatize before matching.

**Comment by biotech7** [comment]
John,  thanks!  I'll follow your advice to avoid exceptional matching.
