### ISSUE TITLE
Clean up dependencies

### ISSUE THREAD

**Issue by johnmay** [cdk/cdk#773]
A lot of modules could do with the decencies cleaning. For example I noticed cdk-io depends on cmlxom but doesn't actually use it directly (only via cdk-iocml). We may decide a some point to not use CML XOM in cdk-iocml in which case the library is now erroneously included.

We can find issues with:

```mvn dependency:analyze```

```
[INFO] --- maven-dependency-plugin:3.1.2:analyze (default-cli) @ cdk-ioformats ---
[WARNING] Unused declared dependencies found:
[WARNING]    org.blueobelisk:cmlxom:jar:3.2:test
[WARNING]    org.apache.logging.log4j:log4j-1.2-api:jar:2.15.0:test
[WARNING]    org.apache.logging.log4j:log4j-core:jar:2.15.0:test
[WARNING]    javax.vecmath:vecmath:jar:1.5.2:test
[WARNING]    xom:xom:jar:1.3.7:test
[WARNING]    xpp3:xpp3:jar:1.1.4c:test
[WARNING]    org.openscience.cdk:cdk-core:jar:2.6-SNAPSHOT:test
[WARNING]    org.openscience.cdk:cdk-standard:jar:2.6-SNAPSHOT:test
[WARNING]    org.openscience.cdk:cdk-data:jar:2.6-SNAPSHOT:test
[WARNING]    org.openscience.cdk:cdk-testdata:test-jar:tests:2.6-SNAPSHOT:test
```

It will not fix them automatically. Note that some dependencies may be loaded at runtime (e.g. cdk-data) so it's not a quick fix as just remove them all.

**Comment by egonw** [comment]
oh, cool! didn't know about `mvn dependency:analyze` :)

**Comment by johnmay** [comment]
Done
