### ISSUE TITLE
Release 2.6.1 ? 

### ISSUE THREAD

**Issue by sneumann** [cdk/cdk#775]
Which includes https://github.com/cdk/cdk/commit/a847162329527e3f892403ab59d783d120f4bb9f
Yours, Steffen

**Comment by johnmay** [comment]
Possibly - It's not AS major issue as pre 2.16.0. Note under normal usage we don't include the Log4J core for logging (only if you pulling in cdk-log4j - and also cdk-inchi)

**Comment by javadev** [comment]
2.17.0 was released btw.

**Comment by egonw** [comment]
The `2.7-SNAPSHOT` already is depending on 2.17.0.

**Comment by javadev** [comment]
2.17.1 is out

**Comment by egonw** [comment]
Patch committed, SNAPSHOT being deployed.

**Comment by johnmay** [comment]
2.7 is release major package rearrangements as well + JNA Inchi.
