### ISSUE TITLE
Unable to build package

### ISSUE THREAD

**Issue by jaindipak21** [cdk/cdk#793]
I tried building the package via the mvn install command in windows 10 however I get the following error
BUIL D FAILURE 
Plugin org.apache.maven.plugins:maven-install-plugin:2.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-install-plugin:jar:2.4: Could not transfer artifact org.apache.maven.plugins:maven-install-plugin:pom:2.4 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [ebi-repo (http://www.ebi.ac.uk/~maven/m2repo, default, releases)] -> [Help 1]

This is the same if i try using Eclipse 
Could anyone please assist

**Comment by johnmay** [comment]
Recent versions of maven need to use https. We should update the EBI repo address - note this looks like it’s specific to eclipse trying to download everything (cdk-build-util) IntelliJ nor command line usage does this

**Comment by johnmay** [comment]
Please try pulling in the latest version of master, I have update the EBI repo to use HTTPS
