### ISSUE TITLE
Any log4j vulnerability using CDK in a web application?

### ISSUE THREAD

**Issue by kpaulfriedman** [cdk/cdk#794]
Apologies for this naive question, not sure how to ask this as it is not really an "issue" so much as a question. Has anyone scanned CDK for possible log4j vulnerability in the event it was run in a web-accessible application? Thank you for your help.

**Comment by egonw** [comment]
Yes, we have and, importantly, log4j is supported and a build dependency but not a runtime dependency (unless you specifically include the log4j functionality), which means that many CDK applications do not include log4j in the first place. The CDK is a library and not a web-accessible application. People using the CDK in web services of some kind, should check if they introduce a runtime dependency.

**Comment by johnmay** [comment]
Note 2.7 is not available on maven central and used log4j 2.17.1 if needed
