### ISSUE TITLE
Source of `NCI_feb03_2D.mol2.gz`

### ISSUE THREAD

**Issue by merkys** [cdk/cdk#800]
Just to be sure: Am I right to think that `NCI_feb03_2D.mol2.gz` is the NCI Open Database of Compounds, as downloadable from [here](https://cactus.nci.nih.gov/download/nci/index.html)? I am a bit confused as I cannot find this particular file (February 2003 release) in their downloads page, but they might be removing old releases from it.

**Comment by johnmay** [comment]
I have no idea :-). Was this one I removed recently when I refactored test data?

**Comment by johnmay** [comment]
It might be possible to do a git blame and follow back the history and there may more info in the commit log.

**Comment by merkys** [comment]
> I have no idea :-). Was this one I removed recently when I refactored test data?

No, it is still there, at `storage/io/src/test/resources/org/openscience/cdk/io/NCI_feb03_2D.mol2.gz`.

> It might be possible to do a git blame and follow back the history and there may more info in the commit log.

Good idea. The file seems to be introduced at 9e0b97d948248192b7e890d4bb7de40351bd1ef1, but the commit message does not say anything about its source. Commit's author is **sithmein**, but they probably are not on GitHub (or I cannot locate them).

**Comment by egonw** [comment]
@merkys, you can email `$SFUSERNAME@users.sf.net` or ask via the `cdk-devel@` mailing list, perhaps?

**Comment by merkys** [comment]
@egonw, thanks for the hint. I will contact them.
