### ISSUE TITLE
average and monoisotopic masses and atoms exact/average mass values used in calculation

### ISSUE THREAD

**Issue by fgiacomoni** [cdk/cdk#803]
Dear CDK support,
My team develops an information system used in metabolomics. We have features to automatically calculate mass properties for each added chemical compound. But in the future, we want to perform these calculations with reference and academic packages. So, to make any changes, we are in a benchmarking phase and I have several questions regarding your package:
+ What is the difference between the "exact mass" provided by CDK and the "monoisotopic mass" currently used in metabolomics?
+ What are the exact mass values for each atom used in the calculation of the "exact mass" by CDK?
+ What are the average mass values for each atom used in the calculation of the "average mass" by CDK?

We did several initial tests with your software on a dataset of extracted from the ChEBI database and found a difference between the average mass calculated with CDK and the average mass provided (and calculated) by ChEBI.
Examples: 
`
CHEBI:90 - 
MASS_AVG_CHEBI: 290.26810
MASS_AVG_CDK: 290.268638570797`

`CHEBI:3242 - 
MASS_AVG_CHEBI: 327.46050
MASS_AVG_CDK: 327.46124875567`

Thank you very much in advance,

**Comment by johnmay** [comment]
We use the BODR for mass it may be out of sync with IUPAC latest numbers or it could be floating point round errors.

```
[H][C@@]1(Oc2cc(O)cc(O)c2C[C@H]1O)c1ccc(O)c(O)c1 CHEBI:90
Avg:290.2686385707974
Avg(2):290.2686385707974
Mono:290.079038168
MAMW:290.079038168
Oc1ccc2C[C@H]3N(CC[C@@]4(CCCC[C@@]34O)c2c1)CC1CCC1 CHEBI:3242
Avg:327.4612487556706
Avg(2):327.4612487556706
Mono:327.21982916800005
MAMW:327.21982916800005
```

You probably want MAMW for mass spec. For CHEBI:3242 PubChem report MW as 327.5 and KEGG 327.4605 (probably where ChEBI got it from), ChEMBL as "327.47".


```java
SmilesParser smipar = new SmilesParser(SilentChemObjectBuilder.getInstance());
for (String smi : Arrays.asList("[H][C@@]1(Oc2cc(O)cc(O)c2C[C@H]1O)c1ccc(O)c(O)c1 CHEBI:90",
        "Oc1ccc2C[C@H]3N(CC[C@@]4(CCCC[C@@]34O)c2c1)CC1CCC1 CHEBI:3242")) {
    IAtomContainer mol = smipar.parseSmiles(smi);
    System.err.println(smi);
    System.err.println("Avg:" + AtomContainerManipulator.getMass(mol, AtomContainerManipulator.MolWeight));
    System.err.println("Avg(2):" + AtomContainerManipulator.getMass(mol, AtomContainerManipulator.MolWeightIgnoreSpecified));
    System.err.println("Mono:" + AtomContainerManipulator.getMass(mol, AtomContainerManipulator.MonoIsotopic));
    System.err.println("MAMW:" + AtomContainerManipulator.getMass(mol, AtomContainerManipulator.MostAbundant));
}
```

**Comment by johnmay** [comment]
Using https://iupac.qmul.ac.uk/AtWt/
```
C21H29NO2
21*12.011 + 29*1.008 + 14.007 + 15.999
```
I get 
```
311.469
```

**Comment by fgiacomoni** [comment]
Thank you for your quick and clear reply. We had based our monoisotopic mass calculation on Standard Atomic Weights 2020 published by the CIAAW (Commission on Isotopic Abundances and Atomic Weights) - https://www.ciaaw.org/atomic-weights.htm

**Comment by johnmay** [comment]
Something we could (should) do is have the lower/upper bounds

**Comment by johnmay** [comment]
based on your data I get a lower/upper bound:
```
21*12.0096 + 29*1.00784 + 14.00643 + 2*15.99903 = 327.43345
21*12.0116 + 29*1.00811 + 14.00728 + 2*15.99977 = 327.48561
```

**Comment by johnmay** [comment]
I am not sure how ChEBI got their MW - since it is less than the lower bound :/
