### ISSUE TITLE
Integration of ErtlFunctionalGroupsFinder and Sugar Removal Utility into CDK

### ISSUE THREAD

**Issue by JonasSchaub** [cdk/cdk#854]
Dear CDK-developers,

I have been involved in two projects that might be interesting for integration into the CDK. I have spoken with Egon about them last week and I will give all necessary details for everyone below: 

The first one is the ErtlFunctionalGroupsFinder, an open, CDK-based implementation of [Peter Ertl's algorithm for functional group detection](https://doi.org/10.1186/s13321-017-0225-z). Our implementation is described in [this paper](https://doi.org/10.1186/s13321-019-0361-8) and the source code can be found [here](https://github.com/zielesny/ErtlFunctionalGroupsFinder). 
Getting it into CDK would require integrating one principal class implementing the functionality, a corresponding test class (these two can be found [here](https://github.com/zielesny/ErtlFunctionalGroupsFinder/tree/master/Basic)), and (if you agree) a utility class with some convenient routines for pre-and postprocessing in a workflow using ErtlFunctionalGroupsFinder. The utility class along with its test class can be found [here](https://github.com/zielesny/ErtlFunctionalGroupsFinder/tree/master/Utility). 

The second project is named Sugar Removal Utility, an open, CDK-based implementation of an algorithm for _in silico_ deglycosylation. We have described the algorithm and its implementation in [this paper](https://doi.org/10.1186/s13321-020-00467-y) and used it for the project described [here](https://doi.org/10.3390/biom11040486) that illustrates its possibilities and configurations in more detail. The source code can be found [here](https://github.com/JonasSchaub/SugarRemoval). 
As far as we know, there is no deglycosylation functionality in CDK, only a CDK-based KNIME node for this purpose. 
The Sugar Removal Utility consists of one principal class implementing the functionality and a corresponding test class. In the latter, a few test methods would have to be removed that illustrate the deglycosylation results on a small test data set and test the surrounding command-line application. 

Do you think these two projects should be integrated into the CDK? Should I create two pull request where we can work on the details?
One important question I have would be into which module to put my classes. Ideally, there would be one that fits thematically and supports the modules I need for my code. Otherwise, we could maybe also add one or two new modules.

The Sugar Removal Utility needs the following modules:
- cdk-interfaces
- cdk-standard
- cdk-core
- cdk-isomorphism
- cdk-smarts
- cdk-smiles
- cdk-valencycheck
- cdk-data (test scope)

ErtlFunctionalGroupsFinder requires these modules:
- cdk-core
- cdk-interfaces
- cdk-hash
- cdk-smiles
- cdk-standard
- cdk-isomorphism (test scope)
- cdk-data (test scope)

I would be happy to give more details on specific aspects of the two projects or discuss any required code changes.

Kind regards,
Jonas Schaub

**Comment by JonasSchaub** [comment]
Hi @egonw 

no worries, I am also looking forward to that blog post about our meeting!

On the subject at hand: I guess it would be best if I simply create one or two separate new modules for the two functionalities to freely manage the dependencies. Would you agree? If yes, would you have name suggestions/preferences?

And what should be the target branch of the pull request?

But I also have to note that I probably will not have much time to work on this in the coming weeks, unfortunately. 

Kind regards,
Jonas

**Comment by johnmay** [comment]
Sounds good, hard to decide where they would go. FuncGroups is sort a descriptor and SugarRemoval is sort of a standardisation (which we don't have a module for).

**Comment by JonasSchaub** [comment]
Hi @johnmay 

I would propose to create a "standardisation" module, then. We are planning to implement further standardisation routines with/for CDK anyway in our group.

**Comment by JonasSchaub** [comment]
Hi @egonw and @johnmay ,
picking this up after some time: if you both still agree that both functionalities would be beneficial for CDK to integrate, I would start two pull requests. What I need to know for this is which branch to target in the CDK repo and into which module to integrate my code. Should I put the ErtlFunctionalGroupsFinder into the descriptor module and start a new "standardisation" module for the Sugar Removal Utility?

For your consideration, here are the (updated) repositories:

- https://github.com/JonasSchaub/ErtlFunctionalGroupsFinder
- https://github.com/JonasSchaub/SugarRemoval

The CDK integration would in both cases consist of one principal class implementing the functionality and one corresponding test class, respectively.

**Comment by johnmay** [comment]
I would try and avoid adding a new module, if anything I would like to try and simplify/collapse the number modules.

- Possibly ErtlFunctionalGroupFinder in **cdk-fragment** but need to check the output. Also I would probably drop the "Ertl" in the naming, but should of course be cited in the documentation.
- SugarRemoval possibly in **cdk-extra** for now, cdk-standardise isn't a terrible idea but there needs to be a lot more functionality to add that. We already have some single class modules like IONPOT and PDBCML for example and it's bad design IMO.

Quite busy these days but I will try and find time within the next week to take a close a look. At first glance the ErtlFunctionalGroupFinder looks more complicated/verbose than I imagined, there are lots of public helper functions (``isCharged()`` for example) which should be private/package-private so they are not leaked in the JavaDoc.  I need to reread/remember how it works but at first pass this looks more complicated than I thought. For comparison the RDKit one is 80 lines: https://github.com/rdkit/rdkit/blob/master/Contrib/IFG/ifg.py
