### ISSUE TITLE
Is there any demonstration Code for Conditions Abbreviations or Terminal Group Abbreviations?

### ISSUE THREAD

**Issue by CreamyLong** [cdk/cdk#858]
Hi, I am using DepictionGenerator class and I have looked at the Abbr method. How can I combine them to get a reaction like this
![image](https://user-images.githubusercontent.com/45339996/164981154-b5867bf7-b584-447b-b1b5-de2450adf6b3.png)
not this
![image](https://user-images.githubusercontent.com/45339996/164981176-54c657ec-3660-4375-8a59-0fabe6045de0.png)

**Comment by johnmay** [comment]
Sorry I don't understand. You call one and then you call the other one?

Pseudo code:

```
void doDepiction(IAtomContainer mol) => {
   abbr.apply(mol);
   depictGen.generate(mol):
}
```

**Comment by johnmay** [comment]
Here is the code in CDK Depict, reaction you call it one each molecule (or just the agents - "conditions"):

https://github.com/cdk/depict/blob/master/cdkdepict-lib/src/main/java/org/openscience/cdk/app/DepictController.java#L306-L342

https://github.com/cdk/depict/blob/master/cdkdepict-lib/src/main/java/org/openscience/cdk/app/DepictController.java#L782-L826

**Comment by CreamyLong** [comment]
thx！
