### ISSUE TITLE
cdk.smarts.Smarts$Parser in CDK2.7.1 throws Error

### ISSUE THREAD

**Issue by Le0nT1** [cdk/cdk#859]
Dear developer team,
Thank you for the great tool but I got some problems when I tried to use the SmartsParser. The cdk toolkit I use is 2.7.1.
The code I tested is:

```java
String smarts = "O[C@?H](C)CC";
Pattern smp2 = SmartsPattern.create(smarts);
```

Then it threw error messages when executing the SmartsPattern.create(smarts):

```
Exception in thread "main" java.lang.InstantiationError: org.openscience.cdk.isomorphism.matchers.QueryAtom
	at org.openscience.cdk.smarts.Smarts$Parser.append(Smarts.java:1829)
	at org.openscience.cdk.smarts.Smarts$Parser.parse(Smarts.java:1883)
	at org.openscience.cdk.smarts.Smarts.parse(Smarts.java:2198)
	at org.openscience.cdk.smarts.Smarts.parse(Smarts.java:2217)
	at org.openscience.cdk.smarts.SmartsPattern.<init>(SmartsPattern.java:99)
	at org.openscience.cdk.smarts.SmartsPattern.create(SmartsPattern.java:190)
```

However, the org.openscience.cdk.smiles.smarts.SmartsPattern is still working well. 

Thanks,

**Comment by johnmay** [comment]
Can you open an issue on GitHub and use the code block to format the code. Thanks

- John

**Comment by egonw** [comment]
> Can you open an issue on GitHub

@johnmay, it already is. Otherwise I am not sure what you meant.

**Comment by johnmay** [comment]
Sorry only saw it via email and it messed up the formatting. Presumed it was mailing list :-)

**Comment by johnmay** [comment]
I do not get any errors, do you have a dependency/version conflict.

```java
public class Main {
    public static void main(String[] args) throws CDKException, IOException {
        SmilesParser sp = new SmilesParser(SilentChemObjectBuilder.getInstance());
        String smarts = "O[C@?H](C)CC";
        Pattern smp2 = SmartsPattern.create(smarts);
        for (String smi : new String[]{"O[C@H](C)CC", "O[C@@H](C)CC", "O[CH](C)CC"}) {
            if (smp2.matches(sp.parseSmiles(smi))) {
                System.err.println("HIT: " + smi);
            } else {
                System.err.println("MISS:" + smi);
            }
        }
    }
}
```

HIT: O[C@H](C)CC
MISS:O[C@@H](C)CC
HIT: O[CH](C)CC

**Comment by vedina** [comment]
> I ran the maven clean and cleaned my project and still got this error. Can you please guide how to figure out if this is a dependency/version conflict? The only cdk-bundle I am using is 2.7.1. I am also using ambit and not sure if this could be the reason. Relevant information in pom file is below: org.openscience.cdk cdk-bundle 2.7.1 ambit ambit2-smarts 4.0.0-SNAPSHOT
> 
> Thanks

just in case ambit-4.0.0 uses cdk 2.11 , and if used via maven cdk will be pulled as transitive dependency

**Comment by vedina** [comment]
> With maven you should not be using bundle but pull in what you need. You can use dependency:tree to check the versions that maven resolved. Almost guaranteed you have a conflict coming in via ambit. - John

Yes, most likely

**Comment by Le0nT1** [comment]
Yes, It is caused by conflicts from other use library jar files.
I removed the jar files with other versions of CDK and the problem is solved.
Thank you for the help.

**Comment by johnmay** [comment]
Use dependency management to specify the version of libs to use or use the cdk version ambit uses. Which a minimal pom config like that you’ll get a mishmash of 2.1.1 and 2.7.1 which of course won’t work. APIs should be backwards compatible but mixing like that is not going work.

**Comment by Le0nT1** [comment]
> 

It's caused by some manually imported library in the /lib folder and the java build path. It's a tool developed years ago and couldn't be imported using maven. CDK2.7.1 can work well with amit since cdk2.1.1 is omitted for conflicts in the depencyManagement. Thank you for the advice again.
