### ISSUE TITLE
Exception in LoggingTool

### ISSUE THREAD

**Issue by uli-f** [cdk/cdk#873]
I get an exception in org.openscience.cdk.tools.LoggingTool.

The exception occurs in line [177 in CDK version 271](https://github.com/cdk/cdk/blob/8d5821f29d4d254d23a8aebe5635478fc0e994ae/misc/log4j/src/main/java/org/openscience/cdk/tools/LoggingTool.java#L177):

Configurator.setLevel(log4jLogger.getName(), Level.WARN);

java.lang.ClassCastException: class org.apache.logging.slf4j.SLF4JLoggerContext cannot be cast to class org.apache.logging.log4j.core.LoggerContext (org.apache.logging.slf4j.SLF4JLoggerContext and org.apache.logging.log4j.core.LoggerContext are in unnamed module of loader 'app')

Here is some debugging output from log4j2, the message from CDK written to stderr and the first (of many) lines that are written to the log by CDK:

```
DEBUG StatusLogger org.slf4j.helpers.Log4jLoggerFactory is not on classpath. Good!
DEBUG StatusLogger Using ShutdownCallbackRegistry class org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry
WARN StatusLogger Multiple logging implementations found: 
Factory: org.apache.logging.log4j.core.impl.Log4jContextFactory, Weighting: 10
Factory: org.apache.logging.slf4j.SLF4JLoggerContextFactory, Weighting: 15
Using factory: org.apache.logging.slf4j.SLF4JLoggerContextFactory
DEBUG StatusLogger Took 0.124734 seconds to load 250 plugins from jdk.internal.loader.ClassLoaders$AppClassLoader@73d16e93
DEBUG StatusLogger PluginManager 'Lookup' found 16 plugins
DEBUG StatusLogger AsyncLogger.ThreadNameStrategy=UNCACHED (user specified null, default is UNCACHED)
TRACE StatusLogger Using default SystemClock for timestamps.
DEBUG StatusLogger org.apache.logging.log4j.core.util.SystemClock supports precise timestamps.
Could not read the System property used to determine if logging should be turned on. So continuing without logging.
Could not read the System property used to determine if logging should be turned on. So continuing without logging.
12:38:28.096 [Test worker] DEBUG org.openscience.cdk.DynamicFactory - registered 'IAtom' with 'Atom' implementation
```

The exception results in the logging level for the loggers used by all CDK classes not being configured correctly by the if/else clause that calls Configurator.setLevel (lines 174-178 in LoggingTool) which leaves the logging level at its default value.

Unfortunately, in case of running tests with gradle this default value for the logging level seems to be DEBUG when running tests and clutters the output to the extent of making it unreadable.

My application uses Spring Boot which results in the following logging libraries to be on the classpath:

ch.qos.logback:logback-classic:1.2.11
ch.qos.logback:logback-core:1.2.11
org.apache.logging.log4j:log4j-api:2.17.2
org.apache.logging.log4j:log4j-core:2.17.2
org.apache.logging.log4j:log4j-to-slf4j:2.17.2
org.apache.logging.log4j:log4j-1.2-api:2.17.2
org.slf4j:slf4j-api:1.7.36
org.slf4j:jul-to-slf4j:1.7.36
commons-logging:commons-logging:1.2
org.jboss.logging:jboss-logging:3.4.1.Final -> 3.4.3.Final

These different logging libraries are pulled in by various dependencies as transitive dependencies.

Any help is appreciated, in particular:

1) Is there a way to fix the ClassCastException?
2) Where is the logging level DEBUG set that the LoggingTool defaults to?
3) A helpful workaround for me would be to change the logging level of the LoggingTool. How can I do this?

**Comment by uli-f** [comment]
I made some progress on this.

Excluding the log4j-to-slf4j dependency resolves the ClassCastException:

`exclude group: 'org.apache.logging.log4j', module: 'log4j-to-slf4j'` (in gradle notation)

### Further thoughts

SLF4J is a general logging facade that allows to plug in particular logging implementations at runtime. This only works reliably if the actual logging calls are made against the SLF4J API. Thus, replacing the dependency on log4j2 with SLF4J would allow the user to select the logging implementation by adding the dependency of choice instead of enforcing the logging framework to be log4j.

cdk-log4j also has a dependency on log4j-core which in my understanding prevents the use of the log4j to slf4j bridge as implemented by log4j-to-slf4j.

There are four classes of the log4j-core dependency that are used in LoggingTool:

1. `org.apache.logging.log4j.core.LoggerContext;`
2. `org.apache.logging.log4j.core.config.ConfigurationSource;`
3. `org.apache.logging.log4j.core.config.Configurator;`
4. `org.apache.logging.log4j.core.config.xml.XmlConfiguration;`

At first glance, it looks like the functionality currently implemented by calls to these class cannot be retained when switching over to the SLF4J API.

I would question the functionality these classes provide to the CDK, though; as a library, CDK might be most useful in terms of logging if it provides the flexibility to the user of the library to choose her/his own logging implementation and leave any configuration tasks on the user's side as there are well-established mechanisms on how to adjust the logging within the user's framework (i.e., by using xml, yaml, properties, ... configuration files).

**Comment by egonw** [comment]
`org.slf4j` has been annoying me a lot lately. The idea in the CDK is simple:

1. have a CDK-level API
2. users choose a sink, and the CDK-level API posts the logging to that sink

Now, Log4j and Slf4j in their wisdom decided add another layer to this: Log4j has become another route, so we now have CDK->Log4j->Something. But that Something always seems to have to be `org.slf4j'. The list of jars you have are a good example of the Log4j/Slf4j mess. (I have similar chaos in Bacting...)

The CDK currently has two sinks and a STDOUT backup: Log4j and whatever Bioclipse/Eclipse was using (need to look up that code, which should be somewhere in the Bioclipse code base).

> Is there a way to fix the ClassCastException?

Honestly, not really sure. Currently, I would argue that if you want to use Slf4j, we should write an `ILoggingTool` implementation for Slf4j instead.

> Where is the logging level DEBUG set that the LoggingTool defaults to?

Cannot quickly find it, but I think WARN.

> A helpful workaround for me would be to change the logging level of the LoggingTool. How can I do this?

`setLevel` -> https://github.com/cdk/cdk/blob/5eebd3a58604b7fd0fad9ccd6681e1cdbcae845c/base/interfaces/src/main/java/org/openscience/cdk/tools/ILoggingTool.java#L230

**Comment by egonw** [comment]
> I would question the functionality these classes provide to the CDK, though; as a library, CDK might be most useful in
> terms of logging if it provides the flexibility to the user of the library to choose her/his own logging implementation

Yes! Exactly the design I just described. It's Log4j that is doing the same thing here on top of that.

But I have no clue how to make sure Log4j stays away from Slf4j. And I have no clue how :(

**Comment by uli-f** [comment]
Thank you Egon.

A few questions:

> users choose a sink, and the CDK-level API posts the logging to that sink

How do I choose a sink here?

> CDK->Log4j->Something. But that Something always seems to have to be `org.slf4j'.

Mh, if you turn on log4j debugging by setting a system property `log4j2.debug` to `true` or alternatively just debug the code I could observe that it logs to log4j for my configuration. And I wasn't able to switch over to slf4j (see below).

I am anything but an expert in this area, but my understanding is that by depending not only on the log4j-api but also on the log4j-core in LoggingTools the choice is made for the user. I cannot use the bridge from log4j to slf4j because of that 🤷🏼 (see [above](https://github.com/cdk/cdk/issues/873#issuecomment-1220270527))

I do find the whole logging realm quite confusing and complex, too. But my understanding is that as long as the library only depends on a logging API (log4j-api) the user can switch to any implementation; this doesn't work anymore that easily if the library also depends on a logging implementation (log4j-core).

> Honestly, not really sure. Currently, I would argue that if you want to use Slf4j, we should write an ILoggingTool implementation for Slf4j instead.

In my opinion, that defeats the purpose of being independent of the logging implementation. How would you choose the actual implementation then? By configuring something in the CDK? For other libraries that is done by just adding a logging implementation to the code that uses the library which is a well-established an easy process.

**Comment by egonw** [comment]
I will try to dig up some information this weekend.

**Comment by uli-f** [comment]
I found this is a very concise and good overview: https://www.slf4j.org/manual.html

**Comment by egonw** [comment]
I will try to dig up why the default CDK depends on this full log4j/slf4j stack.

I'm also rebuilding the latest tex-based "Groovy Cheminformatics" content and will port this to Markdown asap.

**Comment by johnmay** [comment]
I think SLF4j comes from JENA.

**Comment by johnmay** [comment]
In this case Uli have you also included logback? Unfortunately this is just the mess of Java logging, it's shame the default util.Logger isn't any good and everyone could just use that. We are consistent within CDK the issue is when we pull in external libraries that decide to use a different framework (e.g. commons-loggin) or slf4j.

Just confirming where the slf4j and commons logging gets pulled in from Jena;

```
$ mvn dependency:tree | grep slf4j -A10 -B10
[INFO] \- org.openscience.cdk:cdk-iordf:jar:2.8-SNAPSHOT:compile
[INFO]    +- org.apache.jena:jena-core:jar:4.5.0:compile
[INFO]    |  +- org.apache.jena:jena-base:jar:4.5.0:compile
[INFO]    |  |  +- org.slf4j:slf4j-api:jar:1.7.36:compile
[INFO]    |  |  +- org.apache.jena:jena-shaded-guava:jar:4.5.0:compile
[INFO]    |  |  +- org.apache.commons:commons-csv:jar:1.9.0:compile
[INFO]    |  |  +- commons-codec:commons-codec:jar:1.15:compile
[INFO]    |  |  +- org.apache.commons:commons-compress:jar:1.21:compile
[INFO]    |  |  \- com.github.andrewoma.dexx:collection:jar:0.7:compile
[INFO]    |  +- org.apache.jena:jena-iri:jar:4.5.0:compile
[INFO]    |  \- commons-cli:commons-cli:jar:1.5.0:compile
```

**Comment by johnmay** [comment]
This is where you choose the modules you need, you can always exclude cdk-log4j and cdk-iordf to have a "clean slate" w.r.t. to logging.

**Comment by egonw** [comment]
> exclude cdk-iordf

I guess we could actually try to exclude `org.slf4j:slf4j-api` as a dependency from `cdk-iordf` ?

**Comment by uli-f** [comment]
Yes I also included logback (see my [original post](https://github.com/cdk/cdk/issues/873#issue-1343844871)) as this is the standard logging implementation `spring-boot` comes with.

> Unfortunately this is just the mess of Java logging, it's shame the default util.Logger isn't any good and everyone could just use that.

Agreed. But my understanding is as long as you only pull in an API you can mix and match all of the different approaches.
The user of the library then makes a choice when depending on a logging implementation (and any corresponding bridges to carry over the logging output of other APIs to the chosen logging implementation).

> This is where you choose the modules you need (cdk-smiles, cdk-silent, cdk-standard, cdk-ctab is a good start and probably gives most of what you need), you can always include cdk-bundle and exclude cdk-iordf (and maybe cdk-log4j if you provide you own version) to have a "clean slate" w.r.t. to logging.

This is more or less how I started out in the beginning.
But since I added four `ambit2` modules as a dependency the number of cdk-modules pulled in as transitive dependencies exploded, I guess there are not many cdk-modules left that aren't pulled in! 🤣 

Excluding `cdk-log4j` was my initial approach to fix my issue. Unfortunately, the `ambit-core` module depends on `cdk-log4j`, so that did not work. I already pointed out to Nina that this behavior isn't necessarily following best practice and they might change that in a future ambit version.

**Comment by uli-f** [comment]
> I guess we could actually try to exclude org.slf4j:slf4j-api as a dependency from cdk-iordf ?

IMO, being dependent on the APIs of the different logging frameworks is not an issue. They happily exist next to each other.
It only becomes an issue if a library depends on a concrete implementation - as the CDK unfortunately does in its `cdk-log4j` module.

**Comment by egonw** [comment]
`cdk-log4j` is meant to be implementation dependent. It's the Log4j implementation of the CDK `ILoggingTool`.

That is why you should not include that module in your stack if you do not want to use Log4j.

**Comment by egonw** [comment]
> I'm also rebuilding the latest tex-based "Groovy Cheminformatics" content and will port this to Markdown asap.

Okay, apparently I never wrote about the `ILoggingTool` stack :/

**Comment by egonw** [comment]
> How do I choose a sink here?

Yes, good question. Originally, by including `log4j`. But that was in a time when we did not integrate things as much as we do now.

**Comment by uli-f** [comment]
> That is why you should not include that module in your stack if you do not want to use Log4j.

@egonw Thank you for clarifying.

As pointed out above I tried to do exactly that but could not follow thru as the `ambit2-core` depends on `cdk-log4j`.

But I fully agree that this would have been the best solution for my issue.

**Comment by uli-f** [comment]
> Yes, good question. Originally, by including log4j. But that was in a time when we did not integrate things as much as we do now.

@egonw Just to be sure: I assume you are referring to `log4j-core` here?

**Comment by egonw** [comment]
> @egonw Just to be sure: I assume you are referring to `log4j-core` here?

Yes, originally. But it always was looking for a class, not a Maven module. We only started using Maven when John joined.

And now I just found https://github.com/cdk/cdk/blob/master/base/interfaces/src/main/java/org/openscience/cdk/tools/LoggingToolFactory.java ... to complicate things.

Okay, I really need to write something up... I so sure I did...

**Comment by egonw** [comment]
Sorry, I have to fix other stuff first now. I can dig into this, but not now. Cannot find the 2-4 hours I need for this.

**Comment by uli-f** [comment]
Let me know if there is anything I can do to support you in this.

**Comment by johnmay** [comment]
I think the log4j-core in ambit issue is conflating things. As Egon has noted “cdk-log4j” is the implementation (like log4j-core) and you include it if you need it. I really think the issue here is as you first identified the log4j-to-slf4j which is coming in via cdk-iordf. Which in turn is coming via cdk-bundle I presume? 

As noted already, the cdk-bundle is primarily for new users who don’t understand or want to worry about the modules. If you are building anything beyond a simple test program I do not recommend using “cdk-bundle”.


As a further aside, we (NextMove) use CDK as a dependency in several spring boot applications which are deployed to customers and there are no issues. Part of this could be logback (aka log4j1 restarted) causing a conflict in your case. Or it could be I never use cdk-bundle and have not neede cdk-iordf in these applications.

**Comment by johnmay** [comment]
Do you just need ambit for the SMIRKS?

**Comment by egonw** [comment]
@uli-f, and if you do want to use the bundle, you can exclude the `iordf` module, I think, with something like this:

```xml
        <dependency>
            <groupId>org.openscience.cdk</groupId>
            <artifactId>cdk</artifactId>
            <version>2.7.1</version>
            <exclusions>
                <exclusion>
                    <artifactId>org.openscience.cdk</artifactId>
                    <groupId>cdk-iordf</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by uli-f** [comment]
> Do you just need ambit for the SMIRKS?

Yes, at the moment I need ambit just for the SMIRKS.

**Comment by uli-f** [comment]
> @uli-f, and if you do want to use the bundle, you can exclude the `iordf` module, I think, with something like this:

I don't use cdk-bundle, neither does the ambit library. Instead I explicitly list all the cdk modules that I actually need.

And `iordf` is one of the (very) few cdk modules that is nowhere to be seen on my dependency graph 👀

**Comment by uli-f** [comment]
> I think the log4j-core in ambit issue is conflating things. As Egon has noted “cdk-log4j” is the implementation (like log4j-core) and you include it if you need it. I really think the issue here is as you first identified the log4j-to-slf4j which is coming in via cdk-iordf. Which in turn is coming via cdk-bundle I presume?

A lot of information has been added to this issue, so let me quickly summarize here a few things to clarify:

- Yes, the ambit library is one of the reasons for this issue as it depends on `cdk-log4j` and makes use `LoggingTool`. Imo, as a library, ambit should not include this dependency as it thereby indirectly makes a choice regarding a particular logging implementation - something a library is not supposed to do. This is already acknoweldged by Nina and will be addressed in a future version of ambit.
- I do not have `cdk-iordf` in my dependency graph. Instead, the log4j-to-slf4j gets pulled in by spring-boot as a transitive dependency from `spring-boot-starter-logging`:
```
org.springframework.boot:spring-boot-starter-logging:2.7.2
|    |    |    +--- ch.qos.logback:logback-classic:1.2.11
|    |    |    |    +--- ch.qos.logback:logback-core:1.2.11
|    |    |    |    \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.36
|    |    |    +--- org.apache.logging.log4j:log4j-to-slf4j:2.17.2
|    |    |    |    +--- org.slf4j:slf4j-api:1.7.35 -> 1.7.36
|    |    |    |    \--- org.apache.logging.log4j:log4j-api:2.17.2
|    |    |    \--- org.slf4j:jul-to-slf4j:1.7.36
|    |    |         \--- org.slf4j:slf4j-api:1.7.36
```
- I do not use cdk-bundle but instead explicitly list all cdk modules that I require as a dependency.

What made a bit harder for me to track down the issue in the first place is that in the following piece of code [LoggingTool](https://github.com/cdk/cdk/blob/8d5821f29d4d254d23a8aebe5635478fc0e994ae/misc/log4j/src/main/java/org/openscience/cdk/tools/LoggingTool.java) intends to catch a `SecurityException` (at least according to the comment in the code) but instead catches `Exception` thereby swallowing up any helpful information that an exception comes with (class name, message) and replacing it with a message to `stderr`:
```
if (strJvmVersion.compareTo("1.2") >= 0) {
  // Use a try {} to catch SecurityExceptions when used in applets
  try {
    // by default debugging is set off, but it can be turned on
    // with starting java like "java -Dcdk.debugging=true"
    if (System.getProperty("cdk.debugging", "false").equals("true")) {
      Configurator.setLevel(log4jLogger.getName(), Level.DEBUG);
    } else {
      Configurator.setLevel(log4jLogger.getName(), Level.WARN);
    }
    if (System.getProperty("cdk.debug.stdout", "false").equals("true")) {
      toSTDOUT = true;
     }
   } catch (Exception e) {
     System.err.println("Could not read the System property used to determine "
       + "if logging should be turned on. So continuing without logging.");
   }
}
```
In my opinion, we might be better off replacing this with a more specific catch clause:

```
   } catch (SecurityException e) {
     System.err.println("Could not read the System property used to determine "
       + "if logging should be turned on. So continuing without logging.");
   }
```

**Comment by egonw** [comment]
@uli-f, that sounds like a good patch to me. I can do it, but you surely too. Let me know what you prefer.

**Comment by uli-f** [comment]
@egonw very happy to create a PR but it seems I don't have the necessary permissions to do that....?

Getting this from IntelliJ when creating a PR on GitHub:

`Can't create a new pull request: Push failed: remote: Permission to cdk/cdk.git denied to uli-f. unable to access 'https://github.com/cdk/cdk.git/': The requested URL returned error: 403`

IntelliJ wants to have the following GitHub permissions on the repo to submit a PR:
- Full control of private repositories (probably not be relevant here, as cdk is a public repo)
- Update GitHub Action workflows 
- Read org and team membership, read org projects
- Create gists

**Comment by uli-f** [comment]
Thanks @egonw for introducing me to this workflow.

**Comment by johnmay** [comment]
I'm a bit lost where we are now, to summarise where I think we are:
 - using spring boot pulls in log4j-to-slf4j causing incorrect logging levels since the log4j-core was also coming in from cdk-log4j.
 -  Switching CDK to slf4j does not entirely make sense as the logic is already decoupled, i.e. CDK ILoggingTool provides an even lighter weight interface on which different logging implementations can be configured. From scratch I probably would just use slf4j but I have no objection to the current ILoggingTool etc since it's the same basic idea.
 - So the solution is therefore to not include cdk-log4j, and by extension log4j-core. However this is not possible because AMBIT used log4j-core (possibly via cdk-log4j?).

Is that correct?

**Comment by uli-f** [comment]
> I'm a bit lost where we are now, to summarise where I think we are:

@johnmay you may also have a look at my previous [comment](https://github.com/cdk/cdk/issues/873#issuecomment-1221667954) where I tried to summarize.

> using spring boot pulls in log4j-to-slf4j causing incorrect logging levels since the log4j-core was also coming in from cdk-log4j.

- spring boot pulls in log4j-to-slf4j
- incorrect logging levels are not an issue, but I assume you might refer to the piece of code in LoggingTool that deals with setting the logging level for the CDK logging framework
- however, having both `log4j-core` and `log4j-to-slf4j` on the classpath leads to a `ClassCastException` in Line 177 of `org.openscience.cdk.tools.LoggingTool`

> Switching CDK to slf4j does not entirely make sense as the logic is already decoupled, i.e. CDK ILoggingTool provides an even lighter weight interface on which different logging implementations can be configured. From scratch I probably would just use slf4j but I have no objection to the current ILoggingTool etc since it's the same basic idea.

Agreed :)

> So the solution is therefore to not include cdk-log4j, and by extension log4j-core. However this is not possible because AMBIT used log4j-core (possibly via cdk-log4j?).

- Yes, correct again: ambit uses the `LoggingTool` class, declares a dependency on `cdk-log4j` and thus transitively pulls in `log4j-core` as this is a dependency of `cdk-log4j`.
- Being a library itself, ambit should not do this. The ambit team has already acknowledged this.

**Comment by uli-f** [comment]
It might be worthwhile adding a comment to the LoggingTool class to make it clear that using this class implicitly sets the logging implementation:

```
This class is part of the module cdk-log4j.
By using this class and depending on the module cdk-log4j a transitive dependency on log4j-core is established.
This may lead to an issue (more specifically, a ClassCastException) if the library log4j-to-slf4j is also a dependency.
See also https://github.com/cdk/cdk/issues/873.

```
It caused me/us a bit of pain, so we might very well try to prevent anyone else from experiencing this.

Probably just my personal opinion:
I don't see a lot of benefit of introducing a logging implementation in the CDK library, even though usage of it is optional and the corresponding dependency can be excluded when using the library. In my opinion, anything that involves a logging implementation is supposed to happen on the client side of the library.

**Comment by johnmay** [comment]
You have to remember when this was written, "everyone" used Log4j v1 so it wasn't really an issue. I will add a comment.

**Comment by johnmay** [comment]
In fact one better, I think I will make this work correctly.

**Comment by johnmay** [comment]
Argh I forgot log4j-core is needed to change the level at runtime. I think I can make this work though

**Comment by uli-f** [comment]
@johnmay Please let me know if and when you want some feedback for #878 from me.

**Comment by johnmay** [comment]
Oh feedback whenever is good, I need to do some more testing on it but I believe it should be correct as it is
