### ISSUE TITLE
swallowing exceptions in org.openscience.cdk.tools.LoggingToolFactory

### ISSUE THREAD

**Issue by uli-f** [cdk/cdk#877]
[LoggingToolFactory](https://github.com/cdk/cdk/blob/master/base/interfaces/src/main/java/org/openscience/cdk/tools/LoggingToolFactory.java) has two catch clauses that just swallow exceptions:

[Line 97](https://github.com/cdk/cdk/blob/efa79b2afb8b3af2c555e852172a0e1ecd74d0e2/base/interfaces/src/main/java/org/openscience/cdk/tools/LoggingToolFactory.java#L97)

`catch (ClassNotFoundException | IllegalArgumentException | SecurityException e) { }`

[Line 112](https://github.com/cdk/cdk/blob/efa79b2afb8b3af2c555e852172a0e1ecd74d0e2/base/interfaces/src/main/java/org/openscience/cdk/tools/LoggingToolFactory.java#L112)

`catch (SecurityException | InvocationTargetException | IllegalAccessException | IllegalArgumentException | NoSuchMethodException e) { }`

Empty catch clauses like this make for a bad user experience in my opinion: something causes a problem (here: the logging class not being instantiated), but the user does not get any notification about this. So from a user's side something does not work, but there is no feedback about this (what, why).

Proposed solution:
Re-throw the `RuntimeException` as a non-runtime Exception, possible the more specific `CDKException`.

**Comment by johnmay** [comment]
The issue is it uses the null return for control flow. Try this, or this or that. Perhaps a better way is we can check if the class exists Class.forName() but then we still need to swallow exceptions so you end up with similar logic regardless.

**Comment by uli-f** [comment]
Oh, I see now.

The two methods `initializeLoggingTool` and `instantiateWithCreateMethod` are private and only called from the method `createLoggingTool`.

So it doesn't make a lot of difference whether you return null or throw an Exception up the call stack to control the flow in `createLoggingTool`.

I'd usually prefer passing up exceptions because it allows you to keep information about the what/why of the event that has happened. But in this case you cannot log that anywhere b/c we are in the process of setting up our logger.

It might be one of the rare cases where a message to stderr would be helpful instead of inappropriate as at least it would give you a clear(er) indication of why the logger wasn't set up.
```
public static ILoggingTool createLoggingTool(Class<?> sourceClass) {
  ILoggingTool tool = null;
  // first attempt the user set ILoggingTool
  try {
    if (userSetILoggerTool != null) {
      tool = instantiateWithCreateMethod(sourceClass, userSetILoggerTool);
    }
    if (tool == null) {
      tool = initializeLoggingTool(sourceClass, DEFAULT_LOGGING_TOOL_CLASS);
    }
    if (tool == null) {
      tool = initializeLoggingTool(sourceClass, STDOUT_LOGGING_TOOL_CLASS);
    }
  } catch (CDKException exception) {
    System.err.println("Unable to instantiate a logging implementation: " + 
      exception.getCause().getClass() + ", " + exception.getCause().getMessage());
  }
  return tool;
}

private static ILoggingTool initializeLoggingTool(Class<?> sourceClass, String className) throws CDKException {
  try {
    Class<?> possibleLoggingToolClass = sourceClass.getClassLoader().loadClass(className);
    if (ILoggingTool.class.isAssignableFrom(possibleLoggingToolClass)) {
      return instantiateWithCreateMethod(sourceClass, possibleLoggingToolClass);
    }
  } catch (ClassNotFoundException | IllegalArgumentException | SecurityException e) {
    throw new CDKException("message", e);
  }
  return null;
}

private static ILoggingTool instantiateWithCreateMethod(Class<?> sourceClass, Class<?> loggingToolClass) throws CDKException {
  Method createMethod;
  try {
    createMethod = loggingToolClass.getMethod("create", Class.class);
    Object createdLoggingTool = createMethod.invoke(null, sourceClass);
    if (createdLoggingTool instanceof ILoggingTool) {
      return (ILoggingTool) createdLoggingTool;
    } else {
      System.out.println("Expected ILoggingTool, but found a:" + createdLoggingTool.getClass().getName());
    }
  } catch (SecurityException | InvocationTargetException | IllegalAccessException | IllegalArgumentException | NoSuchMethodException e) {
    throw new CDKException("message", e);
  }
  return null;
}
```
@johnmay I am happy to supply a PR for this or just drop it if you are not convinced of the usefulness.

**Comment by johnmay** [comment]
Take a look at the PR, the StdErr logger is not created via reflection so
you will always get something now. And the runtime exception is fine, I
first check if the class exists
