### ISSUE TITLE
adding method perceiveAtomTypesAndConfigureAtoms(IReaction reaction) in ReactionManipulator

### ISSUE THREAD

**Issue by uli-f** [cdk/cdk#880]
Just required a method to perceive the atom types and configure the atoms for a reaction.

There is a comparable method for IAtomContainers in AtomContainerManipulator.percieveAtomTypesAndConfigureAtoms(IAtomContainer container). However, I wasn't able to find a method that does this for all IAtomContainers in a reaction.

Should be straightforward to add such a method to ReactionManipulator.

I am happy to do this and open a PR if you agree.

**Comment by egonw** [comment]
Sounds good to me.

**Comment by uli-f** [comment]
opened PR #883
