### ISSUE TITLE
test fails org.openscience.cdk.depict.DepictionTest.depictAsSvg

### ISSUE THREAD

**Issue by uli-f** [cdk/cdk#881]
I was just running the tests and org.openscience.cdk.depict.DepictionTest.depictAsSvg fails for me.

The reason is that it infers the newline character from the system property line.separator

`String nl = System.getProperty("line.separator");`

which returns the line separator `\n` if on a Linux machine , but `\r\n` if on a Windows machine (and probably `\r` if on a Mac).

I can fix the test by changing that line to

`String nl = "\n";`

I would consider this a valid fix if the downstream code/library that outputs the SVG platform-independently uses `\n` as a line separator - which seems to be the case.

If you agree I am happy to provide a PR.

**Comment by johnmay** [comment]
Mac is also \n it’s windows which is the odd ball here. :). Pr welcome but I wonder if something else is going on based on your other failures

**Comment by uli-f** [comment]
> Mac is also \n it’s windows which is the odd ball here. :)

Point taken 😁

**Comment by uli-f** [comment]
> I wonder if something else is going on based on your other failures

Might be related to #882

Happy to wait with the PR until we know more about #882.
