### ISSUE TITLE
question: worthwhile adding newReaction() to SilentChemObjectBuilder ?

### ISSUE THREAD

**Issue by uli-f** [cdk/cdk#887]
I create quite a few new `Reaction` objects in my code.

Following the advice to use the `ChemObjectBuilder`, more specifically the `SilentChemObjectBuilder`, to instantiate CDK objects specified in the package `org.openscience.cdk.interfaces` and taking into consideration that reflection isn't known for its speed:

Is it worthwhile adding a `newReaction()` method to `SilentChemObjectBuilder` similar to the `newAtomContainer`, `newAtom` and `newBond` methods?

If this seems a worthwhile endeavor I am happy to add this functionality and submit a  PR.

**Comment by johnmay** [comment]
Sure, the newAtom/newBond has the most impact on performance because these are called about 50x for an avg molecule. 

I have no objection to common objects have their dedicated method. But would not add newBioPolymer(), newIsotope() etc

**Comment by uli-f** [comment]
Implemented in #888
