### ISSUE TITLE
bumping Java language level

### ISSUE THREAD

**Issue by uli-f** [cdk/cdk#892]
The language level  is currently set to Java 8. A lot has happened since, including two LTS releases (11,17).

Bumping the language level to 11 or 17 gives access to new APIs, in particular usage of the Stream API and the Collections API feels significantly smoother to me.

At this point, bumping to 11 seems conservative, and I'd prefer going all the way to 17 even though I can see that this might feel like putting a bit of pressure on for anything downstream.

I bumped quite a bit of code from 8 to 17 without significant issues, but with a project as big as the CDK most likely something will pop up. However, having that many tests in place it should be easy enough to become aware of any issue.

**Comment by johnmay** [comment]
Perhaps, but it would be CDK 3.0 obviously. I do think Java 17 is reasonable/possible and at a major release it would be OK.

**Comment by johnmay** [comment]
Can you add it to the CDK v3.0 roadmap issue thanks.
