### ISSUE TITLE
jnainchi doesn't seem to work on darwin-aarch64

### ISSUE THREAD

**Issue by slyrus** [cdk/cdk#894]
This is probably some sort of operator/configuration error, but using the 2.8-SNAPSHOT, I'm able to get an InChIGeneratorFactory but when I call genInChIGenerator on it, I get the following error:

```
Java exception 'java.lang.RuntimeException: Error loading InChI native code. Please check that the binaries for your platform (darwin-aarch64) have been included on the classpath.'.
```

~/.m2/repository/io/github/dan2097/jna-inchi-darwin-aarch64/1.1/jna-inchi-darwin-aarch64-1.1.jar is on my classpath and the file is there and has "darwin-aarch64/libjnainchi.dylib" inside it, but, nevertheless, the InChI code isn't happy.

Any suggestions?

Thanks!

**Comment by johnmay** [comment]
Which M1 are you on, I compiled that DYLIB for daniel but maybe it is not possible to cross compile.

**Comment by johnmay** [comment]
You will need to dig down into the loading error (in JNA InchI) to see what the warning is. Is there any more info/stack trace.

**Comment by slyrus** [comment]
Is there a suitable test in the test suite that should be exercising similar code paths?

My abcl (common lisp on the JVM) stack trace isn't likely to be particularly helpful:

```
  0: (INVOKE-DEBUGGER #<JAVA-EXCEPTION java.lang.RuntimeException: Error loading InChI native code. Please check that the binaries for your platform (darwin-aarch64) have been included on the classpath. {2..
  1: org.armedbear.lisp.Lisp.error(Lisp.java:383)
  2: ! io.github.dan2097.jnainchi.JnaInchi.checkLibrary(JnaInchi.java:694)
  3: ! io.github.dan2097.jnainchi.JnaInchi.toInchi(JnaInchi.java:75)
  4: ! org.openscience.cdk.inchi.InChIGenerator.generateInchiFromCDKAtomContainer(InChIGenerator.java:488)
  5: ! org.openscience.cdk.inchi.InChIGenerator.<init>(InChIGenerator.java:129)
  6: ! org.openscience.cdk.inchi.InChIGenerator.<init>(InChIGenerator.java:163)
  7: ! org.openscience.cdk.inchi.InChIGeneratorFactory.getInChIGenerator(InChIGeneratorFactory.java:153)
```

FWIW, I had similar code up and running long ago (pre aarch64 and probably pre-jnainchi).

**Comment by johnmay** [comment]
Yes any test in cdk-inchi, I don’t have any issues on my m1 but I did compile it…

**Comment by johnmay** [comment]
FYI for @dan2097. I will look into this but suspect possible permissions issue. @slyrus can you give more details on your setup, what jvm versions does you abcl run on?

**Comment by slyrus** [comment]
I'm using 18.0.2.1 from Homebrew, apparently:

```
Java 18.0.2.1 Homebrew
OpenJDK 64-Bit Server VM
```

I'm certainly not wedded to that if there is a better recommendation, and I'm happy to try others for debugging purposes as well.

**Comment by johnmay** [comment]
Do the tests run OK from ``mvn install``?

**Comment by slyrus** [comment]
Yes, all tests pass, although it doesn't look like much (if anything) from jnainchi is being exercised.

**Comment by slyrus** [comment]
And, FWIW, if I install jnainchi from code checked out from the github repo, it passes its tests, so apparently the library is working. Perhaps this is some sort of weird new-ish mac permission problem.

**Comment by slyrus** [comment]
On further investigation.... Here are the various locations the java NativeLibrary seems to look for the jnainchi stuff:

```
Java exception 'java.lang.UnsatisfiedLinkError: Unable to load library 'jnainchi':
dlopen(libjnainchi.dylib, 0x0009): tried: '/opt/homebrew/Cellar/openjdk/18.0.2.1/libexec/openjdk.jdk/Contents/Home/bin/./libjnainchi.dylib' (no such file),
'/opt/homebrew/Cellar/openjdk/18.0.2.1/libexec/openjdk.jdk/Contents/Home/bin/../lib/libjnainchi.dylib' (no such file),
'libjnainchi.dylib' (no such file),
'/usr/local/lib/libjnainchi.dylib' (no such file),
'/usr/lib/libjnainchi.dylib' (no such file),
'/Users/CHarmon/olema/research/proj/cdk2/cdk2-medchem/libjnainchi.dylib' (no such file)
dlopen(libjnainchi.dylib, 0x0009): tried: '/opt/homebrew/Cellar/openjdk/18.0.2.1/libexec/openjdk.jdk/Contents/Home/bin/./libjnainchi.dylib' (no such file),
'/opt/homebrew/Cellar/openjdk/18.0.2.1/libexec/openjdk.jdk/Contents/Home/bin/../lib/libjnainchi.dylib' (no such file),
'libjnainchi.dylib' (no such file),
'/usr/local/lib/libjnainchi.dylib' (no such file),
'/usr/lib/libjnainchi.dylib' (no such file),
'/Users/CHarmon/olema/research/proj/cdk2/cdk2-medchem/libjnainchi.dylib' (no such file)
dlopen(/Users/CHarmon/Library/Frameworks/jnainchi.framework/jnainchi, 0x0009): tried: '/Users/CHarmon/Library/Frameworks/jnainchi.framework/jnainchi' (no such file),
'/Library/Frameworks/jnainchi.framework/jnainchi' (no such file),
'/System/Library/Frameworks/jnainchi.framework/jnainchi' (no such file)
dlopen(/Library/Frameworks/jnainchi.framework/jnainchi, 0x0009): tried: '/Library/Frameworks/jnainchi.framework/jnainchi' (no such file),
'/System/Library/Frameworks/jnainchi.framework/jnainchi' (no such file)
dlopen(/System/Library/Frameworks/jnainchi.framework/jnainchi, 0x0009): tried: '/System/Library/Frameworks/jnainchi.framework/jnainchi' (no such file),
'/Library/Frameworks/jnainchi.framework/jnainchi' (no such file)
Native library (darwin-aarch64/libjnainchi.dylib) not found in resource path (/Users/CHarmon/olema/legacy/olema-research/submodules/lang/abcl/dist/abcl.jar:)'.
```

So the right "jar" file is on the classpath, but the java native library stuff doesn't seem to find it there.

**Comment by slyrus** [comment]
So it looks like the java NativeLibrary stuff can't find the jar:

```
Java exception 'java.lang.UnsatisfiedLinkError: Unable to load library 'jnainchi':
dlopen(libjnainchi.dylib, 0x0009): tried: '/opt/homebrew/Cellar/openjdk/18.0.2.1/libexec/openjdk.jdk/Contents/Home/bin/./libjnainchi.dylib' (no such file),
'/opt/homebrew/Cellar/openjdk/18.0.2.1/libexec/openjdk.jdk/Contents/Home/bin/../lib/libjnainchi.dylib' (no such file),
'libjnainchi.dylib' (no such file),
'/usr/local/lib/libjnainchi.dylib' (no such file),
'/usr/lib/libjnainchi.dylib' (no such file),
'/Users/CHarmon/projects/jnainchi-test/libjnainchi.dylib' (no such file)
dlopen(libjnainchi.dylib, 0x0009): tried: '/opt/homebrew/Cellar/openjdk/18.0.2.1/libexec/openjdk.jdk/Contents/Home/bin/./libjnainchi.dylib' (no such file),
'/opt/homebrew/Cellar/openjdk/18.0.2.1/libexec/openjdk.jdk/Contents/Home/bin/../lib/libjnainchi.dylib' (no such file),
'libjnainchi.dylib' (no such file),
'/usr/local/lib/libjnainchi.dylib' (no such file),
'/usr/lib/libjnainchi.dylib' (no such file),
'/Users/CHarmon/projects/jnainchi-test/libjnainchi.dylib' (no such file)
dlopen(/Users/CHarmon/Library/Frameworks/jnainchi.framework/jnainchi, 0x0009): tried: '/Users/CHarmon/Library/Frameworks/jnainchi.framework/jnainchi' (no such file),
'/Library/Frameworks/jnainchi.framework/jnainchi' (no such file),
'/System/Library/Frameworks/jnainchi.framework/jnainchi' (no such file)
dlopen(/Library/Frameworks/jnainchi.framework/jnainchi, 0x0009): tried: '/Library/Frameworks/jnainchi.framework/jnainchi' (no such file),
'/System/Library/Frameworks/jnainchi.framework/jnainchi' (no such file)
dlopen(/System/Library/Frameworks/jnainchi.framework/jnainchi, 0x0009): tried: '/System/Library/Frameworks/jnainchi.framework/jnainchi' (no such file),
'/Library/Frameworks/jnainchi.framework/jnainchi' (no such file)
Native library (darwin-aarch64/libjnainchi.dylib) not found in resource path (/Users/CHarmon/submodules/lang/abcl/dist/abcl.jar:)'
```
even thought the jna jars are actually on my classpath.

**Comment by johnmay** [comment]
> Yes, all tests pass, although it doesn't look like much (if anything) from jnainchi is being exercised.

It is in cdk-inchi. I think this is possibly an ABCL or HomeBrew Java issue. It should be unpacking the JAR to some temporary directory then loading it in. The errors you showed it is looking in the wrong placeL

```
Java exception 'java.lang.UnsatisfiedLinkError: Unable to load library 'jnainchi':
dlopen(libjnainchi.dylib, 0x0009): tried: '/opt/homebrew/Cellar/openjdk/18.0.2.1/libexec/openjdk.jdk/Contents/Home/bin/./libjnainchi.dylib' (no such file),
'/opt/homebrew/Cellar/openjdk/18.0.2.1/libexec/openjdk.jdk/Contents/Home/bin/../lib/libjnainchi.dylib' (no such file),
'libjnainchi.dylib' (no such file),
'/usr/local/lib/libjnainchi.dylib' (no such file),
'/usr/lib/libjnainchi.dylib' (no such file),
'/Users/CHarmon/projects/jnainchi-test/libjnainchi.dylib'
```

Note a permanent solution, but what happens if you manually put lib from the aarch64 dependency in:
```
/usr/local/lib/libjnainchi.dylib
```
?

**Comment by slyrus** [comment]
If I do that, things work great (after adding in the cdk-jniinchi-support jar (which seems like a lot of jar for two enums :) )). Thanks for the great suggestions! This solves my immediate problem. Likely to be some sort of weird interaction with ABCL and the java native library loading code. Not sure how to proceed, but I'll think about it.

**Comment by johnmay** [comment]
The jni inchi support will be removed in future but it means you don’t need to change your code. So really you should update your code to use the new enums

**Comment by johnmay** [comment]
*jni inchi API

**Comment by johnmay** [comment]
I've install ABCL, do you have a self-contained code snippet I can run?

**Comment by johnmay** [comment]
The extend of my list is :-)
``
CL-USER(1): (+ 1 2)
3
``

**Comment by johnmay** [comment]
@slyrus this is blocking a 2.8 release. Please could you give some more context on how you call the CDK InChI functions?

Had a bit of a look but to me it looks very brittle (essentially using reflection) and so I’m not completely surprised if there is a permission issue or a set up static constructor is not being called

**Comment by slyrus** [comment]
Hi John,

There's an example lisp package that exercises this at:

https://github.com/slyrus/cdk-inchi-test

LMK if you have any trouble with it. Thanks!

**Comment by johnmay** [comment]
Thanks I'm struggling to get it working.

``
$ abcl
CL-USER(1): (require "asdf")
("uiop" "UIOP" "asdf" "ASDF")
CL-USER(2): (pushnew "(pushnew "/tmp/cdk-inchi-test" asdf:*central-registry*)
``

Just hangs for me.

BTW I would probably use cdk-bundle.jar for such applications as you need make sure all the correct dependencies are included. Since you basically pull in everything anyways there isn't much benefit to specifying all the deps one by one.

**Comment by johnmay** [comment]
OK got there... need trailing slash as well.

**Comment by johnmay** [comment]
@slyrus Is there way to dump what ABCL thinks the class path is? I wonder if ASDF didn't pull in the dependency correctly or in the wrong order.

**Comment by johnmay** [comment]
```(defun get-urls ()
  (let* ((cl (java:jstatic "getSystemClassLoader" "java.lang.ClassLoader")))
    (#"getURLs" cl)))

**Comment by johnmay** [comment]
```private static void checkLibrary() {
    if (libraryLoadingError != null) {
      throw new RuntimeException("Error loading InChI native code. Please check that the binaries for your platform (" + platform + ") have been included on the classpath.", libraryLoadingError);
    }
  }

  static {
    Throwable t = null;
    String p = null;

    try {
      p = Platform.RESOURCE_PREFIX;
      InchiLibrary.JNA_NATIVE_LIB.getName();
    } catch (Throwable var3) {
      t = var3;
    }

    platform = p;
    libraryLoadingError = t;
  }
}
```

**Comment by johnmay** [comment]
Here is the relevant error handling from JNA InChI.

**Comment by johnmay** [comment]
```
public class AbclDebug {
    public static void dumpClassPath() {
        System.out.println(System.getProperty("java.class.path").replace(':','\n'));
    }
}
```

```
(java:jstatic "dumpClassPath" "org.openscience.cdk.AbclDebug")
```

```
; (JAVA:JSTATIC "dumpClassPath" ...)
; Wrote /Users/john/.cache/common-lisp/abcl-1.9.0-fasl43-macosx-arm64/private/tmp/cdk-inchi-test/cdk-inchi-test-tmpGQTN7BPG.abcl (0.034 seconds)

/opt/homebrew/Cellar/abcl/1.9.0/libexec/abcl.jar
```

Hmmm - OK so it's definitely doing something funky with class loading.

**Comment by johnmay** [comment]
If i write something like the following:

```
public class AbclDebug {
    public static void lookup() {
        System.err.println(AbclDebug.class.getResourceAsStream("/darwin-aarch64/libjnainchi.dylib"));
    }
}
```

Then we can see it find the resource.

```
sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@3f1296fa
```

Which is correct (i.e. it's non-null)... but then I can't understand why JNA can't load it.

**Comment by johnmay** [comment]
I think I give up... I suspect it could be JigSaw/modules getting in the way and ABCL is doing something funky with class paths. You can see in your error it's only looking in ```abcl.jar```

```
Native library (darwin-aarch64/libjnainchi.dylib) not found in resource path (/Users/CHarmon/submodules/lang/abcl/dist/abcl.jar:)'
```
in my case

```
Native library (darwin-aarch64/libjnainchi.dylib) not found in resource path (/opt/homebrew/Cellar/abcl/1.9.0/libexec/abcl.jar:)'.
```

which is wrong it should be looking in all the JARs loaded... (i.e. it needs to look in jna-aarch64.jar)

**Comment by slyrus** [comment]
Thanks for your explorations! Let my try to address your questions:
1. ASDF path whoops! sorry, yes, need trailing "/"

2. classpath:
(java:dump-classpath)
should do the trick

3. Not sure about the classloader thing. At some point, java changed things so that it returned a ClassLoader, not a URLClassLoader. Is that cast legit? seems sketchy...
4. yes, we can get stack traces
5. Hmm... Ok. This is interesting. Thanks!

**Comment by johnmay** [comment]
Here is the part that fails in JNA:

https://github.com/java-native-access/jna/blob/master/src/com/sun/jna/NativeLibrary.java#L279-L296

**Comment by slyrus** [comment]
I have filed an issue with ABCL here: https://github.com/armedbear/abcl/issues/503
thanks!

**Comment by johnmay** [comment]
Closing as can't fix - JNA/ABCL interop issue. @slyrus please open a new issue if changes are needed on our side.
