### ISSUE TITLE
renaming main/master from master to main

### ISSUE THREAD

**Issue by egonw** [cdk/cdk#899]
It's the new git default, but we can make the switch too. Using `main` as the main branch is becoming very common, and besides all the other good reasons for why the rename happened, I'm getting very used to it _and_ it's shorter.

@johnmay, if you agree, I can update this repository.

Feedback from everyone most welcome! (In the past I would have use the "Request for Comments" approach.)

**Comment by johnmay** [comment]
I have no strong feeling either way

**Comment by uli-f** [comment]
I'd be strongly for changing to `main` given the reasons why this came up as an issue in the first place.

**Comment by johnmay** [comment]
I’ll do it later today, first will switch to main and leave master intact then remove that after a week or so

**Comment by johnmay** [comment]
Done, as I said rather than rename globally I renamed locally then switch the default. So master still exists for the open HoseCode PR... in fact I can probably just change that now.
