### ISSUE TITLE
throws CloneNotSupportedException at AtomContainerManipulator.extractSubstructure(IAtomContainer, int[]) 

### ISSUE THREAD

**Issue by uli-f** [cdk/cdk#903]
@johnmay, you removed the throws from `CloneNotSupportedException` to `AtomContainerManipulator.extractSubstructure(IAtomContainer, int[])`:

https://github.com/cdk/cdk/commit/1ef1c88529cb7ea93967fa9cd1def8f07fe1cf33

IMO, this is a breaking change, as downstream code that used this method would now get a compile error.

I am happy to leave it like that, but would suggest to add this to a list of breaking changes for the next release. Is there a changelog for the next release we could add this to?

**Comment by johnmay** [comment]
Correct, i was a little unsure as I mentioned in the PR. Yeah let’s put it back in but just not use clone.

ironically of course if you implement clone you’re meant to remove the exception from clone(). Copy constructor obv much better

**Comment by uli-f** [comment]
PR #904
