### ISSUE TITLE
a minimized set of JARs for rCDK

### ISSUE THREAD

**Issue by zachcp** [cdk/cdk#915]
Hi Team-CDK,

I am following up on a set of tweets about the performance of some of the code in `rcdk` ([Tweet here](https://twitter.com/zach_cp/status/1571871742573924356)),  and I am wondering if you can help us figure out a way to reduce the JAR size we include in `rcdk`.

> Note: I think CDK would be a really good substrate for LOTs of chemical work in R.   Java is fast and the `$` makes it easy to work.  There are currently 2 major dev issues: massive JAR size for CDK-libs and the compiled code step for rCDK.

Although @egonw mentioned that the CDK jars for 2.8 are smaller,  I see that the 2.8 bundle [is now 45Mb](https://github.com/cdk/cdk/releases/tag/cdk-2.8).  Maximum package size for CRAN is 5MB. `rcdk` has been granted a size exception but the latest JAR is already >25Mb. 45 is too big.    Ideally, we could find the minimal set of non-bundle JARs that would let us retain backwards compatibility with `rcdk` ( and all of its dependencies in CRAN/Bioconductor).   Do you have any suggestions on the best way to do this? 

zach cp

(note: @rajarshi if the above works you might be able to rewrite the JAVA compiled code back to R/rJava for a smoother dev cycle)

**Comment by egonw** [comment]
`rcdk` should not use the cdk bundle. Also, in the past the full CDK has been larger than this :)

I guess this issue should go to the `rcdk` repository, but don't mind discussing this here either.

**Comment by zachcp** [comment]
Agree this could go in `rcdk`. The main thing that I thought would be relevant to larger CDK users is how to identify JARs representing some subset of functionality.

**Comment by johnmay** [comment]
Please see the already open #911. Long story short, don’t include cdk-iordf, then will cut it basically in half. Then next target is jna inchi which targets more platforms than the old JNI libs. You can selectively not support 32-bit Linux/windows for example. You can also shade the jna jar in a similar manner.

**Comment by johnmay** [comment]
If I have time this year I will try and rewrite the CML processing to be more dependency efficient…

oh the other one to remove is builder3d, the cdk 3D code is not that good anyways :).

As Egon said, don’t use the cdk-bundle JAR you should pull in what you need

**Comment by zachcp** [comment]
PR in place for cdk-2.8  jars with a size compatible with previous releases. A bit hacky to generate the individual jars but seems to work for now.
