### ISSUE TITLE
maven goal javadoc:javadoc gives warnings

### ISSUE THREAD

**Issue by uli-f** [cdk/cdk#923]
`org.eclipse.aether.transfer.ArtifactNotFoundException: org.openscience.cdk:cdk-build-utils:jar:1.0.2.9-jdk11 was not found in https://s01.oss.sonatype.org/content/repositories/snapshots`

I can see that repeatedly for every module the javadocs are built.

Please let me know if you require a more detailed maven output.

**Comment by johnmay** [comment]
You need to build it, see. https://github.com/cdk/cdk/wiki/Building-CDK.

I had a chat with Egon about being more "vanilla" with our JavaDoc since these customisations were painful 8 -> 11

**Comment by uli-f** [comment]
> You need to build it, see. https://github.com/cdk/cdk/wiki/Building-CDK.

That is a really good piece of documentation, thanks for putting that together!

> I had a chat with Egon about being more "vanilla" with our JavaDoc since these customisations were painful 8 -> 11

I remember listening in to this convo. There are good arguments for and against the current approach. But having anything not vanilla usually causes a lot of pain in the long run 🤒

**Comment by uli-f** [comment]
I downloaded the artifact `cdk-build-utils-1.0.2.8.jar` from https://github.com/cdk/cdk-build-util, but branch `main` of CDK required `cdk-build-utils-1.0.2.9-jdk11.jar` so had to build that myself from the `cdk/cdk-build-util` sources.

Might it be worthwhile to add `cdk-build-utils-1.0.2.9-jdk11.jar` to the releases of `cdk/cdk-build-util`?

Also, the following two warnings popped up when doing a `javadoc:aggregate`:

```
[WARNING] The POM for org.openscience.cdk:cdk-smiles:jar:2.8-SNAPSHOT is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.openscience.cdk:cdk-libiocml:jar:2.8-SNAPSHOT is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
```

**Comment by johnmay** [comment]
Sorry yes you need to build it, could add the JAR but it's more effort to do mvn install:install-file. 

Not sure about the warnings, there many it's hard to know which ones mater. A lot of this is due to the age of the project and various updates to JavaDoc linting etc. Providing the JavaDoc looks OK is what matters for me.

**Comment by johnmay** [comment]
We could add it to maven central, my view was needing to build the JavaDoc was quite niche and we host/provide this already.

**Comment by uli-f** [comment]
> We could add it to maven central, my view was needing to build the JavaDoc was quite niche and we host/provide this already.

Agreed.

I don't think it's ideal that generating the javadoc is a bit of effort. But then it is mainly of interest to contributors who might want to validate their contributions, so shouldn't affect a user of the library too much / at all.

I am going to close this now.
