### ISSUE TITLE
NPE in getInChIToStructure for radioactive elements

### ISSUE THREAD

**Issue by alev000** [cdk/cdk#925]
The following line throws a NullPointerException for radioactive elements like Technetium-99:
https://github.com/cdk/cdk/blob/cdk-2.8/storage/inchi/src/main/java/org/openscience/cdk/inchi/InChIToStructure.java#L195

Seems like this corresponds to `getMajorIsotope` returning null.

For example:
```java
InChIGeneratorFactory.getInstance().getInChIToStructure(
    "InChI=1S/Tc/i1+1",
    DefaultChemObjectBuilder.getInstance(),
).getAtomContainer()
```

I think the desired behavior would be to either (a) translate the NPE into a more informative CDKException, or (b) if possible, avoid the NPE altogether and continue generating the atom container.

**Comment by johnmay** [comment]
Thanks. 

The correct fix here is we should use the inchi isotope table. The +1 mass delta is from an arbitrary table and not the major isotope. This is inherited from the molfile which also did it this way.

See slide 4 here: https://www.nextmovesoftware.com/talks/Mayfield_BuildingOnSand_InChI_201708.pdf

this is one of the many reasons trying to turn an inchi back into a molecule is not a good idea.

**Comment by johnmay** [comment]
Here is the mass table:
https://github.com/metamolecular/inchi/blob/0fc7adc58d4ff1c481b26e0de53cc8a404c3d381/INCHI_BASE/src/util.c

(Official code is "source available" Richard has rehosted so easy to link here)
