### ISSUE TITLE
@(bond in ring), !@ (bond not in ring) and @;!:(ring but non-aromatic) bond expression

### ISSUE THREAD

**Issue by Le0nT1** [cdk/cdk#926]
Dear Developers,

I am using the SmartsPattern feature with Daylight SMARTS. It seems that @ expression can work in bond in ring match properly. However, !@ and @;!: don't work as expected and return true for any bond types.
Is cdk2.8 able to handle these bond expressions as described in Daylight SMARTS? If so, could you please show me some guidance? If not, are there any possible solutions? Currently, I am using R/r or !R/r with atoms as an alternative approach but it would be much better and easier if the bond notation can work.

Thank you.

**Comment by johnmay** [comment]
Need more context, which APIs are you using. You may need to set the ring information before calling.

**Comment by johnmay** [comment]
You can test on CDK depict: https://www.simolecule.com/cdkdepict/depict.html and see it works correctly:

<img width="1047" alt="Screenshot 2022-10-25 at 09 14 22" src="https://user-images.githubusercontent.com/983232/197720477-f982d94d-b1fc-42b7-a928-39117298b803.png">

**Comment by johnmay** [comment]
Depict is not for depiction queries (SMARTS). You put molecules (SMILES) in the top and SMARTS in the "Enter SMARTS pattern..." where you want to match.

```
SMILES: c1cccnc1-N1CC=CC=C1
SMARTS: **[#6]~1[#6]~[#6][#6](=,:[#7][#6]~1)!@-[#7]-1-[#6]-[#6]=[#6]-[#6]=[#6]-1
```

Works correctly for me.

**Comment by johnmay** [comment]
Would help if you had your code example that was not working.

**Comment by Le0nT1** [comment]
But the 

> 

Thanks.
Let me do more tests first. It seems working after I restart my IDE.

**Comment by Le0nT1** [comment]
I think the @, !@ and ~ symbols work as expected. The problem I encountered is more complicated including aromaticity expressions in the SMARTS string and the software I used (Marvin Sketch) handles SMARTS string a little differently than CDK toolkit.
I will close this thread. Thank you, dear developers.

**Comment by johnmay** [comment]
We have different models of aromaticity to pick and choose as you see fit. By default for SMARTS we apply Daylight aromaticity (since SMARTS was created by Daylight). However it is possible to use a different aromaticity model.
