### ISSUE TITLE
AminoAcidCountDescriptor logs warning when instantiated

### ISSUE THREAD

**Issue by StaffanArvidsson** [cdk/cdk#930]
I'm getting the following warning every time I'm instantiating the AminoAcidCountDescriptor
class:
org.openscience.cdk.io.cml.CMLHandler WARN: Detected unknown convention: cdk:substructureList

I'm not a chemist so I cannot tell if it actually outputs the correct descriptor results, but at least it outputs some values when I send in a molecule with some amino acids. Should I be concerned with the error message, I assume there is some bug in there somewhere? Tested in both version 2.7.1 and 2.8. I'm running on a M1 chip mac in case that matters.

**Comment by johnmay** [comment]
It looks like it's just a skipped attribute in the CML input. @egonw is the CML wizard who will be able to confirm if there is some special semantics being missed or not. Based on what the descriptor is doing and the test cases I don't think there is anything wrong.

https://github.com/cdk/cdk/blob/main/storage/pdb/src/main/resources/org/openscience/cdk/templates/data/list_aminoacids.cml#L2

```xml
<list title="List of amino acids" convention="cdk:substructureList"
        xmlns="http://www.xml-cml.org/schema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    
```

**Comment by StaffanArvidsson** [comment]
So I simplified my pom.xml to just pull in cdk-bundle (without any exclusions) and simply using the test;
```java
@Test 
public void testCMLWarning() {
   new AminoAcidCountDescriptor();
}
```
prints that warning to System.err given my setup. So it should probably be pretty easy to replicate?

**Comment by johnmay** [comment]
@egonw Pretty sure just removing the ignored ``convention="cdk:substructureList"`` would be fine?

**Comment by egonw** [comment]
Not 100% sure. It sounds like a convention was not registered, maybe because of module splits. But if the reading works fine otherwise, it's probably fine.
