### ISSUE TITLE
Flipped stereochemistry for Glucose using `InChiToStructure`

### ISSUE THREAD

**Issue by MaybeJustJames** [cdk/cdk#933]
I am parsing this InChI:
```
InChI=1S/C6H12O6/c7-1-2-3(8)4(9)5(10)6(11)12-2/h2-11H,1H2/t2-,3-,4+,5-,6+/m1/s1
```
and producing an image with `DepictionGenerator`.
I expect an image like:
![image](https://user-images.githubusercontent.com/26444312/202723071-93bd5376-ac04-4dd4-940a-5efc7699abf6.png)

But this is the image that CDK is generating:
![inchi](https://user-images.githubusercontent.com/26444312/202723140-6bd78a6d-fa3e-4859-836b-9e2bdc93f173.svg)

Note that I am expecting [L-Glucose](https://pubchem.ncbi.nlm.nih.gov/compound/L-Glucose#section=2D-Structure) but the image produced is of [D-Glucose](https://pubchem.ncbi.nlm.nih.gov/compound/D-Glucose).

The code I am using is essentially [this](https://github.com/ipb-halle/cdk-inchi-to-svg/blob/master/cdk-inchi-to-svg/src/main/java/de/ipb_halle/msbi/cdk_inchi_to_svg/App.java):

```clojure
(defn use-inchi [inchi]
  (let [cob (DefaultChemObjectBuilder/getInstance)
        genf (InChIGeneratorFactory/getInstance)
        parse (.getInChIToStructure genf inchi cob)
        ret (.getReturnStatus parse)
        warning (if (= ret INCHI_RET/WARNING)
                  (.getMessage parse)
                  nil)
        mol (.getAtomContainer parse)
        dg (.depict (DepictionGenerator.) mol)]
    (if warning
      (println warning)
      (do
        (.writeTo dg "inchi.svg")
        (println "Success")))))

(use-inchi "InChI=1S/C6H12O6/c7-1-2-3(8)4(9)5(10)6(11)12-2/h2-11H,1H2/t2-,3-,4+,5-,6+/m1/s1")
=> Success
```

Environment:
```
$ java --version
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Debian-2)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Debian-2, mixed mode, sharing)
```

* CDK 2.8 from maven
* `net.sf.jni-inchi` 0.8 from maven

**Comment by johnmay** [comment]
Where did you get InChI from, that is the InChI for D-glucose.

ChEBI: 
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:17925 D-
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:37630 L-

PubChem:
https://pubchem.ncbi.nlm.nih.gov/compound/79025 D-
https://pubchem.ncbi.nlm.nih.gov/compound/6971003 L-

ChemDraw:
https://chemdrawdirect.perkinelmer.cloud/js/sample/index.html#

```
alpha-D-glucose: InChI=1S/C6H12O6/c7-1-2-3(8)4(9)5(10)6(11)12-2/h2-11H,1H2/t2-,3-,4+,5-,6+/m1/s1
alpha-L-glucose: InChI=1S/C6H12O6/c7-1-2-3(8)4(9)5(10)6(11)12-2/h2-11H,1H2/t2-,3-,4+,5-,6+/m0/s1
```

Marvin JS:
https://marvinjs-demo.chemaxon.com/latest/

```
alpha-D-glucose: InChI=1S/C6H12O6/c7-1-2-3(8)4(9)5(10)6(11)12-2/h2-11H,1H2/t2-,3-,4+,5-,6+/m1/s1
alpha-L-glucose: InChI=1S/C6H12O6/c7-1-2-3(8)4(9)5(10)6(11)12-2/h2-11H,1H2/t2-,3-,4+,5-,6+/m0/s1
```

OPSIN:
https://opsin.ch.cam.ac.uk/

```
alpha-D-glucose: InChI=1S/C6H12O6/c7-1-2-3(8)4(9)5(10)6(11)12-2/h2-11H,1H2/t2-,3-,4+,5-,6+/m1/s1
alpha-L-glucose: InChI=1S/C6H12O6/c7-1-2-3(8)4(9)5(10)6(11)12-2/h2-11H,1H2/t2-,3-,4+,5-,6+/m0/s1
```

BTW you really should not parse InChIs :-). They are an identifier not a representation for transmitting chemical data. It is an addition not the primary presentation.

**Comment by MaybeJustJames** [comment]
Indeed. Sorry. This can be closed as invalid.

> BTW you really should not parse InChIs
Sorry to hijack this but what should I be parsing as a serialisation format for generating an image?

**Comment by johnmay** [comment]
SMILES

**Comment by johnmay** [comment]
or MOLfile if you have coords allready
