### ISSUE TITLE
checksum for jar from release page

### ISSUE THREAD

**Issue by uli-f** [cdk/cdk#946]
Is it possible to add a checksum (e.g., SHA256) for the jar from the release page to add some security for users who d/l the jar?

We use the jar in a python application and the easiest way to d/l the jar is from the GitHub release page.

I saw this on other release pages in GitHub, for example here https://github.com/dashpay/dash/releases/tag/v18.2.0, file  `SHA256SUMS.asc`.

**Comment by johnmay** [comment]
Sure if there's a way to automate it in the build - otherwise I will probably forget to do it. They get signed for maven deployment but you're right would be a good idea for the bundle

**Comment by uli-f** [comment]
Happy to contribute to an automated solution.

How do you publish an artifact on GitHub? Do you initiate a release from maven or from a GitHub Workflow?

There seems to be a maven plugin to generate checksums: https://github.com/DependencyTrack/dependency-track/issues/205

And alternatively a GitHub Action: https://github.com/marketplace/actions/generate-release-hashes

At first glance, the GitHub Action might be easier to setup.

**Comment by johnmay** [comment]
Maven plugin sounds good, I just upload it manually which I'm happy with.

**Comment by johnmay** [comment]
Checksum only needs to be in the cdk-bundle module

**Comment by uli-f** [comment]
Okay, I'll have a look at the maven plugin then.

**Comment by uli-f** [comment]
Opened PR #947 

Checksum files are generated for the `cdk-bundle` uber-jar as part of the package goal. Each checksum type is output in a separate file.

Please feel free to remove any unwanted checksums in the `pom.xml`.

**Comment by uli-f** [comment]
Closed with merging PR #947

**Comment by uli-f** [comment]
@johnmay I added the ability to add checksum files a while ago in #947 and you merged it in Jan 2023. However, I just realized that the checksum files haven't been added to any release since. Is it possible to manually add the checksum files to the latest [2.9 release](https://github.com/cdk/cdk/releases/tag/cdk-2.9)?

**Comment by johnmay** [comment]
Will do, sorry releases are infrequent enough that I need to remember to upload them as well.

**Comment by johnmay** [comment]
Done, please remind me if I forget again
