### ISSUE TITLE
Reproducibility of SMILES parsing

### ISSUE THREAD

**Issue by hechth** [cdk/cdk#957]
Original SMILES `Nc1ccc(cc1)C2(CCC(=O)NC2=O)C3CCCCC3` produces two different SMILES using `SmilesGenerator.createSMILES(IAtomContainer...)`, more or less random. the SMILES are of course equivalent, but the Atom labeling of C1, C2 etc. is changing:

`O=C1NC(=O)C(C2=CC=C(N)C=C2)(CC1)C3CCCCC3`
`O=C2NC(=O)C(C=1C=CC(N)=CC=1)(CC2)C3CCCCC3`

This makes writing automated tests for things that include smiles quite tricky since a simple comparison of text is not possible.

Did anyone else also face this problem or is there a known fix to that?

Thank you very much in advance

**Comment by hechth** [comment]
ping @zargham-ahmad

**Comment by johnmay** [comment]
Hmm, based on your description I can't reproduce:

```java
    public static void main(String[] args) throws CDKException, IOException, FontFormatException {
        SmilesGenerator smigen = new SmilesGenerator(SmiFlavor.Default);
        SmilesParser smipar = new SmilesParser(SilentChemObjectBuilder.getInstance());
        String smiles = "Nc1ccc(cc1)C2(CCC(=O)NC2=O)C3CCCCC3";
        for (int i = 0; i < 10; i++) {
            IAtomContainer mol = smipar.parseSmiles(smiles);
            System.out.println(smigen.create(mol));
        }
    }
```

Unless you're meaning if you put different orderings in you expect them to be canonical in which case you need to tell it to do that. By default SMILES are non-canonical for performance reasons, canonicalisation uses InChI labelling.

```java
int flav = SmiFlavor.Default +
           SmiFlavor.Canonical + // turn on canonical labelling
           SmiFlavor.UseAromaticSymbols; // write aromatic as lower case
SmilesGenerator smigen = new SmilesGenerator(flav);
SmilesParser smipar = new SmilesParser(SilentChemObjectBuilder.getInstance());
String smiles = "Nc1ccc(cc1)C2(CCC(=O)NC2=O)C3CCCCC3";
for (int i = 0; i < 10; i++) {
    IAtomContainer mol = smipar.parseSmiles(smiles);
    // may want perceive aromaticity here
    System.out.println(smigen.create(mol));
}
```

Please provide more code context if this doesn't answer your question.

**Comment by hechth** [comment]
Hi, we've been using CDK (version 1.4.19) with IKVM compilation inside our C# app.

The code we use which generates the alternating smiles is the following.

Are there things which are somehow platform dependent, like some randomization or so based upon which the C1 and C2 carbons are chosen?

```C#
var smilesParser = new SmilesParser(SilentChemObjectBuilder.getInstance());
container = smilesParser.parseSmiles(smiles);
if (container != null && smiles.Contains('c')) {
    Kekulization.Kekulize(container);
}

implicitHydrizedContainer = ExtAtomContainerManipulator.convertExplicitToImplicitHydrogens(container);
smiles = new SmilesGenerator().createSMILES(implicitHydrizedContainer);
```

**Comment by egonw** [comment]
Hi @hechth, CDK 1.4 is really old. We know there are problems with SMILES in that old version. Please upgrade to a more recent CDK version. I do not think any of us has the resources to support CDK versions that old.

**Comment by johnmay** [comment]
Please also note there is [NCDK](https://github.com/kazuyaujihara/NCDK) for .NET

**Comment by hechth** [comment]
Thanks, I wasn't aware of that!

**Comment by johnmay** [comment]
Please reopen a new issue if you still have issues on the current version.
