### ISSUE TITLE
How to handle MDL files with aromatic bonds?

### ISSUE THREAD

**Issue by StaffanArvidsson** [cdk/cdk#962]
I'm trying to use [Ketcher](https://lifescience.opensource.epam.com/ketcher/index.html) to create a front end for a web service and call the backend (with an MDL file) which runs CDK code and performs QSAR predictions. However, it seems like Ketcher has some extended version of MDL that include aromatic bond information which CDK cannot parse. These MDL files can be loaded in e.g. RDKit. So my question; 1) is there a plan for adding this extension to CDK in the somewhat near future? and 2) is there a way to still read these extended MDL files and 'clean' the input in some manual way that guarantee the input will be correct? 

Some more details; when reading the MDL using `MDLV2000Reader` and `MDLV3000Reader` the readers will create IAtomContainers with the correct number of atoms and bonds, but e.g. when trying to generate a SMILES (simply for testing purposes) it will complain about bond order not being set. I've included two test-files that has this issue (had to change to a `.txt` extension for github to accept them):
[ketcher_v2000.txt](https://github.com/cdk/cdk/files/11016435/ketcher_v2000.txt)
[ketcher_v3000.txt](https://github.com/cdk/cdk/files/11016437/ketcher_v3000.txt)

**Comment by johnmay** [comment]
Aromatic bonds are a query feature of MDL files no an extension. CDK will parse them but you have a query molecule and not "real" molecule like you want. You can not reliably/portably turn these into a molecule without potentially modifying the formula. Any tool that does this is an approximation. The issue is you don't know where the hydrogen counts are, SMILES does not have issue hence aromaticity is OK to use in SMILES.

If you need a query from a MDL file you need to set they hydrogen counts and kekulize. There is an option where we can put in "a" representation when there might be multiple but currently you need to do it manually, something like this:

```java
IChemObjectBuilder bldr = SilentChemObjectBuilder.getInstance();
try (FileReader fr = new FileReader("/Users/john/Downloads/ketcher_v2000.txt");
     MDLV2000Reader mdlr = new MDLV2000Reader(fr)) {
  IAtomContainer mol = mdlr.read(bldr.newAtomContainer());

  for (IAtom atom : mol.atoms()) {
    if (atom.getImplicitHydrogenCount() == null) {
      switch (atom.getAtomicNumber()) {
        case IAtom.C:
          atom.setImplicitHydrogenCount(Math.max(0,4-atom.getBondCount()));
          break;
        case IAtom.N: // D2 might be 1 or 0!
          atom.setImplicitHydrogenCount(Math.max(0,3-atom.getBondCount()));
          break;
        default:
          atom.setImplicitHydrogenCount(0);
          break;
      }
    }
  }
  Kekulization.kekulize(mol);

  SmilesGenerator smigen = new SmilesGenerator(SmiFlavor.Default);
  System.out.println(smigen.create(mol));
```

Sorry this is automated but I'm on the fence about bad data processing, garbage in, garbage out.

**Comment by johnmay** [comment]
I'll take a closer look, it's true we need a better option for this but fundamentally anything we do is going to be a bit of a hack since the data isn't there.

You can store coordinate in CXSMILES BTW

**Comment by johnmay** [comment]
Here is "fixed" code, forgot to clear the bond orders.
```java
// clear bond orders
for (IBond bond : mol.bonds())
  if (bond.isAromatic())
    bond.setOrder(IBond.Order.UNSET);

for (IAtom atom : mol.atoms()) {
  if (atom.getImplicitHydrogenCount() == null) {
    switch (atom.getAtomicNumber()) {
      case IAtom.C:
        atom.setImplicitHydrogenCount(Math.max(0,3-atom.getBondCount()));
        break;
      case IAtom.N: // D2 might be 1 or 0!
        atom.setImplicitHydrogenCount(Math.max(0,2-atom.getBondCount()));
        break;
      default:
        atom.setImplicitHydrogenCount(0);
        break;
    }
  }
}
```

**Comment by StaffanArvidsson** [comment]
OK thanks for your help! Just for completion I'll say that currently ketcher doesn't support creating CXSMILES at this point so going from ketcher -> CDK that's not a solution for us. We came up with the alternative solution of hiding the "donut" button in the ketcher UI in order to create a kekulized structure and hopefully that will resolve this issue for us. 

And further for completion, that clearing of bond orders did not do the trick for me either. But now I do not need to use it, by forcing the use of the proper format instead.

**Comment by johnmay** [comment]
I will still add a utility for this as we can do something better with those inputs.

**Comment by ctapobep** [comment]
@johnmay the kekulized structure will always be one of the resonance structures, right? Which is still one of the correct representations of the molecule. I wonder, in what contexts will the information loss cause problems? I guess only when generating some chemical IDs/doing searches?

Also, curious why are aromatic bonds in MOL is a query feature? It's a proper depiction of the a regular molecule.. From MOL perspective everything that doesn't provide the precise info on bonds/Hydrogens is a query?

**Comment by johnmay** [comment]
> @johnmay the kekulized structure will always be one of the resonance structures, right? 

No - commonly it may be a tautomer or just a different structure.

```
Cc1[nH]nnc1
Cc1nn[nH]c1
O=c1[nH][nH][nH]c1=O
```

> Also, curious why are aromatic bonds in MOL is a query feature? It's a proper depiction of the regular molecule.. From MOL perspective everything that doesn't provide the precise info on bonds/Hydrogens is a query?

Not quite - there is no way to set the hydrogen count. Well except again hydrogen count is a feature.

The reason for it is aromaticity is a derived property. Different toolkits have different views of what is/isn't aromatic. Therefore in all case a Kékule structure is always preferred.

**Comment by ctapobep** [comment]
> No - commonly it may be a tautomer or just a different structure.

Hm.. But aromaticity is _extra_ information. We should always be able to generate one of the resonance structures from the aromatic info, no? Or do you mean it'll be too complicated to make it work right in all the cases?

> Not quite - there is no way to set the hydrogen count. Well except again hydrogen count is a feature.

The inability to count hydrogens is what makes it a Query MOL?

**Comment by johnmay** [comment]
1) If two molecules have a different formula would you say they are resonance forms?

2) not quite just that. You might be able to find more info in the old mdl papers but we are stuck with it unless you start introducing bespoke handling/semantics and that helps no one and you may as well just invent your own format.
