### ISSUE TITLE
unexpected not reading of properties in ChEMBL SDFs

### ISSUE THREAD

**Issue by egonw** [cdk/cdk#963]
The CDK tests show that the (iterating) SDF reader will read `> <PROP>` fields in the SDF as properties on the `IChemObject` but the current ChEMBL have file content that seems to prevent this. For example, the SDF for [this entry](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL3183843/) has this in the file:

```
M  END

> <chembl_id>
CHEMBL3183843
```

If I remove the line after the `M  END` then it reads as expected and a property is read:

```
M  END
> <chembl_id>
CHEMBL3183843
```

Similarly, [this ChEMBL API call](https://www.ebi.ac.uk/chembl/api/data/molecule?format=sdf&molecule_chembl_id__in=CHEMBL4297182,CHEMBL564829,CHEMBL3673452,CHEMBL603469,CHEMBL1946170,CHEMBL3889654,CHEMBL1983268) even has two empty lines:

```
M  END


> <chembl_id>
CHEMBL564829

> <chembl_pref_name>
MILCICLIB


$$$$
```

@johnmay, what do you think about this?

**Comment by johnmay** [comment]
I think chembl have inconsistent SDF files :) - not the first time (one release they had two $$$$ by mistake). 

We should accept these though, I’m likely just going to rewrite the whole v2000/3000 reader/writer but will probably fix this before then.

out of interest is the id also in the title of the record?

**Comment by egonw** [comment]
> out of interest is the id also in the title of the record?

doesn't seem so. neither in the API call, nor in the individual SDF

**Comment by markfortner** [comment]
I noticed that the header of each record indicated that the ChEMBL team was using RDKit to generate the file. So fixing the actual source of the problem may take longer. 

@johnmay Anything you can do in the mean time to make the CDK SDF reader more forgiving would be appreciated.

**Comment by johnmay** [comment]
Like I said the CDK MDL V2000/3000 needs a rewrite it's just a bit miss-aligned at the moment. 

You can actually use the V2000 reader as a reentant reader (call again for next input).

How can I can get an SDF from the webpage? Really not obvious to me but perhaps I'm getting old - I would expect it to be near where the SMILES/InChI is but couldn't find it. From the API at least this seems to read the properties fine:

```java
  public static void main(String[] args) throws IOException, CDKException {
    URL url = new URL("https://www.ebi.ac.uk/chembl/api/data/molecule?format=sdf&molecule_chembl_id__in=CHEMBL4297182,CHEMBL564829,CHEMBL3673452,CHEMBL603469,CHEMBL1946170,CHEMBL3889654,CHEMBL1983268");
    try (InputStream in = url.openStream();
         MDLV2000Reader mdlr = new MDLV2000Reader(in)) {
      IChemObjectBuilder bldr = SilentChemObjectBuilder.getInstance();
      IAtomContainer mol;
      while ((mol = mdlr.read(bldr.newAtomContainer())) != null) {
        System.err.println(mol.getBondCount() + " " + mol.getProperties());
      }
    }
  }
```

```
38 {chembl_id=CHEMBL564829, chembl_pref_name=MILCICLIB}
41 {chembl_id=CHEMBL603469, chembl_pref_name=LESTAURTINIB}
35 {chembl_id=CHEMBL1946170, chembl_pref_name=REGORAFENIB}
46 {chembl_id=CHEMBL1983268, chembl_pref_name=ENTRECTINIB}
39 {cdk:Title=118009787, chembl_id=CHEMBL3673452, chembl_pref_name=GZ-389988}
35 {chembl_id=CHEMBL3889654, chembl_pref_name=LAROTRECTINIB}
49 {chembl_id=CHEMBL4297182, chembl_pref_name=PEGCANTRATINIB}
```

Annoyingly yes they don't send the title in the SDF records... grrr.

Anyways 0..n newlines is fine (testing with):

```java
String str = IOUtils.toString(new InputStreamReader(in, StandardCharsets.UTF_8));
str = str.replaceAll("M {2}END\n\n", "M  END\n");
MDLV2000Reader mdlr = new MDLV2000Reader(new StringReader(str));
```

I'm a bit suprised the IteratingSdfReader doesn't just use the SDF property input from the underlying reader (e.g. V2000) but I think I did have a good reason why I didn't make it do that. Anyways like I said, needs a major clean up - see all #952

**Comment by johnmay** [comment]
Also note the primary SDF has correct formatting (no new line) - I think this is more likely the ChEMBL API is sticking together different parts rather than delegate to RDKit.

``% curl https://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/chembl_32.sdf.gz | gunzip -c | grep -A2 'M  END' | head -n 30
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0M  END
> <chembl_id>
CHEMBL153534
--
M  END
> <chembl_id>
CHEMBL440060
--
M  END
> <chembl_id>
CHEMBL440245
--
M  END
> <chembl_id>
CHEMBL440249
--
M  END
> <chembl_id>
CHEMBL405398
--
M  END
> <chembl_id>
CHEMBL503634
--
M  END
> <chembl_id>
CHEMBL503643
--
M  END
> <chembl_id>
```

**Comment by johnmay** [comment]
I've send chembl help an email as well, the other wonky thing is they had extra spaces before the $$$$. Whitespace is significant in SDF (much like python) so if you add extra you get a different value. In this case it was the ``pref_name``. However I think it's most sane to just trim of extra at the beginning/end - any spaces in the middle will be kept.
