### ISSUE TITLE
Molecule alignment setting in org.openscience.cdk.depict.DepictionGenerator

### ISSUE THREAD

**Issue by parit** [cdk/cdk#978]
I am giving the following atom-atom mapping smiles string for a reaction 
`[OH2:1].[CH3:2][CH2:3][CH2:4][CH2:5][C:6]([NH2:7])=[O:8]>>[NH4+:7].[CH3:2][CH2:3][CH2:4][CH2:5][C:6]([O-:1])=[O:8]`

to the cdk org.openscience.cdk.depict.DepictionGenerator to generate an svg. Note that water is the first molecule in my smiles string. Strangely, in the image generated, water is the second molecule (See the attached image). 
![10001](https://github.com/cdk/cdk/assets/3196240/39b29182-e43d-4b24-bde1-fbd5f7cb298d)

On further digging I found org.openscience.cdk.depict.DepictionGenerator#alignMappedReactions setting that seems to be influencing it but there is no way to change it in the API. Is this deliberate? Could someone add more information as to how this field is exactly used or can be influenced?

**Comment by johnmay** [comment]
Yes it is reordering/aligning them based on the atom mapping using the products a reference. In the products the oxygen appears after the NH:7. If you put the NH4+ after the main component then it would put the water before:

```
[OH2:1].[CH3:2][CH2:3][CH2:4][CH2:5][C:6]([NH2:7])=[O:8]>>[CH3:2][CH2:3][CH2:4][CH2:5][C:6]([O-:1])=[O:8].[NH4+:7]
```

![image](https://github.com/cdk/cdk/assets/983232/ae74bdb6-fe2a-431f-823a-88e4b5a4a1cc)

Set

```depcitionGenerator.withMappedRxnAlign(false);```

to keep the ordering unchanged, normally this gives a worse depiction.
