### ISSUE TITLE
Sonarcloud wants to use Java 17

### ISSUE THREAD

**Issue by egonw** [cdk/cdk#989]
They wrote in [this PR](https://github.com/cdk/cdk/pull/988):

`warning The version of Java (11.0.20) you have used to run this analysis is deprecated and we will stop accepting it soon. Please update to at least Java 17.`

They provide further info at https://docs.sonarcloud.io/appendices/scanner-environment/

I'll make a PR.

**Comment by johnmay** [comment]
Sounds good
